---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgB8cf7ZCtSo21rOPetWbjYxSY4GAWxiiIUgeTnBhMaEt/kJvkgtOCQbzFH6TMzw0XqRZoCmoogukFdJzecf7b63A6gzFgqmSwCNEV9EbApi11IURQWIlBLiEKIZ1quX3O5nonZwJsi4qLfvf1AZDKC2+wUzn/5keXZRpkTIcckeGy3KKxGrgR7TLkuT9IaT0RsEFnS263yFAznVp0KfA5qo3/PXnM+XGtLPaqrllvUqmVeQ16yE0+FdbCMabPR+YO8XvYmqyHfW4DT6aO6jWeHPDC8h/NugH/B3fNLpuj2mN+ELWR6EokxZidCsSZM4w3rGobc16kpj76tB89gq2FosMCj3kvMC+2sHz+E8GHdDZn07HJr+jkMvPAP6WDVmSYOXFsKqGukreI+oqUEvqaa5CBCCXGz+JbQNs459VO0IxD+HgE5oGqGltucd7wDaRtI5a633jDJNf/zj6bEvfZKGnCqOIwCZzbVzpLGAQNYA1QsU5PCKdDBZOy9CSxuwMZLuKHHUrJ/dYej8zI7T8BIDuospyQBmrIkDVbYV95TSzLIxe4BBpy16+fa8htUbKCGPDnonALVfHY0AYiqRFnUJWsnMNO/cpVo0QQfRxdT+rrQ44+IOm+ZG/+dO5GfwMlvVhh/rKMuBL4vXCtrFm7CgKGeJl4mWMJXxZ0EEpKuPOVCroZZz2i6rkiGjYWmm4gF46gWIKvsi2wg=
    secretkey: AgBWBoEATkh4BwyjcrguFmIBuWckPVwFxuxmuUOfPA1Va8/3y5mSF71rbSeqDCPilWEsVyXWkH24X+xMTWsq8gE7JmvDZo4t7rZSOqGijjb24ZuTmNZUuo/+1CdWDVquK6KKFyhP3M1VwiP10tU4lXJSJdHWKJZtlPeqXN60VqatNBlwE69cBDtGzZifeu/tAbrCtU+fzj/kgVVZyFZwmwQQXgcNGjkhVYigj6LdvGlQb0a4k2P3cowvOIMIrld74sAbCInM36BxaaT1FgQ1Ev0hMIORrULEJ9KFPP3n0JW0XwB/M8eEmXcfSkI9OJRWwJ473GJNb6UiirB+Pk2udghBS9c7tAqGeSPQmfIpv9mx/toifkvOHdHqmIdhAleSpDoeIpP1OFGFEgAWPm88Gn9BI3Ok0m5XSnMAGOurK94KKBmOHLpn+D8QXgPN8SLtvLMLO1alB6JiPQRMTAwAFw4VnOu8G6JOOY8ePChV1XrAvbnxuj5l72Yc0/Pc4h+8IvPPDCsFujqqoKKdLW5MVrgkG74tA9oaZxrFKg/Uk2Sz3P5ClyRg73+5ILHolL6GMNkwEI1si22z2+xYsXVvXqxjEgqM83/jL+8Vi9P8qh3JJf8YwTFwDWeTF7yYt2sMBn6ZrCPXOBq1iVCRYpMROMtsyjEaioNbZLEaGvz6CcY/4SvzMO8J2gRXbEX3jXj1eH0MZ1KyoiXjpR8=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
