---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgBS8Albg8JZCFo9M3MXIqnx6+hHTs6DETUB/pgjg6yIVlQsNoQEO+AhiQ96qyW7tzlYXWNTrx3qoTd+vl4SJb/G7f/KoMe0tqJTnXF0MkyX34xHcrZj+k3hntDZM9hfy1GWMRuEjCaqTyVkQ6wc0r6NHsIMlA/7SO/Q0dDtOFkOaAnTADo7HCIpuaU8cvfChpk/QE9LeiqrQWQZPb4X8tkxHQpu4CKhIjur7/PU6uuZWzA8fI2a32pbY7Kjo1Zf2ibZPD2fGiRFraDA+D9T6mQwV7lHFERWR4c1Lu5GbTJi0PdgNX+9Ux9AH6gc+z6zVBYvPGnAQmwMjScEjZiFqFBBc5Khc3cIwm6Q4rTI4O66iNVCu0k7IAyiUlcFmCJV3itBCX0i7Atv0UQiCNjG9FWZGh4pZk61gQ5p5W988MKilPucKuvq9Jzes4iee3s7pdq5bjmomZhb1zlfskmgaOX2/tbXzB2XwMFN7RQ+xORlRQcOckrNvDWUn8iilm/VafTjUEr6Qum9HSfSmmr4F8RJDGWF19Yw+SELEXSZKYTW+TNjwEblt0NKx478r2zk8Zx43FEzq5VaRYEmzIBewX/+EkeYmPJrVzYId5YhzQjGozgy8pXkNBSeidt4bZ23bpPf6ZjcDt5aPfyJute/lnF4riqgIUvt6tCc4qHzT8L1gSU7GlnOwL1a7KRk9pXPHqlPvBECM4wCMsQ=
    secretkey: AgCFFwstHFOkyzKXgza4veNL+d8WrjuOvUtFtnJLYoK1PYmRq7wseg3i+X/iSdAwZ0Oim3c9s2AxHVtReQoNLL4S23nk5+PcRJcbP0Va/nzdlAURZs5wQlGzWGItVVvg9rfOGIg1ZmRXxRE8onY/JmsCi56bBNmLbEwQU0Ujz6iXLZ6MEfobLrb/JiE79tJoXnKCTSzel7sFuQq/ZZOYI1eRpdZ1hyNIM3swxpEtwBoVvTzZk5JNwa+u4OX0b+mwUfJNLvNX4NmcCEoNNTpP5wSihu7EUMNvNmge53dwSt/ZYNoWlpd6znjM6910o2TcLMAu80NqROAvTFNKfG8DB8hiuXi39hg7D/deQeKhIW581eYSdb1zeBZwQamTJ1D7U+DShzzYIBJlA4Ez/NzldGZJP2LeotmdG7nvHJAxDPQ8OwZXObY7aMUl4T7rie4cpDvq/Tr0mTOg0vlohqQAUlYtzLvqZxVd53FbK2trTkJQCplll3r9IwTXzU9GpcAU9FZxbwKevZ6W17taVv1jFS/+O2ar/y7PogR3vDrOyOwz7lJZMw8Oxt8JfCyAdtgOd5eczTVpFNHqTABkCcSosVQ1+h1oARBSiSl9sxiyE/kKDADRwIc2RckOV1ZL089RV0FMsr8HS2pzqzN4QCxzSl7IR0g9mrlbQhoD0wVfcq/QBmc4BK8HqXe9o1CKdVFoKGAlMG1sCUuPjq8=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
