---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgAxjJaYgl9ALs/SjN/T7eU85vpGyLwD6YPM8BywgEATJgbVJQKZ5M/Lz0269k3iFEt9XN4g7bSSQnq249RlCjloGBPDYwz/xpEs7PTFVgl+xp+Fo0jvWQI1dQtj1+qHi1P9HjkHZNIt98JCpfSEg/T+OZoQNpNnNq0Jf3r39+yPz01d6FP3R0LZdpYfbfhmBMfwBIgBQnQIDCjY5n6yo1oLMlLljFoegZSrLzin1sSc6OCeValW5Iuu3HgS/H+C9qW4Dx0CuMb6a6UNjMEDTf8NcF9Dk9JN4w/bi1ai5NLX+y62J9OA6fXDf6gyM8XapIFyRoeX7zYeq7mmgXPnDFdilKgXBLarp1H8nGm0Dova+lGeqExp2sUs8s2KNPfWD4G4M+ySKrAcLZBD9CsUAP8GAvV5mETTyVAnTIBeyW/YOdEKSGSNXSnkWLoViNdpvsR6yS3C7ztTfPjPte57NE8WWBvMzdCQ49HQf7DJ7Z3ucy1STGPVsuj1aOjHKTQf8CQ43DMBQGVpiH4TAzBE1CLlDPN2Xn+2zAP6bsIRb2YN5JmHMBS1sJfjXREtnPfcsxGILfux5AbBP3u0O6P7LWHcW9FwcDQRASca8YlKKo3Drs0C8shS085Y65jh2yYa+/WoYmQS9omoQ63fNpW/zF746115+zdBBTv0vn7yCmcLDjPQorJYl1EYATXNcXNUlJ7C933cwcHj4pE=
    secretkey: AgBOyn8L+3gabs8D7e2oBwveOHmmdo4N5gfqn8m2TZx0VUybZbia4A5fGVek4yZEOGpvT8oOe++Ou6UvfPPV3srqJ9/uMi0cV56IWkaCWvYhg9aprI0duJRs9wrzRUAdiDhtvWiqkL8ap88x/CHM6og3X5DvZYny6ay+tGEvDjaeFgr6GQr2PiLq72PF1BrdkyUrIT0yBsijWKEOKHRrjq64nA93f3fk1GxBnym6Qg/qviEt+tf07wuZ5xbJ3uHjWKPiqw7Fz5AGhyFVNOLTYWUDbbxPQqWEamMPNSQNnuoKAA2eFqEf93fNiZgH1ypWq8ko0v9SCi8aLRMDJ9neGcbliWB3fNeQbQkeqSg87Trz30D3xTYExNZpXImHr/SRLKid1hIzWgl15fmF2Qxe1TEGL1PuZ/uVDM67dJus2CtV2bx94s+ktRrIelaUo763xLrhwH4KUQMXBZ3LD8ZjEk+JG1NTF2fysZNxafZJCSk1LmV7gTfcPDqYPDde2tDoktWx0MQlRy0eqV2sr4TYMrHVFuaL0EvJ3hUOuYXXZWtYg0pJYIrim+2gohV1EopRlY06GdkETFuW8NvBNAskQs02RNWEG/i/Eh3QRkKjWTGbtZ/RObtHwFyBPdpTK2vKjxTCKefnWtgK8MdsonUB/XjZ548BieCe2bgVJOjOSKTZxAmG9mYVKs92fuPwmBSkw+He+TVNTykAYX8=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
