---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgAOz/kfOnpj/axBY055oocZ7yvOIyC9zkOLgAIBWjc59g464HPzBAggPXWxDD6iJMAJoHEdjyAyb5gvHizHWSYjhoa6dKpbczYnIBsVqaM2zH+fx3CmLaHaRl+w82rMwPu8PHylwBRG6Uau/M/XomueHs5w1SztYxcM9iZaceqPUvQjkxj6I3DzNQW1EKdqRcS3HY0zTxDde8OQZC3fraqNO6Z42RMqXDzwAvYigP2QtcXEIF5B3WN+5xzEqZb0rveaHiFY0G592fJXcbpxRBQqwVvCXIqN6Jpyw6c/4h97zPSlnXvPsFyB7GVm2WobAEfkpfhV6o1dRpfRFvmfvMBGuehlmwA6ZBoUx+CafHtYqW1sg7SNccs0dRhwP5kHefdRv5yWkjECr5TuCgYs/pBDozWipy+K0kjXrZvf6hngFOZHBEPD8mL2x94fQyBAiQ1j7IMAbynjQzvAhuI+nalJx8uLrNh1XTt0jPIdWJ8eNhz2dJD6GqIqhXAMUyKNYkjd4IQibu/bzLaQaucD7p5/83y5C2dcWPjqHf6CLp6XuEEJITGk0lCUStzMExqDhz2JJGFoDTSRg5N9ZSZWvSQEqGEzx2MTWj/JUQ7ErBAcDiIoO9JTAu3kZMr8NZ/L7bCfqANQqup9GMHAjZMVKEF0OX2EBASPBi/8NygkjwLIsNPuPcDypkpo4pyzuSIh+Qp+/4ngXYXA7IM=
    secretkey: AgB2xw43eQBFbuB1OTrzQk+uN28S9Rmqgw4Tj4QXHDNqvfalxF2+WyPjIVkhNBCDy/QJv4vNBlTvhru/PQSWiFPQfjskel6Duv2luskNU4q6STtW5U220KWvaLQQcbSvw20flFUV7EIlAa1wN9Yt6PeE2vGaXFgy5IY7AplhcJGn9e9yzsIAywfbzZGqKGFOmf5Pr8PS06+u1zOx8h3ci13iFdpHT2Du8ZqTcY/t2OhS1ztqcgBXKz772nFmEfvDBQYkK7H1ZjHgSu1XG94xu9++5+QZnvnPqFoxIpPM5UcJPHqEPqSrx5Pqm/8iC0JFqPqRLXci4XS+yZfkQ37pWNw1aM8kteDgEPz7y6MTc1ByZz2TCE8k+C0oanVuF6RLPnQaaq2SnJMbfMPyIYooeRRpgBNINvYWvFSISz3oRt4udv9O+JBOqig/gTpxp8uQ6PTpvX9FYuyGjLbDohobmsQCrU7Edu7JdC+8VBF2I0YDcVk2atbVmtK5WE0bt65x4JpwUGhUBKVqt7S4KGJctRb49stXYWrxx62Yb+9wpJQcbf9rFQf5734Of+YKKFibJrj9UAhNoAGv1ubqjEOo3l5x9dH7Az0ZcT5C7BkpLMHGU9DrZi5lON6z3LwxHjczyRNVhSYldJSjneyI79hfUtEkiRwGelZ3eiHr2bqal1ninM3K+SgI1EicO/3mijSRcHpJYOEmHVRRplw=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
