---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgAkfVBMH7M3yu/0oEbODu+BpQ9ed8/398LzvCl8CpG1wCWRKQPdPA4BosCf7lvCjcbmGqIHW+J9Yn4gPNM2XRptWY1wUnxrd70qtjk0LbRHk809HG20tvWPx9nAKtP9ZMfMOgy85W3BSSjTKi1T6MtlhUqDc+/rgmwRl8Cb3o4VjKNtAwTbsE47SfEZPm7cxJ95Hl+NE5LKSyCXHe3GKhDI8kJ6ZQTxaiIcfevWxytj+5lmXx7cG87gVdTV5t0IDNmsf4cWqqGERNgSKx3I0myUiuYNiHbaE0B1wsmncx57TJPDZUhgTPa+y6MHQZCt/pSBDexrNkrD65PFImMBrC4TX7NQTERcJBzrHc71JZLHyHPg1JWjqwYzIp+gHxle8Dq/xmoqc6a8eHbNxt4HomInhx2is6vaSwRbDIita8KIHikd/0l50tYLgyQgdYTYQXozDFVpn78A6MsHoEEvY3LAUIO8pdGA5Vzw/sy6eKs3mZMWEZGOkuDSooPD+Mi4F/uikvoZZT+ndMuH1m9cnsm4K1KSGmSpMw/CORb5QZYGV+9svtPST+6qr5xZoYATImmBSRO06ftoS6zLrk9kMK58CfFt/psgbdhhrVkPrc5y6UE3DXBj49WR1/6jgMepqBNQiD7k56/EiW6e/1ZnNd7hHbEbQLrm5WUdWUgblDe7IoTpBefBfDbhPl8gKAKzs0CVJ6veVFVvB3M=
    secretkey: AgAAce9ooPGywsGLhTE5LVLvmq0T1VLot/lNcSep6coqCsq29hMmeYe3/88lU3C8qaL/pWFuZ4O7UtH4NBNFb6ZuXNIxO6YygUvQpodxt2F7emu3Qa/Uql/wfnxGL0xPpqy5Tn5CQ8jLPxfPgm+54xt3HwFVFiek1EKdwXDoH3nIxGIiImlAFkY082Pv2kaHmFghxUOUzCkQiy1PvCWoP3IBXseolk8as3RbkOu8CcCVk8LWgech6RTeQggKv0xT1nzSKyiaZ2URKV6FI09hLo+3T4L+irCldoQtYRqmxzDnhhd4RPo6BY2n051gGLa+g9Iq/cckk5ktYNIYT+8OZLxS4cvAT6zdfpUBEbCSf1PmgeHqyInkR8nSREG+PNrdGQeow1hakix/ZmYV9FGUuUqmWZbE73Rj45xBvdSIpv3XS1AXbnslpHoOckZPVr5evf889sM7rREjQ14ykUhDd7haWz05i2vTOTwLJ+v1M/NAou/ghRf02H2R3QjtQjT3ARCn2fPXmWbrIGA6ta1BPn2uWETXI+dyGk+DlGs76UoggrDDCwcqYro+TSOwqPG8dXOiP+BNdFZGhTrQUPcKvK/t0jjaH7PJGGGcmj4HqTd1AyOYqEvqdTyKCQjUNdOyjKTGJqBlhfIPrGu//GLnrNmrV8TlPO1T5zDPWfASe5pCAu+nrmgt+0eTJ0T/RMUTTdIwZf4t4I3h4AM=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
