---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgCWETYgl5HeWaDX4nLUxQrVTw2Pml3UydG6JKZ9ec5Pl5jKrIBKBSMfv2QAJUtZmmEVpgmxmtIHl6avH2CIXk1uSQliZ2OXFiN+ZaT3XJTPigolr1gjdukHgbEnFWq8KwKDdaXJXd4MF6d8JysiqLsS6mjENGTtA+dh/SvZ/9CXEl/1RcniT5AbVNEAStEW3dXAVkPUqr6oK7PgwfhtdCgMgGtP0+KowiSow21rx+qyIXsFaOBQQjmuAJMVsB9pSVgNOBnrD5Xdgr2QIgG8ZWAf/j7iQCFpOWkPwV0rCx+SPIWwPtQVn9AnHJzAtefQui+EvGISaJRwm0icy0CXmvpvY/Ydw2kT9dy3gcUCOQovAfXeRu0re66L5N818rjnatsXIL913Lyjzel5PxRaIsBUrYEU1pnKMuUFg8BODDlys+F9ePnHtk0w6tpxJraa34+IE41Wg6T+bUSxKTZQD4lPtd/jf567K1s+GkoxAlsUwIsv4/cbHdRPbV3vHsc+JM17xS/9CASgsC1s0kDpbdGWJvchcMycqkiz14UuY/IlsX4HxBjINaZhIZIDNyMYQL48+MDB2dnlu2VKQu1Y2QlmJrE1L8cNEAMJvMkp2w+zcvfsDyNaxYOWgQvoYKwZP6/KjGthKOdXDHPCnhn32LI3W122mitDh+RJjhVmgZmPsw8dnAPqAyco5dKz38obCi/rDLCBujbZiSk=
    secretkey: AgBdTYk34Oo9ZymjU5m2crZZDxS82WR8CtZLUCuf6wkMV2v0j4ZdIVCiKRskbS66As+FNUoZJCpmg+SoaFOkggjx2aCfh9AwKKOl1WxSPOUBiq3bMcg5SM6S+p9UyjbLtt5ksynR9FD6QB0dj6tteq6gKRzuEFPGA9rEMIZxmvBcYvdQoETjP5wrVuw2U2MauGhp8hNs6F5FQHF4f2aGn8fN9EMf231FzHiE1yLAu4lKWYBHEB++8eBJYxgQ2FkTC8livNGKRrq2OQC1/FuXIfnCmj3gr53EZ3ikZjSO1FSqAwl4MGQuoi9j3g8N3trueqy6EL9KEYOWFxZO0P2yI2zsYSRZKAoGjDMTnpGcO87WPXaArJ2aRI9tFdRbqAHZb8Xy6z3nI7+vf9s3XbOJwxF2bpu2JMHRs6HqYFr0LN7p9Xlc0d3DpGnmDAtk8SaDm0OCRwluwwIwy7Ck/Su9rM9lV866sA4EMKlCNbhMKfN6tzf6pTxucUQmqo9Ghi1W6RdNqKA6V9gjWEvYBHWrgj2YymTHucwXN0jtdlxYNTCT2+D8jbU3xT/mZ8kHB4OlLWiqzbT4NLMDtM4kvstiNGoQb7sWr4qWmcicqZogUzBaW+lJtHnj7O6ekbXCSIoVbxcpBWjVY0ZLK7EW7EIfrxPv40YsUMsNAuPJ04GDIuCiyWl1dE8kWyMSjoflKIZ1fDFpRno4HKFq0Us=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
