---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgAmiPAGarhfBGD7WCO+GCcn3q6J1O/d+6LZEtFNWoi3z9z5EKYrDb55OY9fyMW3rqjGwIwAXbOol+7EbrGGHxIleGEEalizLZj95fPt98/2Je6YuX6J6a3NOLFYU6xo4x4sjWR6v0+O3YiSdPlzATKo3PadAq4FWBZ/+s37bPisQbdKJNxShEbnNgVp0+3h2as6Cd+Kx+OgcOfugSeyrvCGHsEq1M7VDJtpsdM1oB6JzAqYQAjA/AhIh7Vqfj6d6CF5bRk4kInO/pcU6g7/5CqvhtmFZHAFDEJ6hBw1tonWJcdoKz8jmKw7r5cJzzWsqgUTrIhJLAISxicscA/BEgKrUp1ng9oOXXwQs1qCP2PVbrX6ZzpYXrEMchKHUv82ah1cDXtySM5+ivUE/PJmW9Ko/dfpMDSWpfV90Oja/Qb/6oj4lb9sGnIL/lWFhSQvsGp+COmqq/DGJ933UGncxQzuiuOqs44JFtYYQbsBWgw6jvlikrE5rpu06iqOtLPhItSjpTxsEsGRGtM1lCvJNo8dutvv4Reo66/hBxBs9FDL90UpMcpiRpHeECnfirrY3rIVMa1UTGxBxvbZttKA/621r7XqApobboCngWzluWRrgri/vUcZHU2kjlFACG8FvVQnG7TB5xRzJ0+89xGGy+FAi5LRbfDMZsc0dtrnnNybI3WRQLwtFUn4shzmRFLsJGghkKkoui6RVys=
    secretkey: AgAuziQBR9/0Wf6ExwQNoXamDWGTnkB9XmeB4FcMWz9N8QaBeiuHsJfrYCdmVT/0feLoD43JAAOm9NQHHR+D8gPcdcpjWx0TZhy/AmnBBdTTdsbCVD06qF9dWkk/FqMfr7SRcn3/501lWC1SgItqNqhqWiXAibYYtVvGh77/m+LtZ1NnSx7RaXWP0fvnupII4QPSthdoVPYB/bzTmMxjp8t1fwxiV0PzreNqpW0htICez28c4/tWFfGMrLv/5aWJozwe9eOcWcC3iCbPuRv+MH4NEyAu7koLYcRKeYWT3aQmWuRC361sJjLwfoKxOy95N4JadSSytPk6saipS/oga2lGUpM3v8ZdH+1ar3BBft1SEH7qW61l+TY8aC4Tyn/JPR/XWtL+HIcd0xZVnfTg3NKonZm+TieqoLTj3dVyKLTEvIVHuIehqoXbyzhCmWlmInCri/QNGcVQn+awI86LP2Khgfqc9l2JqU+wYIJiCYGWZVWW/5J16laZQsjEs0ksUu5sQ0UswbkxNhHm0vx64GaBfB7kecczxPR0hWpRMTQvaDFRFucgSJzUpWVi1LqkcocWh17k+vZXO7pNyA5drm2ouhhWGYsr7jZqp4Ji6iEGXFI5033evCsT8EsMvoE0RmsND2rgy+oqbf7/F9v7W5zluEfejqEXZHeXLkFR0cHn6ASuwvJR7UQbP373TAxed/Qw4y5SbeNY5fI=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
