---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgChoVX8w1H+SWCq/ZS+2QTrBoj4eYcafcVe6Tbb7Ngiyk0uCKJMy2aRl8w+IutD7qRjGWVfFmlNGGaxMkMFDYqtPNsT+X/JJDDcKbya4DnQrXg2Bnrq5gp0DawDgHzY4Y9JxLbrW+3AcG9jVttzJI2oFRqBHB4bf/IkzOo3LUnMTlAhqnUUOTWy4x0t5m+ZcUM80RivEfRBJu6e5QjxcJCa0nsQlNEz4aHq/wLzm3UYaSaSrMJL7hPtmrl/WSTgZwyNhDl9zLtFTvXua4fviNnE3VwfkSBMk4pmeSIwdL7THNjWET5PyphKRFQ64/oZSZLbTOfeyJVV4fPVUeSpNsVD3shIlHwY64yHHd4zvDQfNzPVJxQhXEzEaJBmHtxxn8D3UqVHwSppzTFEKqsp/fk6BEsLC/dBr96AxsDMv/9uPY0mpD97n2lWowBcTiChKv/PTZuMlQAQa47IUCq5IupN7qC71DS8bIWlfHB/yrFJZg6xcw0VsPTZWNZaq2G4Fz+pz5za0lpG5NWcSzhypFq3dSZ6EiHmXwvPFyn4mBiNwNZDSM2YtpOIxxSSyPOZyV4u4dW98EQr4B+wOndcOzmaU2cq8uRrlbF3vGvrUNj3/MtmnUKVgC2UByC9A7Djk+2zkfiBCoNjwXzxI9d8/Gjh5lYKE7QqMe/Kt3vyn8T2kOirPvA7IjTaXOy58i6R9PfHKsdM68rZQO8=
    secretkey: AgBGr3qsJiNAh0q2Oy/Kg5LBLlmn1x+bZt3VGNOWNyrcKw4Ul6kq4TAfrMxLRKPjRMinku323Rvy7VUDS+himHdx9eHbUgoWYKxZ/fNqlLnUGvPhKej0xzw9Ph6DsBh9ECKLGlghb/W5AHEqYW9Q/R8fh/6QCXRqyTX6GSIqw/iBcyyBcyAs2FkCMsuGx9rESB6DGMP/mwXN6mrwAgV9NbQ/Y/HNKL+RkZtSUxRtOmRukz4am7QcCiNsgMKylFjc31tUIt1sg53bvK6qND49OEU7luYtGwFn8PW3kIs199OaewbI8PLsta+wk0sm5W9o+ngoiBfsjRZJVRPbEOulvDTk56Um59kIpxnW6Bq93cPHfj1JxyBb9FlGIhDtz5dHeIMEV24miU/035dDOCY6K508jKTLltDC1K0qv9L0Dbqphd8r8VUvkUzGMku0huRveHsu9b6E7ni9t01QPojUgrZXXxaaPSo4T5bN/81DDTVLYv3blhJwZcqjyyI8WWPtiafUU2uOTcTdDjW7fvgSzI1D4C/tU0d7rukcSqfXcXlxICwxO/8HeoNadtV0mhdNNuNoCxwspnvlUnrFzoj6Svc7QVwzdgJpMZlDIOTFyxKULeF+uyfLsNYAbJmSSdE/3MOoZu7kUdqwCyey7h9g7Jus/5luDqKIobPk0a9D7ZdmewSRJL1U/3SO8FrVafqh/4GDIB3bUVKROVk=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
