---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgBD4v8xDO8ch7aTaUfZyw0kTIFOo7zwuVo2UVNxWoTdIU536070WXGlxJYdYA8q/tQOg0wXWnI7qR7C7WCK01//MOjdHbuqLoPeC3bvLSjjT8Sjf5llzZhqtwjPOxDS3WPtEtD6aBwfqFBHtOE1EvPs6dZQLwAgfjOTH/x2l7G6W1xx25E7zpzFQfPmfDSkgmXFHUYUmwXNUGm9LlSfL5u1dF/I6H8e5nkB0bhW0R6v20P8mmmGJMXxi6Iv/I0JFaT54H2EDpuPUHCzc+HNcmtBX65jnEqnK3n+js0jp/J8i1/SHOkKj3Px+KdCxEeC3RogAdP3HZpQaTXu/T+LANqBPUidG9ps9WDe1jP+lQl4gsyyIBz81/a0Zj4wnescCmhuyvcnQtYRHGWM4inXPRl82/UkxHEbuhYqrSJGglCQhnk35+BqhosDcsCydY3BFnTH4Xh1vBqWgLkkDQWpnWJ+M5+2IlIaGxWXp4j/SYGAUhd0IbZeoRdnldYcPJ2ivk4B+1YvOd9X0/wHJVB1Swt8KC3ekrAkSYVeTlqJjIebdJgy1GmA9gzFUWA9vPsvj2Nl8eT+fQTGX539cxQJEiblja+Ux8RqPyT9XIjp9ZDqXDV5CQQlk1qtsgeNVJoJEmT3R+X1CCWvKNjbPtk1W2C/9CM3CYxf67G40nij6+XhUT4/BBqR2FggV21TXAtkimfKzSlUl8w9hYo=
    secretkey: AgBjapPjnUz+0dTspiq/hquTp2C+tfeWPANrRYWrn7612qgqEg7WjyC6ufyx4pTx15GOtT3IGCn1tkgwwJdHS0g3fx5Lbba8y34ikcgsxGAxoI6g1Ksr6AidP1WN5GKV591Z4wqJXCx1QlwPmVSn2KvCiFvZFMgxy+cEurmOkYCFU8/tHjOYZEcBXoRi4KtCwqd7WKCWPLlk/rG8p1ZDeJX9q4wvzKMt+RA6CmOjnEJayhaIi3CVm2Oibexq0q54bLWkK8VmMxTqR6LICW7eaCAVKq6LdUgpgIQAANrXJ3E6f7PrQmKSWjsKnGXnbPS28BQp8ZbzTz1/sC8RbAcPeITKSBe3tbHcoohdWJWhgdNErXkotULSMTsazpfB9DA121718TyheIFD0t405TerLfiDBvejJBIlRJ2SjDpGKDYJVQXqLTOQPeZKYTbstd+CIw2fOmEe8jZcbz234Wwgd8wW4EcT2cT/W8C27keZVkHxTO0GuV00F/cqJA0+IbRll3Lv+W/XasVI4jVnw8h1k2uSl99lUKnCSO7gP+pT+pKkJCL9ulu2Z7MGmmuZ7Zk/4mYH5KSITfXvtk7NOzM+E/asYisskXB+UtxehIUMurPotSR6Qv5JugUN+rPu78E0iXuUMEGwSTfyEV0XR93REhCzoQDoQm6MUsP8qPMxk2R152SipJ/8KDFVc0IkhApZln9j9mhavNFUoaY=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
