---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgAOD30+dxv5IwECdF8x81YXF74gAQupXdoF3gmWobiuSnQL685mkASaKRNhM6TuYyI9R9ZnQE7bXfimUV+/c2+KjbS98c2rZSouRDh419JL2b9w3Lj3OkVTnvXDoxIL/6eeq7E/VEZY0qS3gsv0MrrDAgKm4s3LJbtA248fhayRI/yODFj6dMSB8rEfL0xsdnR2ZdyZ6TjsJKbTnjIfAWVYgIG4N0fx1mWzmoJVtqM3dZKlShlZ1NTXPrdEt6kR8iVjR6Zp3cXNBPIOIVVzIdGSZN7S0qp0w7J83w7Wr2Yyzw650bz3Xqjua8aDtxwAm+Xulm6yXGxlm6PrUG/tlbNzlIvaiGuL5H3oCEn+rGaZwuZ5JfkhJpi4duMU0DK+A7SYZ1k1a1nrlqXQzF3PIsnIB2tnLnLR5BSotQ/Q4thgAhRTtO2IoTrMpLxr0KzbLHvCznQClU2BcD2Gkxx+cghpXMch0RP6OuTG2V1/6hHUfDZTl4jsIf7htC1aOEM15LltGDS8ZYBI+fg7rH3rL0TgBDQm5+wIZrLX36//txosijV5CkJPlBlpJtYvsNgCMWtnAb+zJt1cmjLk8ViO0pj22ksGGsInjwlVndqZaDRNsE34FNpAqQVmu9TVFerH/odT5OWFgP6ImdzZXE+Xu5x8/2YAwS/mRvSNnRjYCM/LBImkJRsF1aiIda0mSq42LUUshBOzs62zmo8=
    secretkey: AgAd/QhxSf+pMSjuu34RlG3pAM9Uo5qZGuBN8sEY+/2hdZ4Qtf0ZE0srYanthPLzfQ/vl5PLn85dHKbca9YZuLBmGrKKUU7U4R26KmCp/bx76dFeY2yFVfTmSv+0KSl72jvs1E4+vE1d4MaRYVpzoxuC0yg+Bktzma7U2tZr6uufSP/WLL+/JOfevLizwhoQeMqPPvgCdo0r7YpXOUNLKgC1PdHpf5TuokpbywJ5e65P88V4D6KFP1MutNZHW+EJHqzgyxXVAZpvYpPyoUPpicMdlBdnWZ2zee8kEpYUxIDV9pdgN4Nm+fRzdU1ace8YNxUI0dL8OjN0fHiP2X4wlGvqhZp/0T+4iZUG1Q67n59l2/6Vxk20ePoAjTCpx9bVtU4R1T6+A7v8KkCGGcMuTsSsAHvr84IVcGkidLEzHnxECyY1gzW+D1nU+vrAfg486QgPbvyNZPlrAZM+AuHNZodHm/U/KSJn4+KXn55M3NAFQPlaK7rppPRnvBl0bzkBsiDUVVLqYKE5FZY3lEK+7kHxhxMDVT76jdNehGILXqomHpCiTscnTBbOAhE7MC48M++8EenoroMk6TxZQxWHZrU4CTmJvTGlegfg82tKEfpnS57DwsvHSV8V/koZ7/lqEQIqEahMkcVCBxs1lP2mA9eAGbYZEco/gYD7h2XiwRy6g4CnCw3+P4H18o968cL1nUA2F7N60GbcQIo=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
