---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgDJMM95k1Y2vve62wT7uWsT+vX3IiNwlU/wjBSd0gwsdOEmqq9PoM9OMVGJSMxHiVzzIG1KAEAXjBzm7rhsD2eRtGGGnEds0YpAq8n+ySNal0aVVOvWn2IbowT/ZJTem2xxoczwjy3FfJGtsPN/wxsdy2RgkYCWVY4Lcq3Vx36DlLLdPO2CZPEV9rcBnrmpcr7AAF5jcpAa7zRmRbtfxWt3Ock+yxtoYgaxp+AnxSzGudGDG3r3V8whVQizAbtrStNtMqYZAkVf1YjsWhc8rkfHgUrODKOEa4NtGND0VLK7drLPYriJD/FUqSU0X5huK8+aKp5fD27PJpH9fEVtrLsuVIeAMO5PtnGyVXVTYk1SA00yCMzck7dxpcjcs0mMDzBRtcZXSB2QPKyxrIxwPw43eZEk6eEnSwLwWuNOcfj1heZis444/WI/LGi1jEWDsGk4vDkIO+Js35AeHLkEgkS4It370ChpHS93hbg7oyBdBv0AA5VFqAJimATUL8eTHx1IAzTCg4KodklMSauglaeS7gFbbGWtV+sGMSxl4XcnGpueEn1HTcwB2QZvXvlCSfG+XVB498yZbskBi0SYI9cmyT3jFJGhnqY84m5bLKnvVFUsV9FeuWaL8/zZ9TjWmVGWy70XztXdhtA0OZmpNKpbDTs94Bxi5I5h6nA/IFzOF+ngXQ/0VAWLAcgBZBKBhq8502F0ZUS2oyg=
    secretkey: AgCa9BSRslVGZqhxM+KzQq8vJHhIXzjRXM+cPaJS+l+Oabbdq909o5ktIuYn+FhucWhGyHfS5uZ5OUXTTIqbMVBjNgKYgkXIoLV9wNAl1p6hZX+WQ06SjrnO+77ucFiHYKFiKQfyXyXoIbcDlbo+S9QBmSmiSvdhs3YH6RYAxo4uRJORzP81gEePRaBcbRmlUvF9iluvuzMGMqQp+G+uMSD7Bh6JKJsdkENWz2s3uwJJ+zVmDilWHaWa1auIPj1JRegVp0Djcvx0y9jEJTgL1IJqAf0BClFxdA3usL1a8FjXCnitf8eXFEMJlCbTO22RJtyJUu9zYtyDhAD7cEowoglQLoid40vVVVENgVkPsDohfMJzPrl8Uk+rjWUQ1XbeM0eKdSmBZsnVicLqH6FTsNDjv+xfqArR2p5TRQICHJXTISKQIOAA+1zkV6gzxjflHu13d/BU4J2yRVaWkK9/75xoYK/kmCtYzPjERHkS5j/eXK20r63xmjp8A3b1kyVDSwjZC97vQb4h7fXY4tsESCeXL9ZDtmYng4Ouj76ToPlR7KfSz3n8iA1GzK60fF+H5JNoyLTYfOz5tJzzTrOqDjnfnfvN6/ETEZKIouBQDNgWmcHCU8IjeygurHjHth0QT7+mJCYApEbwtOcwWh1G7sH5WAJ94vJBjACl45pOhqf7CET0FHJng/3O7VEXa7Os/EUmpR/Sx2V8Wc4=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
