---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: loki
spec:
  encryptedData:
    accesskey: AgBaIZ1KkjW2xDACoe4Cv8OwAgnZsIp5GxVusMWvU9ETEIwfqLPzruJsNh/j0HG/2Dqy/g+TfzXuPiXRgxvx3MkCcKkcksGen6ZJA4qzMt59/6tlDDAnRLXVr5UyHBsS9Kz0alKtIx+P1mPdAq97ND5sKCLQxcGWAF0YShIB3xurNjbUldrmxY/n3l9EAeCt5v8KKnBYcj3mxp6fy5MBr//ir2p3Dq4ayHv4c1yDNict3vCIi5ll/8Zlk1iaXzxRlA/ieGft3dZcul3Okapp3lYkiV3OpbKwUYtPckzdv+tOKD4aYJjHXzth9iY6EaLLqZHAoN8pHytjRpJhwn2+RuuSesc42hAMvk3xwHg/MLgO2oTW1PIRbYOMDd/lIZZkmomP0Hf3dHXfKHZyO6sAsCnAkivy6qvMTNB/hXiO66H7TTa0vQyt9qUkDdw+DPXUUQqchLia65xFuF/6+lFdVFVtWB+MzTg8qcEbSySQFpli/TjEewAAlXhj7L8UxARhbVVOVwVqbBnwPQHsLNP6d2RI0GWlo3sXu1AwIqZB2KLcbpyP31jkfTNljblf0OzifMHiuTR9M/Dxcn26089tAWl31hvGWLqf4gNwLYv+N0vrw+iSqpuEiS28BZ5UDGKdoBRbnVb/O/YMuAfpBsFUWTJfpAGbdjjXKpulmJ8/Rcnlftz4M5olSttS+bG3VIXemGm9mIp7NqwU0iE=
    secretkey: AgCPtFnboGc/r/kh+paOq/cLyifR4JX94OXmu9r6eH2ksmoAhfli6KwQpCYRVV4n1hR93mNy74f5wZPe1hKj8L1r64pbaAUh4AUQhH5mhHzaDgDZIm3ugnIsoWG4Yu7n8y3paMgfayqIcGnZ/kvlQgG6Cri9Q+5K6jF7xPx9/nIFCtOIkMv40nNYF9yuppB4nuTb2VK8bFxmiyMISZ7Ay3X5W68FCXsCts6t/AfwFoX993Tg43Mw6oZTeSuObHUs+Oj5zEaJpo17ejFpifqwpTYoOkhOYxplw322k9aM5HDbGYvsdwSxkJHrwLLCx4D0W6SH0PHfGJLxWjcOeJz6t3yIlrZcxi70yNjnYciYdQo0z4QJjVqoij17otj0d5WxzNklhyzIqFibvOTmhaE5N68KpkL22doV7xdonXcVdD2tV+fLAMWH9mEMElWXIaIqWfFq2OzqVZvReykFbc1v5jPV1H8qSqv/wI9lDydFuC93yOpWliHSK1GmH1B5/u6ZX+oHrWRUj1lLCWaRyNLrRXVmgHdDCv6Vl+VQl11h0pEhoKrKM1PsOe5CRa/Rp5SR45gecPhquSEoNr5/h6jVAAqRUK10moT0X+y6zRvfXDiIJZiuq4kLFyhJVYgWGzpoWT+0/FVYT1N6goBF7W8FCW26SqRC8CxqYd0WjKFB+k2N24O5iae+xn18DsBMiCJ/72Si0kboo9xP8Zo=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: loki
