---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dt
  namespace: argo-events
spec:
  encryptedData:
    secret: AgCINw1osBqI0hk7BOhFXabFPS8ilLQYJSeRr41uvKi+mdXXCdLDAIwu4Hf0kDpuFVQCpovE9rE5+S5BD0cEpzSuAVc2yTKXc/kTOzuxg0E6HNWfhw+fLoh7m/7nqr6HE7atCJS/EHj0MCQwHS/4jC2sX0Mwpgd/K4/r8ETDv4ouWxxukm7bDwponI57GJkYAyHYWEJ1JxlpTu3usaOf8F2DZjcLxRpr/ER7/D5LADpkTvudX2J/QHKVydbCs4NQdkCN3TolNtdPdVhC9kqUIQfeVfkfoUk6RWQeHqZUDuysk/MJuiIc634PD5V1Hpg1nXXjjeajj282+B1fhuJ37WoNSFZD+GvwOHJxo6lpwKoNCpcudLxqSw3Y2W97I28io7+ZlDKy5e4t1rR/+Tr5mHfAJpVrBkk43p9bRzuz554ZxXZuEEDohmjdXyF2xRA279jHi4C6PhL3c+DIzfUGe3McAEh9PUbbbSo0gq2Inf6i7RutYfr3o///PUrDfenLEu0v7D/BXYSbqTsVEVv502CTTZ0e7dOvfwPxuvB/NJpW39KnlgHjcO7pDr+aQc69xuM3/272SqkvXdn5ZNDMnUHdOajg6Bw8MDCSxJpIcFxQupbkv/isRNG4QeGm6Np0nxuXXoOnvuC59aDMIGbGgdnlWMMPbvGlt6w2cE/BtsVoEjmVrE638gaBCSJE7WezYl4=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dt
      namespace: argo-events
