---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-token-dt
  namespace: argo-events
spec:
  encryptedData:
    token: AgBDb3vEu+VNc8FGFVL3ij1YM2ki2Br5qXp2dJlOZMXYmt8V0eKphOdMT1lEvuuuqgLADiEUqjUHa0oYDpEs/8xsFkQ80R5lWWsBHyi4TbPE6YaWw8YZoMwVQlkuLsBoo+ERRXf1fMPZ3UjvVWYHEDP7LUWAfLL4L4m/QC78n3L/YJfJ2FvRyEeoync8wpDxDzMGQysOWI3EPDwnJuQ3VCq2my2q4QSG8vHNg26F72ggYEapg3e51CYGC3tM272ICpdexU5X3G2VcuCJgx0WEmrv2niyRTfYmVeLJ5CuTbfxYUOamxqKa5+AgYyrCUDtg4B0bmH/apF9BVrRhUG+K76eifU72qdq3HthltmZNRj6VGotlf2+aqMwOtX4kBJPJaqftqk3y1Vrm07cid/Yqcd4lEzvNdk+NPbkMJiodc/CBGrGCxEQrfJ9lq6SYwNmziRzrJYjvOi+uvr+Thf9z5FTW15+4hoYw1j8wU0zrbYwZviRh5NVEwvlWG8ychJbcO8z2l6JByww03GNKsDdhBE1PdsRvLpgBJB/W7QgHP0dPLzi3ETmNsdwFkx7HNwpjwgxWStVLd28LdK55zVRLiUV8euMjZSPxOmHU2GD+ve0Z//PNWhgJKyM6En2HiCypqvssJhVc9CHTAn9Wt1eJ9RFZc/SJrm+mFSTwcEYUYR5fhl/SNkhry8XcPU0ehGzDro=
  template:
    metadata:
      creationTimestamp: null
      name: gh-token-dt
      namespace: argo-events
