---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-token-dt
  namespace: argo-events
spec:
  encryptedData:
    token: AgCJHmJV52zzEMy+aKXadJI9tKTwspAk/gpC5j1tGzE461dB5x+rbp3vcYV2csMaClVwpxGNKcWYezEkELlvvbic8U9uWrRKzc7xgFf3LClqNrm8essJq8U9YEwMI83mM6YG9qBtruMApQoOqSapyV2vE2x31Q1O1eQF6U3gcU6Oj1W4NIAxkSbEZzNOU6DZhi88fjqedktsdklqTRaCATYKnfRhP2hEe741gEduJx30U0cM6faQwI9s4CfLvVYaIqvpRjT22WqhKWnhLKGqxfQP715nKOnss8n3Yg33Qjwqznby3GFk3mvMbl/tnXL7/bLjJiagDn5jqx1lH4zk1jCfdVsfQRsUNFEfY+wdGaoyuDu3v1V5pMTDUu+XBniWB3hJDsSXDXedK0YYT8E99eNAzljnZ0SAnCK28dWqYOufOwko6N+FaZdMHuzfi3bBBhhmqUsXAx+7o9AR8NcM2LmjgxHMzzTkpD7MH2/e7qZZZ8bu73CkE1wLxGOevgljSMlSw/dhaUxB0zSoTpmVV2fKVlxFG7l1aJDiL1F8VD4tB8U1YeKc4+z6or6F/SCQf5cvB4W0UeZZNw5IM8FL14iK9L8n+u8fPoT0Er3SSi5tJ3bRgZ4ByXcRuCKnltqxTgwyq7yZl/HZkNFzH/qQrQskvX4tOIkNSENX+XGQli2gIUTHr/CX8Gciw07e5J3d/rY=
  template:
    metadata:
      creationTimestamp: null
      name: gh-token-dt
      namespace: argo-events
