---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dt
  namespace: argo-events
spec:
  encryptedData:
    secret: AgBMDhYRpBJvs0T3XjDFvcR7bFuLJ6kQY4QyNJLBQ3dHKZTVvLRSIbZitsqh5XQzKMxgqaljXjit0R5r89gvgJhlMDR5PHBz13FQKzaIYnW5bw3wlzSSkls3xokzUmHiLEuCSfTykHj0Y03oSIydRfEj4e/k2hVn/qVuHRmBUIQVZRBXldtSnkHqOqneTBRzI0oDbu+7zNxS5v/ue9mXKVHlp9hD1cuizQlzBDbivJJ4wjPacWPBBftX6uh6sFVYZj/5JmdsMaHVijxksBpWLdbTInmUYePSmgC/D78A3wMSaQQvhGKwSeAt82DgS6zYH4mEBcXel8kM+72OgXb9OMJoSIlWlh/b/rj/YI/B21fMxt9vcNFXYmWzOlyr2WUSH0q3fi9Ti9gurszByKTchQZFzeisgvDdSAX/fANL0vDGg/H75OGrzk//iIZZWNPrB3yJUGd6R7B4ZToeCq3TFIUzykVoo4uZ5E2cwSBSP7r+U7EE2qCllvSZNupgmmNdswgP2TseiA4lTyEc57vn/n1miMWFtvv0FmV92AIEWaOqVBX6UC9qO+xLMP75XfAqWR/WAzZiX++jwk82ktOkVxpWE6ZfvjkV7NyBGfz0rLlpRdIc/EloLusQP1Y5FU8I/1vPVNKVRUvQ7B4tMakaC/JehlxQDXbmaZ/6G305jhEvSYZiCA/iVSJVqegcU0RTbMU=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dt
      namespace: argo-events
