---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgAphsESPldZOdXP6a6HaLiAaRSCxRP+8/nNN8u1r1sBNWDRPdJ6ix7+3dxr2bBojDpNNp9ALCI90qVlLVCXJPje/08vWehrEHYqkOz/rN9iiVS7Jet1dE43ItTg0bSBHWSRpLuXJv+4cFWTfZ7P79wUp3Sf+6/l9gf7PxzTDlpCxKK1MS5k9c0mvAvFasSHzJSwxqV+SRVtAyYMJuaZPKLUObJGqMjqT1lS7rLi0s+mJ4XKzUJk1fDfaAWBfXtz2pW6g6z5x7SM8xW/8ZcRDFs4TFCcPRYZGmogtt9e7ogkLjNykvr5Vyb2yTz2p1L68MoNK8PGD7BIjG4E3J3bq88FdlbGOC2mtSYjO7DMnI+nqMc/KZ+Nc9ZiDqnO8nW4gmBZ/rGHIvnlSf0Lb6O/FbmvqCqGTbBfFhd26ch2L90zfyojWjJvZ4+2QdJZas5pSa5QtdUCEVw5I50JqWq6LrSpDEdtd2xlCkqJdPWDNYIxjuRoEQcL/NBUFX3icLYDxYtPw7hJDJYHd/8UoAwWs5LD45M9j34RFs6JxHLAaoHAN1pVnJnNXfRconKOSOyMcoZM/nbIIv/KpsDUT37EKKNUCAZZE8qZzZfKCz1JYZh3FEegZ2r/bG28ZKmGs6DcXmydRQonU8EN9s9mKG8QxVmKmUE8oRVPteIYIVgUWGV4Ja9jAD6JenZW0MgR81/uUnQ/OZq/SvlVNiN5
    root-user: AgC+H1/gb04E9Acezvx8YAsphXp9P/KQH1cBguiGj+CYmNRZY029kaMnlzO9qDOGQdVLd4Ib8gA/1sd678pGX7/UljlczWJmqGR56DMa7vdqQRMVGS3WbvXMosj0qnAkCR4SZXAJHtMywv1z4QUv8ugDt8tYb8RX60YAqpz1miJW9AkOuUOBkSbP2oO+HWZinuIWbQ/hAWo1UIwR1NfsaaeqQwQJ4dATQVAVu/TszAWszFdWqMv1p0DVjkK601AVgrNrhLLLERjSqUxfEjdMf2rYlJzTRxWYLR8Fa6LjahNX3tHvve33u3xa33fq1gXqQjud12uRz+am29IJC40gWiwH6LIgLpTXYTMun8SOIxKLRundXj2ztkO+ZLFjiip8t1O/Mr90fbqT1G9fvGwm6toF0DJAtUASOsoYiVKfeET3N0hrORqXfmzIPMEz9BWdntMpADF6egCdTbJvaFVPqlOwfeddgxMEO7oamoDSlLL1Ea54rwqqnwwx45sSLTvbMXFkOMcUl2iCdYkAjrQoyZVMe5sFqk3uoLGsT7bVjGpPyujD2Nbio2W8Hn4aMhh3RLgz35LqVtKCXun9T+53URg5ACHtOmqGKnFI3k0eJXZAs5gm0eoR/2flOnNA10AeX+MUglAOo5VZbHrxvNWWQYXiv0dgi03gpgtGSKXY+abQmFaFvo7yi0wR3mg9qJvRf14DIKHAPrIi6/lQ
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
