---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgAO1f7pZtCAfXOiWz0ynizq10D6WDGwicaob8dtbN7bcwdXd63p+H9l1aBLlaTt+JH7akSHm9kQrWgkH899er3BedhubcVhywJsbnFvB4nVZYP8wEynq3jCHsmHwIEgLlTE9YOA4onoSZB9mXwgRFKoO0WPL0i2xzt7ZaemxeRPNwxyVgigemAKBV66cdOM+yHxwWS7CVNYCPD7sF4k4z/UOFUJM5lQwTM2vSLbsEFS7ycu2x2jaMfVOjvwqFe91cfvZ7ufu3RmOWb8fAfrvU9S4y5aKtIC0F7KL7gBLHkPeH7uOWjKw/qginRXeOw4lZ3L96ACYM1Gkyr2qwZhR/QrM7RMqPsFS3S65YrY00gLzrXy9uJVwXaNKX4Gikhtf25jxZ73xyFCkctH7WQ6LtEYnhgQkFcVAFjwsSUJxCfcJf6vk74hL3SuZfyxGM6ruzUmAiflz84DugMRWyxkFJ9GiPBQZXE1U2XVxmr21qwJ4NXQ1Jf9iHWBVJ7LxJQSuZuAV2h6e8tzcaiDXXiX7mw5YHr8GqnDKX0E3i1F9hs84Y981SUF6L01C5b5XeqOqYK5R1hH9S219Zzbn39wyfmOmowIsaorsCDjx6TzdPoNyw7iUMg43tv1qncIqDHBfGePr1Ke9q4xzHRazO+BMIA/Ts5Mm321OQo5uCog/KK7BUAbqsKhhOVMb+emiXprgNJtZjwfd5RGX6hzCWxflMJeVxuXWiNi4W7LA6UvxDhopVN0WvCNvUDR/hUV6yplXwRvgZWSs7wPKOuJGS4heCzbNnOR6Ph1JAaUn5MXmK7qTphmLv8XID+Ryl39YbsYaGDZ305P09FDeUpHnfiec/oQ7k8H
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
