---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgBXcbgoTepaKLte3wRBh7M4YwSlLsBgp1nr00XDuNH2y8ZIZ7U5TfkUxpLDsxFOpg9Xr2ES4JpRg795WfHPFFG1jqxQbgAO6QaQfqzOLH0TgroJvuyf8blepy2iTxVAZeo3lXzBdawsnvKZv6B+UlNHr9d5vdjt7SfKgICDf/Iou7mYcSpcixKVJjYXqNxCAP53Yn1UmaDUhfyd/nDOFuLTsfDhjjPO0Cpp/oufokWwAQF4EGU9j8vRNk9XAfkcfBtyKt8LH5XGXFeLYfb/qJ+Gj/h1O3gyEjjbMmZiHqJymV906zA70Zwdi0k+tnHh3P/o5nGoiJysvrhC9ytBpEVQY/vwwYp1HY/Dm38ZxL/vQrINyG//DkuKz6SjdCUHVCjqZeOGu7PIafex1RVhjtPapcxpMZe16ITjeCtouiFnXR7cRi8IFkC6QHcmRZxUbt3LWsLIRmmk7b+iGzlqkv9zA55YqzEm5YyRUymuZdrtg6UnYEa07PEETzJ1Gb2KbDfy8LqYuR9t8JxZ29rMDeCNq+KT55pyBW0bIZk3z2ehaicsgIkCNJ0ULgs9HXQtp5gU0o8thmsAz0F8Hi0hDY0/PN6+ar09tWDoNVacnPZ537sdtORvmoxieTAF0vtAUHhTHIT8S0udzEAo/kZkpJL4p7EIuNatP7syokMBe/P5QKMyqIfI0Gy4SaOmhVX72gHYjG02YJBMwOL/
    root-user: AgBt3scvoUPOkRBHog0GDmcRMyYh5F2TXPYAce3e9HtxHVfjGDlUyUrIX10DUMunJ2f6AK2NLC/2/BWjD+KPrkGb90DpefTZvwGeoiI4MCNu6GqJFbyzvscXhbu79Ayx2Zez/fGd3JlNQgkcsm6PtZxvdlrgAhFXKlDdGN+TIHOFvePyR9gqwpgvan7HVR+/XtuGpPhm3OMdNVTHKOOCa0K9E6A2lS7OMEDKGkCpQehuhqAJ6/3q1/EJ8RpRoYo3EdLAQXNPiKxd3oN+GhcSIU2fpMejOta7KjUv42DdVYobJVDdyvXcLOmlzi9AzsLLL3Ca5AOKTfUX2A7PDzhs0r0xiLG0icIH40qIbngxz3m8zAt+W5hUsxT111UHCh9bxsTSEUXkqfiYQcGDzV/i/irWL2xApDVJyqCR30x0O5l6/W+47pPytxS8S6GNA+dy3nAag/ughC3siX+6dwz6+X58W5uEEGuGmQEd4qfnSi58q3+KS7tfCRrrIrCAPR7pG3WK2mS1xDNanoRpnPzbe2kZslj9Ob6zifpCk33DuKyWoP7xIZAz3i/kXczkpRxxixJGdrBqHwyFkAf9xxCtoQsdkVQe+1pt4WxPGORa3cMXSliIKVyyRh5O8VFfqR50c8lgbFBMUd8l1JLUVvdmkjcUuQxhe4okomffaSf6Xb7Wu+f3mLX2jrws0WL0te6Xd8tKxhUowwnD+fWT
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
