---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgCtuCkSf9rh8nx8FF2t6mGd0//DqVx+Gp5OZeQn4UNA+A3fY3ktGy4LdmXtbCttyy14gE78bQg9Pv5KjDOlHZteeJZq4m9BbRTnFWWSE2EIL2JiWSb3um0q4tj/e/zvJdVDJWm7qTJlHxzJgHS/KpROowKR3JjJtsX3jRGulx9/IAwUlzC/Vb2ZN3BUKP7JghvUT9k5UqD737hG6WFz0+epy8vBGmidGrKMxDYbT4cqnEhb1yf3vn9SkKYxW04hTEGxsZjHCeSYJTQGtiuukWgiRzfMzObYEPCfDggxUq3FPfTs1lrvn7kLpdzbrFhiCkn0+Ad9Z0EGMKz6wy74YOaIC5HvG0GvYJQu9G1XAT2VJXRqd9NJNJUqSIK4ICmMpAcWjRiyKEYl7D36w8t8al1fKBsYas7WhM10+QLwFvw3TeLrDZYVP/CsyWVB3wNB84AvQVjRTMFP2eNAvShpIsYPd6mrPtDwQDqTcGza+4C/UNZenFBg7vX4bBzmPOLGEzVXSsdHSFTshwbKXl1DI3xPJ3N+0hgvW4dYbmQPl5JwpV3VOwT2W/X+7Uq16aPvgb9kLjFpxQjsnwmBqVCECW7QnDrn4fv1afhPS876eDEXINiTIgdyJXu7K9o+E9POOVA8SnxVFtXbeTl8FFHvC8Pg3259f4yN2ZzV0ivRbPwu+AE6LBRfM4HjlH7ScvUgJfyQVwguKLyE30DS
    root-user: AgCWRAxjxz4QZ4aqpQWrdz12LeZI1xuTgEYpTgrqOu/kiD9eu/g5x1ej+ru8ODhxkZu7A3SMxg1npXZ3KRqWJQqKIzFsGLBb7q72CNVw8muLPx0yeP6pyPfzIi0Zfl6sBOdiRj1VT18lMuHzM4V4luEEzTSnxh84Ubaz6zWWyrZwjti3WytpNmUr9VjRkStxbX3kDbV0iJme7Efl1kAWSZrbLAIlNu9QCV1LKr5u1wskrAQssSYcvztp5dyN36kZR2/PjA4cNGifprrrQHJE0sOkxKCNRJcAHUpZ7GrfaA4yRthPiQc65JmrKyym7IRtGPqDLeM0rXaOr+0N/WjEaj/JKj+uuHTXEwRcSQk9a05kI0O8+aQ3blFtVjBkOZuj2CLkL4DnKwuOeLkO9gK4Haejkr6fdQfQwz6ZBLHWjmTjsMvU5LawmAxodgApFSPZ57VvdXRlyshVLViw2rWtW7wtg5Zyr9Uc3MMVIpgPS+7TUDZBHuZgA2TF3JC+qpk7uNSSOUeyP9q5690gRxSDJhIscvd5zv01IxuvN0JRDu41k3FNFfox5ZarxRs+bUQothbBd6HwbjKx77TnxsGKYFwW9fTdnUjp8FXt8oi9SrWEzpevhTrqR7BI+1ThgtPFFu3gO3+GMhkZpnY0fFylwOi6hQ8FgexxLwTe9N1PZHbu5nXGbntqmC1VdBJ6mEvBaSQ7CKjVBbtpPIGk
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
