---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgCzp6ne0osV12qkYLSqSDbtilGtZN8smONA8KfasDKoBBne77QV8zdlK5nwsoDsJuQ9pFR9j6tB4tXEKy9ZTMXvhCDpuHKGKd92HoIII6xjYcpjDnAeFLg9ZA3d9RsNz4jnVoeszRKWdbQJGIPBogS/xoRhGxLoPVCLEQNZQIEIIJObxMlVd/EnvLA8JJEm6ZIJP8WwIGzchIt2NMgHcO8TrEzIc2wd8viPtIuD42sGMvLVwZFtbqFpEikFjfLPqJfKcmhPVDqhCOEWm6neQRctIy68O2PgQ96W3X/x3wC9HwIM6uvFf0EkOuR700mdTtFPa7WkuVsA2drF0YuFMg6s/jjsoTZeLNElCjMONh7uIjGnZzvivR4SvUl3bh9noPULpNbxWnFpFWS2zEnqWLik0bFJ+hyWmrJAjkwIMctDJFqlYwc3YHjrBHk+PJ/FBngjvkVe+BBjxr/ADG2PfwgFm2QC5NKy8fUcTnyhiXdJvUWeYOalBj9b07ZGZnwG6WUHCJdv8NC8yS9bqUTjbOsddG/+wxQzs8fT2M4ODitpB69wS3z8uHBFutZPP2FJC+KvmVqz1Ho7qMQTOjt0JAbCJwVW+drm3kb7jCWjnLl2CnbOwabqot31MlZUxLpcmMyC3tmVP6j3ZQ5Bm4IlQ5DuRN4AKB2igcK/vYVY11y1RRRmftSRJTxlj654/BTQkBWKi6mDEbbvCROq
    root-user: AgAenhgj/hApdB5L6VgjIkSJTVZIWY1TmLG7FssRyZpek+iltYuBPcKylFUJQiEmtAimqxFHGDWEc3aN4Wg9jHH5ec6E2SMAPMOzZ6/nTMweHPFkbByu2s4iXsAmBhmj21ekyzklzo9UbX12ExejMK1Wa1Pa5B1qe0neXnkgC3AeA7XbagdSyJiY8aGkTZus/FcVVYRoW9oGGzBAho8Z+fcxd+Exmuy9KVJHw7Xhc30jCiiS2uCE9Y0b5vobMDke+UzeJNG1OYdkgTXxEbjtQWwMYBNRkONEJ9IlRMY0O3as/CfiylRJAucHBlXvEYbH08sn+Mise7xK4Fgpt8WGQ7sp8ai36FVba55gQ9ZLqRlSn4F2ZElgZ87T9oCPHAYG78bny2aL50pN02nBJKUm4XwfS+80mAGbiRHkOzo2yrwnth3jSUD/f/twJlEbuozGpAckdI4X8qtmVMnjnEu/vxBmOEdbLJ22TvJL+KGvLx/aJ47ivAeYGP1gCjcSiFDFIUgTobL6yq0AfEpjv9fo/vkOzU+kprPH1ZVVIXKHfzUjLFowrxQXMt/+OkBpcfGDfcTs1JkhhXyMtAWSDAShQJp/jVkO2QXZ7PDTLnYiXUk29mtIe4ssRhLApBB0kS3tCvmR1aDPGt8HPXCWVB1WlAJMn4uNCO1czYDq1J8ldIKL/qOvumkNa+K9txB14RtKA/gVTOaeSsqIHT9U
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
