---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgAhFR+SjkVB6O85oHxvhmeWe95xHKvctGM6jJsG8ClXwoVtADmdNegPku0UKdZWmE3/eg+FjBFiaDc0tkDdNOuoIjIoOp68rH1ztSyBIF84k/02WMwTto90rLamwrtuqPFK/GPkhcD4/aOLZaSQGBN/WiYgVynOCASDEJX20vA2AgBoX6BVHQ5E+/MB3PvTLv8D7MUr9YAN/pnU1+I05Rxdu8APqa/LdwiCOUvKg1eTD9rE6j31MzuKFwUfJKQLvYP609/c7QPDxKg9sJjU4NkTZnjEN4UnWwim7KCORMkMwCbuKV692FmudxKlQSuOu/Rmike9dsvtC9DFJi4ZG9nshrl6VGdrneIHytqBYRgyHXhAanICSZ1+QIOdDArPLNfX0JwbeW7zGyGi2b26DbqdTRlZ4HAMMKb9XBDU7Sgei5X+a2YSdmc+0+Gtc9ktfaL4QeiH5UtAnRpjWD01kWgQ4ioVbFFq7Ha9OWAKNRzg9BDjAPS95/zG2SBfFel2qUCJBW6ViElyX9ISwFVZ7Y3NKrHks0jicDIaOLDvywlGAEUeYJ4s5JQO05Jf2gnHSLAT6zNLUPpMZRiIaJktMtKUPHLa5Cwqgu8Hqx+SonlK7PqqzFxoncgwmz8fb7ue1j9RPJ6McIJ2ISzrQnNCpIryUM//VvDpJy9lq5x9eiRTLuRPm+2skQdt8mUQ9WOaVueH5vwDf9cWEPMCNMAWjqMiemUmKJs+fCFJIXkdoAFZvt+D2rtRHb+TrrVc9JRLOVGeJkDiXK9LRNmvLlBCRGqmzTKUQ4eRbtUx/pid5jvaICqcHzWroyPYNCjWLIzQnxhUlZ9F8NylVyEd9uyG8hW/WNUX
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
