---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgCzexVrqnwrcsBNjj+5gt7WJzzr66+2BOA617jBnQfQEYj+XDSovDUXzeLX5UptEnfZV6H05toYb4nknNGoJZmd8uMQVdgFhhXi7gPChP3pGYaV9Cys53LJQZDZTyMka6a+jLuIQS+IltKwUZ6IZE4206+Wzc5oqh3fTLlKhkZyICLliSQh4P34pKr8Bo+B0laMiUUAcRC0x1YzcIqzDh1TZSnfnzB6l4T51Mnz3ruj04PglQZ7y2tHv66RK9oNuwZEY5S2hU8IHcMT8eY1VvEcvh8tw1OyAGRS4jgeY/TspOe9e8XZxOTtHc2hY4QxbQRtRgaiB7UJrknBEnJv9mlSQEnnS+JzEb+EcBFrlM8CD5mOf5t5pBOSBr2Z5XD5PysrYkk6vIPBkbVhAKPh0Y6KRvYWUbYpcSKZdDnB75y0+BHFw2DSzjK3boYFjZA5K/DhjEFrDAiprF8R0GLXKar9/YGMWe7Xc7wv0ynZ4AreISACrIyZomN9sCYBiC6fvllDpgkQjoY0NCyboziZQ+4/K8tuiIct0iRKj+774KME1lk9K+kRVayfH7Lvi1VD4STpoKZZjTaehxIcVVOBitMG+nR02eDNXrrP4JrDDayT+aBjuc8ieoT1/vvV1pRRb/kW3ro/kp7M983UMrMzmGdGW5FwYYbZG7eHAGtnlFIxX8qB5LSHsSbsVihP9Ik10IZ7Ep+h7Uze0cYl
    root-user: AgBx1cpxo5E5pH6/jBK1qm5qa9cWyI/92on+EcenhCwDfCkXLpEUTQ5g+JZ7su7+XN29KBpaWYuR6xZPWV/Yz9f7BkNFtrq5jX/VzEjJk88NqGxmsSykZT0l8lwr0EcVchXylck4cyZmsd7w0jTyJx1nG9fa/KfFd1Fmg9PI2ajVkI63o9Rxi7orS+GZAZs7eZgoa74AbpUvyD44SxF+v3DMNm3fhz3QrZa/0qNBzbPjXe56NQsT/QT5+SaEIATDZZR76wo/NgDaAJ0vbYU7AuryjBLeu0ds8apt2XXpR3sMNMX3R0yfASHQQCpAVvVXY8wuoGS8KDERDOl4sGCefo2r0doLhAlxCUfK5YAi/9/wDOn5CafUv92VQRWOWPWF4GWTXuNF6Fy6eit2bGYX2nhtKpRSm1dXr+4k4JI+TGghSKA7pebvkLXIdRM4zDSritsC7L2iUwtkDMP3PTFbXGKsqSMjOsZiTu6TvwsuduKeM3cjv8z7zIQIFrHrc345iMJrhmYA/E6iuk1Leuf0ZXCjMIWgmXjdMbXSKXjJGuM7VN8waPjf9uWmzGBbPjtLNvdTmJR6bLVnhD27HcNa3sxiHtxBr9zJ0ZPx9/i5/292Pn81WhmDAgtPC4c61hi/6FEjXGwjH5eUuT0Ce8/aQYrXljdN3rJ0IWChB7rjntDXoSOcSx8U7Bg71hn/Hig7JCTvAlG3eGINDkKe
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
