---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgB5yFvnXoUV6EFSjLafeCgsNZCtxfhvLJLL/EDcbx/NtDIg3u+qIqpGp1/Q39P5OLEvJSjEwZZ8aivN1Z3mPPPjbU9lGkEqTtzHmBvMB6cHW2+HFiczVN+8rBxRX+Ofx0Qbm65nvfeP2GQ1CYET+LprnNyDEE8L/RUNlynCcf3FAy6meMtshR6WOnBOEXMpJsVN5LhhxmFQ4GFkR94fR5qjG7t5fuf6H1bDL5PUtYfW5XG2EXBOGY98KcCJ+XtIfS3SSZsrJuNW4AzrekZ0KJu0GFiM8aRwOESCvuf8v5VwlvwVhPHYM9Jl6nN45wNRR/M0pMOAh9sSeAoRn4QEeDLCJr5Mv47DXkqLi2N8/PBN7+s1MgW3uwvAjzR0Ts14KftdHJSMW5KC+dukEqz9eQ9Z/jzN+rsBisg6FECKRi8TZ16rSSTR3VUbOmi+TGk3vQzVlnwE6lSk5HocoxmUBl938CEuZvuyXTt/dZwniJOGGqNoAj975vVyb2ZwuRHI2L+B8sz9yAO73rgqFU//hKydT9HOxxp60b7W/pZrtqtpM16p2/KCtfDJGwTzOoDbDaN9v8z+Oj2+/SqcTf4VRt3NT6fSHy0/YxoS7tfTSZFC4LVHrTrMqezx7bQyBUZMKZijaXatOqPpKD5Q4w9vCCQqthRnl7zFmDhzBnQeK+Q43JzSo23s/qzBUnH5V0YVUA1tn2pi+UauD5r1GOst1fI8+ZRlmv+crj8Ygt17SQBFBlpS6iwH7Epew29WazuuVMuk8S8kol0k6JpJFKXDnGj8vgNVkpN37Hl2Ui/tYiXDxzKancrhdQFC5cIvk5aVoe/eGXo6f9ui35Uu6AvFE3auhgmS
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
