---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgCu2PVt9aR9KA9KVnCgdUbHOeVTu2o9f4+m5XGoVPJkNAYC7uBOWCE3NuuVZsznfvrXN8LLA5PIBQlv8w1HVbrSYpKunREO+iiV+g3SDmlz/acaQXcn30kGJ5lV29z8ieljqW64MOAzqeTBqe+DaAqL/GDIe+Todtup51c15jxWqNmfrNRa9PUHSgo9pjMIsB8KuXTJj3vEHDIvwbNFilKSqr+mRkmN898Gs7dn5Ipb6xsF8B6+QEbg3zA7AKtkA0APrDlWT6c7NwtZELduZHL47qeh7OsbMkwyIEoQGYD06jHnQ104FlXntkis3hXZajWhpGRcKGsmMQTN5mQvPwzQbxCk/fhE9oEAq8NzNvaUJVTDmzqDM3SzJRaF4K40VmfaxJbbDaIMPacN9jB8P/7x1GZiB8uGtAbdK/SQ1+23UfO5WifbcMzPzQnK2n/XvxTamayYj3rbLXoUG0T5wQVkmcCq3vrvitlocMDKXsTK1OzaUJHMc0LfI79F7SGWAclq/zjzNimZ7Hdz32Ql9WiGiBxE0ly+ImnzQf/x2Owj6jj0YJ9b19byUI3K9g3qXZk8d1xQF3WCG8r/kKeO0b0l3J0tkHw+xYeilk8lWyKQMOzs/XvbtvirXnEKivD4eM3zEo59QogWqx0B8CJk0QuiZ3PEMvQEsBw5mKpxvNJBmFQThf1LOiV6l6os9bW6pmCdEmF6F4mxp+t5
    root-user: AgAhSxp1q6CgWM35yAXeobLNREtJJAt7NmfqZkoA5JZE+6bkTuT9HzY9F/Mu6M36FRYvJUDv6UtOzOjxEOdvnYDKFso/T+UvxCR8Cts8S09gVHPxYofbfMQp5EnIa0y/3UYkv+bzAvNYDdJJZlkiZA4plPTMHZG0Pzv+IPwNH3wAafvu3m0A8eGPxtz3S0EvKQLr+VJrwI+o7LazWF0FqBE7A7L62QAAQKjMZb9GdsI0fKtBDQeCzv5FJm+iJYlM9PHeHjzAHPlnX6L0IeWwEvZuvmj0UKUzhXJsNNWXGdTG8w1SOMKU3AohLj/vzwcsWybwt+mYgb5KneTRNAst8gTBcvNor+sVJme4PovamDeRX4vhH76uSqscTQroVRfKgrd/GYJWvXqbxcIJNsShrvjACTNRAiOAI59tF5drus6iBBDqWKWzCgUMjbNRigdap5hOs/gjqbTrowXsXi7BC5xOUyp0mrKVmHQPpcZysd35+h1T8ePtIdMuO+g8nXPr/Lh5Eouk91va/SL8QvxaCExYZXLi8eZVxyAhiRSlrx32j4tqVNGUqcaRz59j9OJUG0r/hfZ9ZNou8+NuNbqx3nqXLM16EAtWDT+yIfIWrqHjwO9SM95ZCi7mB28/ZCfU5/vi1jMB0e/z6MvmC+nwznshipK2aaGeZAsXWirAJLIWNa24kD5IMiWvZ1cwsK98cj5wwZhVLtiKjel9
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
