---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgCkykQtUe3XvyRKNMC1mkuIEd13DpJ1TwRV7ngd5Apc9Te3y5rimesP36TX0tpESsYqbloZ154y87ZZByiEkoG+1Zw0MoCtSLUUSV8alXRyMSXMBvBgGlIGT86IbhGDjV5EYBqOq3o3T7OVAPvVCLV+ZXqkb5t6FFruK9yM+5rppDymYOuLUFVlljKAbByEF7KB7/BgpixSNT/Q5q8K2Bnz/yCbEHCGkuVzf7Wj7pQXKoiZgtkOzdQ/RnyCwQZWEJ93J+vYQQ/fMrdc8xe8BwFdW71BapNgII/JgIhRvrzZeEEDLk5GVYh1emNjpylr421O4jiPTrs0XBT5OibTWWbBughuBajaSpzy4ZB8Uy2Pod2Y4FN3ENpIRnl3DHCnCE1iEY63/oCGvbYaq2yX5CxaBMKKxBDvTbmaPYfjtuoNVrRSeC89YuUOkVfv+KUQ30fObkCMyysP7TopQtIj3yXevTK/DPz55BYPzQup+7xrMbeDnl7mQ58KMMU/lvZzeDI+RfTE5DUVOb1djBJNE5OHrKtSJSxND19knQWnAqlVZHqHqnZ+hgLQpJV/l5EfL8x2vbO5v/dMQgji/y2eeuXX3nIRAqVasD+DXP4tNPleDUyB5pQrXl5fTgb1ZtNIXSaH+iBvK+Vw9gBOENGIEwSM5IlmfW1hGsx65nZ27/sFwPN5jHCJ2BAH1NQz6/a/S9Sl/mp2jh38cMwkrEVM29a9pHE9tyTcypUCg4gwGyCOTIoXnpOzDIvsJXpMl8OK9kc7OjOFkyIPwaBqscYKcNqEkK/nfy8GOS+u/97TzMeLwB0dTzXmmcYTdpyhesHVJ9C7bmMl4iQru+UGVx8usqO2ma2i
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
