---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgA1EkcHzST4xjI8RhN2E9G+unTRxfMOtdVLJ1vEjBd/joFUuXjUfE1ZhjUrjHX8RnmWq2QpTC0D5qZjZuFWH5zCAnNsU214LONtbHY1ICIpybwQtjpUuqFRGneDGbX7g+nLUShx4ull+Zyo3hHljMmMcGlXFs19Uapiur1rHZtUI/kvlc5wfOjP2Xcb/v/ENYbM2fiet1NqbnvYU6WVX0efVyaAGHyJlwZA4N77WJP1Xtdtn8PpprzX4LEiU8S/Gs5F/PvvRjwIptjvXspSqMDQkMml88717HzHh5wFHu63WaQH/KPHWhssIMEkoYi7M1DeRjR7yzY0NZX7XiHniwajMO5DNJMNBRdH3NBkBtdeigREpIRQ6K2+6UGzdLfwp0yf8GD6MT+TiQRsKBgqoDZLwB0CCaqAnL1tigf1U2p5VqERvfPdvi/MTzFkLMtQGSgSDewcSQF4KHOTmem/Ho108fM1cdQFSnUIZevwo4sONk8gEy7uQvnTHgDOdVKUuXGqHUCCGr7EEmXuOhnItskvS9mtJbzOOvnLdfouXQrmBZwf/UVFcro4oXmiIweD8xx+i0lHI0fMpg4W7p3rTQ5YDEaKVkLlS+W8LoaXhAb7UBne0GBmLGxrSQ9zZ0JxqkGyZYs/y+Qr1paK8Z4lmzBI77pauZk5EzvvIL2tLWT6vb9g+pFkl90jKXG0Nv2L9GybT8b2CgMMtDtOpk8NkM1hiUhQji0m9NvQKAar1ZsMyM/lpLIeFGRw5HmmDFUWemE9hP8r+2zHJJD1rLeALBC0ANf4zR8QXi2Qb3YheUP+wMGhIHJ7TUg/AqK69HY4yqxAr/Wra9y58GAjmMmWJzqsTpJh
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
