---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgBtdvAv/Pa2H+F8+1ih5QReLCHOsoeF4LW3lg+23Ur1fBXhleZvfni1/BBmonlZj3Jxbz8lrTju6jf+mrnKiu8rSM4EytvsfH148CAcvpwJ4sY00nbtajgTfbo4AqLka/kpiizB2UTPqWlFQN16ZI1LuvYJ4XcaCYyCbDTd/kCbGNsqBW3v4WGdy0P7RjQRsPFlOhb3kHR3L/htbTcHeh8HzLX/GW3H/Vq9DaBkIRQwpDe1LbDAh1RwLo36Ptky2W99KpqpUCj/YoYImQnF8MDVfEH1I2SqBDrMRy0MWf+a2SagiNEx79kvBW066GjyuLYFKb+cpajMTrhmwycVZkoL76UVtfmr0LFgTEIxlP6WcKsCdHNlChwkGn1+K13sDVII+uIkXMeSSHdAW/WTs4usUMDstf9OBf/aJG1X0SgjC7zvQ9wlwGiyDSkOcSJRPS1Ab+tnZbH2dhDMiCIOBDWVK0z/FQc+wphe0sW0tCUpG9RqVGTADd11W91zr1MXnmSt0iRLa0XuXdW0AmnxiZqUky9opVGP91h9DHUo+G2y1WL8ID5oklRp6EvhmBG3AMTg2uqnRpAW0Il9Nnta4q/1oN8JUudcv7zuVj2buzfLwjMewwpjcAJ50nhs1VLE4J9nd71oPp5cnP0wJaiAw8+yKIOe4zW5/qLfwdHvfxGfafqdb9YjvUXpVdch6oAHEgtI1tnzmq5v2JfW
    root-user: AgB9UMAc2xmfPTJL71DxGOat4dQF7EVKNUFnMOyEDB2hZ3qOuYe7EEWa+JIkUfXOKawpWUlEsPfQiYs9rdG1LRQG8LK9m9x5D/mssxC5M1mGizLS4KX/obSunyXkBl7eybITW/TQnnGwWTyQoMhwJ+SHjPAlRZriCezyhM6pWW/Gl/5aAHyYOfsPIC+U83EKWkzoSkZUfYyW0Rri0m9zm+8ecjyww5uTNJC3+e0oje89EiXwnzdUmDoRt59H4SfE84Iy491ln4lmjUWGAILJnXf5ZvpwD50lHEktWqsqz/A//gnXETzreYymlxqvadn3RJNgG4oS5neov2oWTrdMSyvIwfujV3GBsGI+VGyEMAeOuu/Lth4Wfzzd4uQV0Tn5HraQa7S5Km+Cme8QoAHQywjglB5K4bARmmoarhjvgSQb1n4xxsYBmsnB7xuYXKuws8fAor3lHp+ErHmc0DISctch5VfhtjdbtoptzhMlVHxTpJ28aR3eb2T+HVGrYMnKn9QUtPqdkRZxCyU7YAzsRf6rImLJ4yLhrRdkyHq7JwioQ5lyUeKib29x3J+MXRHTpiUbmRe8kP6OAARQayq0FgbgwU3ktpTH/51FvoJNYqD4RRh5qGPaSjFu9RXB1kaaDNNyFBcbf5ZV/ZL5lEJTpAvm39d/tkp+7jSrciB0Vr0XZV3ojNeIqwsB3YJxI/KOzYC0xOZvIY5BQ9mX
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
