---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgADUBikkeVe+ZSt8MoOaskMInGZVymsEqjgtwbt4rWUAlP6AwCrF6r794tdR3XR8mOaVHuNf+DfI+bL6k9XxmGMQec4FarKRM58ImkPLyqu4h0tnzWIurdAmycfl8QMA5RgUR5UJNd4IEMRg+xXQKXTlb95gU5f8GOauH5k+JNqtm3+qlq7rikQwX1EZJDqAyweBt7P3rkM78bocqZnqo/sxLCqel7VeT5nUxC54HV8r0mMUG4s4EV8K5nj8xi4xJFCcOYSXXK6/PL0CiYqqiGCf9kBljR8QIv3eZmiIbgpYOp9bKrs7n1Md2hl5nmtt62yDoLJcETapt+Aw0am/8tVL3uFHMt1lP1ULW58+4SG2kB/gpvlbmVWXkYPs7T9LfTatXOmTkjR4EH4jZpjLLE+9mH/ONZWFTg84etDCWFj2aErGZpPGYnR4i8Ea+eXW73ei1bNec4hU2HqD58/L0UYjNXRKWK/2uRsIWtWaxMuHtR6Me3yfrralwk6Yb7qmj5hGkbkUTUi5k3BituPVkMOmeIaPFrBjGAjs0k6wFOBsBv84FdqwEq/5rk4vCjdDTfi8i7GCfKuCUk1ytqXeZ+s4sPcdH7lZ5maPkEDYiwXiBAy3u5IJRlxmaiKIV/4F3e1qZGA1lvm1NUGNj6INsWfdMVG2Ots4535ZnisLv4iATNlRcj/cZ9+ZKSp2qFA3iXurbt7V+aYDOIL
    root-user: AgAY9dXxQOMS45hOoxTloj+6FYqXqfHZLPlYPJNhYIIk8GljEZ88p23ZBq/uHLYfSWmbZ3fks4DfjyqjnrggbbRkVSkijMA526AB+8LGwITwzcAInvQXNMjoIjfrXCNgWtfRsMRIV4B3As0XTfAjycI0D6xVTAbAy449FNRJbjuR8rIZigvDCBz1px30pAY9IcS34Cw+DyKlZS4h+VgTa50YFfTAJ092WeJiFs3iADB3FGC20WCEtv4GM3QtABv45ww9vKrkNOXM3FixL92MIJMx1x4ZEq71b6BJmIk2iQLHKAB1O3LRbkryW1TaBU7mesz4Js8u0AfH7goV90aB5DlygsVzlOzrRuepnDCKYGAL8tegbqrHycAIvV3vTKK+BRB4mYu8PLQjg8SRKRdbDA/rYCDMUDSQeSzdRh56E+b6xtwXqex/NHXgQ0jMIWJbxdrOKfn48JTeNiuxrM8QQgAFPpLBHi0NlMk7hE9TT0RSU6x+i2m03fI1XCRnnrWPGaOIQ+A8wg8Q6jtteRN4E9oJliAShgYAzp0WKp4BhUJN8qQkNg8tYboDq9321Lc+r4qpVftxIrJerawv73ADIom1esGIjV3omm2VsBxYMQGfEdfv/hsTEROLHe8EHZQKU6tIOCs1MSI7pgLZaBaz9a+MvVaC4gLollpLFinMgOde2jwxs7R4YKXiVdhWGL8HJkmqI7nKw3mKoa1+
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
