---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgAVAMadevpbOq+3PZOOrNlDQvMDHRCTFEwd23InaP2enepKDNZCC439vpRXZVU+Ws6fMHoNNtiKu194RWbs5tUziJoQ2aSSKOlQqr2f/yFddiVv17/l/DNPbbf2sJeLT6C4HvXEdtrr5iL0I4cVuW5u50kbGTBGl4UM4P1Jsnr33oRtqykPBb6EEpNqubjrIRq0KWgI5I0m6DzyjuDdWoaPC2OmjjN1GHIFfGPhpt97H4U7UPtKNyaxDNQ6vYwXI1x2bdY+DO2zjkQhr1DGruW+cPyqzfzFdXqHWvJs3iXqvTXgOALNcwBaNivkjzWiUbcss4UizikbDkQX6v7uPUpUkhokd/ycCWTVPuhaOI0QySW0sDiwA8xBakFBnZQWka2l7bGC0YDRWbtgpoMgoy19L1eWtRir6lL0hQ+8vpcqay/wCAAR9JW0goqaa6HD9FYXlQC8o+JvAENg/TLbJvB7Fl4xDWfHXhBMgD4HzG3vi5rQbtFTUxqdXcRdUFlT4S/D0RtGfnvBMEuWnXUDq3c+0dnyLWK/uSgGTAx57NIE4+tlvWux/v3SUCHofjUgDHCo9Z1QMWba5xITQIGRcf6/PW6J0EphM7xTsIj+Kh/S2pdsBnZlfEmmgRqfVlljFskYxzxmmLEcwx8QeJzFR3IaWQfEtn5Ol2dLIHYvuAcXOp/luQZBEZ1uNbn+ubVVtt7o/Jd2CG6FCwdJTFQ9GcIWI0dq0sR1gHnEm93V026TDh89FgWFJKe0IqlhWlpv7xuRI6qjd0+w4yN2E/KeqV0nbAI7vmxdqiRJA0xZRU5ofY2+LoFSWCu+szkzwJHhoZX9wZrLewE6z8Fk78hcfLLY4GvA
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
