---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgCHRBONNdGlHe8ZVlsgziE/tQXSnl4EAHK3EHuysBAPIndAb/26fKAem8RpJrl06eBodZH5a0BQJDN2Tyw2jJvAZYWvmBHhZHNiP8/rijGWD6zLkdtqwQD0Cj4L/dCYNkiNhfjx81EpszQw+r2E/39U2l1VZnUtPyevnQaMLnl4B2IGULQMSCHZ71XkgtUnmrBGONYjXGebkVYqaSceYLvmZJ7LQfo3tsvb/Bd+1oUvOG0RlI7EFS1SR1OKnOupJmvrKa4FjNx/ybLw5ks+7TWrVGS8s8wx2geHNRUT+oCgVMLDCQDhV5taAbKHip/ObFKC08fofzjKvPNY+lybD2bknN4XQvAEwvnyp+5eXEr4KbEl3mr3HS8ia6NCcglWbpBeqbY07iTlCiW1SYQ7u5IgH2ShqfGHf+9C7hzFzob58zTVdM9mX/redrTWRluuda0/kxEcuMKT3Rig02/1OUXTvSwZ3RPeV/u2Rekoytpml3mxvVE8xjmjepkBl0qs8LZ85G0LnhckksitVle/D0OMmYkAjJ+YxSY0xoPT9h0G/N8094sqNCTrFtTrLLrCqLGdUoH71K6j8XH7f1/h7fRMmpKzV8271FPtqLk8ucO+1CiyG6mfv0aSPXKorun9qvzWHqjRGB8YAxkCLrvdLkNW+O+9Sfl/lP9irxegmlNbJ2RuF27y1qaMNQyRYzeLHmb+gsDupRCcw1Vp
    root-user: AgA7EqDXCtMAWoFAvWxvpphocYdt73sF/N4rW4CYmxJB6z4s6qO2i0CCILWVEKh7TwbM4XWyApsDOZOnhAgwbvXKxztXiwBo7bOL3WCCETyOswqLeAP3TLQ675Jdu/18cik8DG+OkYE2vNiaXFwgaYz2XeCK8pcMoFCb/7W5nxMGUtFmaGqCartTE+ge9QldFa5UOTLESj9O/st2nhtVb4+16fpXtBTPR4YuMxlKI6bL/o2/nXhv9aVEBXY/Vrwzh4wlKotJIH4e8MU+SYfFm0BPf84FaaJNK6i4OV68dqafhJNfitgxMgnNnR+4dU+ZWgB2yf7J5lHjGy0u+74cxiBkHlG0WA4wu5Rtphu4dUYLZkP3qxLAmJXVXogbjQyGwH7QdKyR1rI9OvMRnlP3fMCRD078FSQMxXqj8ghUP+vLZHb9k+DfgjRQJYbK1nQk1Ii9N1SLMd3an48W5VZqc3WbUdLV2AYsAeg+/UZPwTEh/5bikFo/ZKuawJ3zJOKJ2VKq8R2ZkcDfhzCBWMWEzQDZI2l1iMR+Jb1mQUz/oFv98MddG4w8dnImm8JGf2kvbcx4h2ogw0S6VhVHopMsOF9YGBs5OyrPK/A+uBACs9I4EUff7oHbQKzzKVQdmUXTt8WZXM36URz64vRWRRRmFZ6baREmLHxfTDjYq2egHA0gJJoCv7BZEgMUJfykgn9jQsR6j+LqWA/f90Nc
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
