---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgAstxddAtwqzZsWzasHke+hMwTZUIle/JkRa06kgimgK7lNPEg1NpMh9Gu2BDtIUL+IbL90fmAyOgUvYFKWTcuNOBVrTP2ERO1FDSgJjcPgWikqkUh8fERaV1k09KiYLvgF5/1D6dLR8p1Ld8fYq9SXQ7BSw2rWTmwUVwuM0B35hMsNkW+rgOW3b024PVSOtkmF9dW9lEd9QqFL6D0ar+F0OUwhdO59VZ4lBybuZacksFGzA8Hab21dHMhNMh7ICEX6v8QI15wF4NhkYOPkKtTWkV8dThvzc+9C+eRXImR85Vau3+uECc+VpEYCvKR03NgTG791M/787H+xBuTjzjciHwdo+K9RxVXsFIFBmsR/HY3LftGBc/HHHvh+519ggN/ggavod6883tPDAUviaAP5lFnz0teGP1NfscMgt+I2U7qFLKlEgjFftv9PK8b6PxLvxW/Av5nGIhFhLwFZEgjIBmdn9Rp4qjw7DFUpTzVp1hKHJ4fb3EN99fARXaRnUw5Oz5aregRjwZOJcwXRrPGWNEiv3WVau7hzs/RfbQFJ7HnibpTjSTV0mceg+QZCS0IAJ5/NwAAEKOIJ5KVFlJ4Iwpa8ypFfkbAeYXJTnwhZOuAIOnnQYV4y/8LM8JysNLosr1KalQmjspqkQbZDkh3ZYJ3JqrXfpNLaWLSllAq/LORP2Q96do4KKfAuSHZjHLYQZ4krKukcf+YP6UiOxuXFpKoWDfFIOdraOOKfw/44nkLFpOc+ZDilS99xARElU2jWQQ/Zl5h4+ZqQW08ttxfewnoszuWywppGZgIoDE2IZwf+a8+LiZ1xHnmHS/4GYm+hPLmMVqdiRrD2DgqqUL4mcQtt
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
