---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgB9A02fBeyYpG8xM5xkWJGT2GWpqS5SpkVZnqpIpvGPmRiLfxFF9E5D2NDpVan2jIDupgrodgSRvGVmpsksBdtAkNMxzSrSJTmyoo94DfTbIjpc3zagBbiyRqGmsCLcOO/xrNpm7FmvT3jgFMKPsq7JsuKAvFcRt8QBQL+c/IeyaYQimN/bFhYYfxqcgIFRwryxvlniNwii0UiSa2MG6BiznvKrQKhHOtamKiQH9f0qSxf2PZxCH/dBYqobREPO4nzxEFQcfk2Xt9I0iWypJV58KIoGzfYcnKmjwEXPor2XIbUg8TyaNO37RrN7MD6h8qlcUSWb4GDvgZtO5jFSwM/DSAQc90YUyudEP1OT+EZmzr2My8+L3Y5UBHNElNRai5p6n4t9j7Dat6eAhMriSbJI7kMPG9J5tKEEMFC3Chdrk8NQaPj6tRAp1Q+S7RFYovtUuyTZSDcjCvqkr9IsSvHUwBvsLwKL6yDQyqqfF+D40+WQtJdmE/Glae5I5Tn6CiYxEJt2BDccwHnxEohhCLhBUkDenZS9TRtvi6hOUL/8Mkd8CnzKe7C+4ZIY5l3bGUJ0myAFCtJ8ZJoUze32tnOFKCJd0hplA5XTDJTB6+9Vl2jDphFQDzdcaAqFjB/dWkedBa6z65dDS3xVtYoV4fgxzzmFsZeGg3xtgOBs4MkhkRV+nXXqvYR3ibzBUrotxS82WF0SFHB1qwty
    root-user: AgB5HuEVhmMeCTCjgb9JZ1MlAevbKxofFHsJyJVfnHNuVzsmLQN4ZscS/vkkTp3N2amDekYNJ72jJiUZUKtmQWDBwIUcxLN2RJMqDjfjhkx7Foqjk4kHniYPW2OAhfiE42bJVkXHpwmc6NIZ3F7g5dWyOUrfxnm8z2ftxAmQk0BB5UaMg6sWbQc7DMrtr8jYc5HsXTQeTNmgRyoOFyiMIbxgIGIU02oqcnGDp9gR7GSqfzE14nGjSY44NoZUfarS8FtVzcBJXydP/kuOKGfOX8YX1OrBCuzI4Xgxz9NEApQJVLCUAR4PC0icTZOEpjWX8Odek9XSazLUsCKc8kY3MimUYvQyS70An7BB9scEqyfy+/S8n7FMy2nBvxIaZ6MZGnXq4hJqtkpBuTOa1Dp2BIRPcWjW/0d6VTZZUzpQv5CkjLlj2FQWZmQZuuQbNyqSk/nvA8QV1aPjTXaFK2D+aqND1awJRJgYKgZ4ugnUoJA1OoOWGNoc/689BVZsto/ynxEDDJMBNPKAoZMSBfK+PThl0N3EymFy9jn+iO4xh4YmwByTrKVTr0bXrxZdctKG7tuflfYXDpyKlDze2FSwp7//FnLGJHygD/14KWHa7xg0p92xaNN0dqyJwyRdPdDMnZiUyctqbJ08xLOJwEbXvcFz/NNcZATDTbBM1Tgc8X8LzmQCHfxmRUP35hPCfokVuh96TepIgab/CRHo
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
