---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgCHJ16F8Y7YmsP22pp5Xt+8xTxZs29YlkbeFqQZTYy0fnvtmM87U/zOe44tE7PH3RRbK4uqRF0O3ZvuOstG9ridoKVdycxs3ijh+J/fCYNn8QT7ZE4Tq+8D0nI17T2bxMLbxvYNjvA+vLzNttR4Dd8PJJ0F3eHlJwcYZoWMz+VeIugGakSx8YBq7v5hJiHNogTq0bycjmvxcr5mTFoyJbD32n0fig/l8+/AeVRfYefIM1GOVx8M+xAbA4zT7nXxm1EKQVT5dwUzmEjPpApbpaKGFwy1UknMma/73c+dG5s5O6QyOi4bjKfcmA0/MacgTpbTVVwMH8qO2GO1wtBXpBP4ECJ0KpFtxvTCJYtMNVMMx7t/CS+Ku7WhQplaeyh0L18I7ffOwoV4iyK8hbBTsOicEw8v+2TWExAPTdT8Q3cx3H4Kx9OEEr/OWON+HGvuDy6Z8q+Q+OMEwUD2ghGxGLvgxRXrJcd8bR8ogmwsJHI1pTNC4EAl9uaF++oH0GqUNeENGiN3d1d+aNACPt3e7j9aVZSJ9rXiBgR95O6EovT9QSB9GiSpwhf+Su/aP7y1xe5qk0jlb2gxt1lykAOCIByi/zxbe/NZelhC6wCF6yUz9fQi3JKvKJmvj2FHUYQUz6UOklS5DKh4Ttp+Vuk0N2FAqJROawrLZPUGbV15OHvgtnCoyhvCtjrOQQr5NenBZpbsQ1pNQQbh6x+/auF/z2Pivl1DuOz5HqWtISBBPUJIZ9topifpFVJXN9hE2CinI3o2Rh2dos27nQgwuerWuwwyatOXZQNH2DRaybOQ/Ntz3PCeo2Edo3Htb7l0ENknOw4UdcVaNGiBj49bJYoikpKf+XrA
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
