---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgBSntOXJd5U0WsshT1ufb099yUtdUyUcYt+RuQtPL65VBTdlQtOA72Unkf5x0zqONvQ7n19BQRPsYZUgpIfKXFgAGT4uGUeWWpEn00s/+OKADGCiCTI45ge0GNQPCS5FYJTXm9pmStq4pIi5gh3JgY3mAlob6O9re1K/F8LIp0JfYBIof7+Mf/O+MYmoZ+WAaVnnfNQnzmTK+5JiaQW+nS0Qt0iY/aIF9WzNFyv9VuqbI5y19N01Wh98YqKBWRWgK/h/aSU9ycCXAx+a7bp+AzPWHX1Yj/ujmHMxehnLapMgsFUQKi+hP5YRNyb69wuF0aBAr0/0KYHo/0xVRW4QH+NHD+knIrqUmm54ybT7ry6TDMbDG92KA3FHKDQpRsYpfLQ3PLvQNRVZ+VnN3qpVChJYKZHLb9H7i4C4izz0nyg7XX+S/nJPR21ERaqz+Nml8trkYGkvnfrjq14a0/6Fv+xa++qbx7aMR3dTFkvf4wAkuiiAHyHQnGcdwGealF1fWJBvoQW02kF6aB8LzuSzk3Q9ekZW+xgQ/zGr8q5YixtRm5RVCkjksKGHxyPBBi/HR3rCigRsNd0750aWWs9dx64jzdoQaWa8SXkNqajO2UPsn2+gj+ZVvgDN7M3mTq50Gbh/G4KsVQuRARd80AASkXQ6j+iehySO4w/cKlzdqdgetY14a6RbTgoN0IXZs5Izznd7X5zor4/w9EaCXCauzrJf5YLI0GN0CJcD1oVZFcoOl6xUczVgd2u3wzUrag1bgNdtHuBDO/iU61Di9sfcq4+AnGixiEZWivE8RhniPLMDQ6Q/6dNwKt8yyW6beYC7mRDUbMxBIU8rrZyKXfU938SCjLA
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
