---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgA/kP4T5axbcHytfEB1kPkcXYeDg30dRQRX+fYbBvDx0/h5fJFSoZy0Kq7bs84wKDR9hfdMlDPKR4a4E22ZfcjGj+cGJIm1ga07baWbePJwEKeimbSmowtmTHid3Ibit69Y66G6vgL20QOHjJ4Bne7H9PjughS7LLSKbCh+1Na1nqOayahk53g5nTQRJdCZALIrHrgp7ucctgz1wlucFzmPFrVCy8ZCmuoxUXj1U4kuzNYSdZtOuw5/sxgEa2t1GYsilID2dksX/uBTGo7ZGXbOnxE2s49JZN8LjTYdq79tcr/xkFM7JKxMkr+1Ql/6f8kiDx9mzt+KoUSQCnzzJWNb2xvbxjF5MQAJQ90V+jGejKMzsYYxaARf7Qlro+ZQfo84ejJMpnPzH9ilEbqik/TmJuGCFWl7/1XUI/R4vr3hfrHRulXQJI5pST1hi4Y/7cty90EK7TrMXsf/xss98QUA2ScnbFYlgjIHthI3MtVGSEf7wO407XQP66mjQBzlqivpxgknwt0BgTVani1e0skxwP+iUY3gsFgNdPSH14/3GO/0ejP77jjzzpEVXoU9b0N2rW43SYYU2/mlrtciECsTAif4JvJ8nQUxTVgBPGPB6x0uh8YDAdPnmCTe0nGUv868VzGZaeM0+Ho72mZVbiR4m9tMrNcKpuWSJwLAiM6Xtdpyfz8btk8iQPkUaQmOwyjyblBRRozexz1w
    root-user: AgDMn1ZQhbqhdICaH45LDrSZaZbW4C0rgb3h2VotwyfMoYqC1zummFUs51arbq5IxfSOGwRC3r5YOdtjYQs48R50mjM0L3YkizDTvBXBP9hcQ04jQMOgRH6tZPots3iEU1VnKEsyjzC7GInfqnonLz8Vo1FaB8BIgJD56vRbBFEq47cnUD7VAIreAgHDMiRimhHrrl92dMam7R727fd+s2Mh2Fge+GnarkuPbZ7V3b2gzV8JBNnl+llLWnFxm9GJQe/CVtf53DUuE5XP+LYwYIXzEPtEMI2JeJGFjlJYUBrQjQOkuMvitwedaQqLW7gdMXbhfq5tqfonKlpl6NuxHVnP+uWQTUFXh0Va03MCZJgxSkO5QBVAy/v/MPsGAy5PsTR0H7XT0rVFT0uCHjv5w1tqQYu3adrqTc5qxEZWpekR4MvRJ4GQrfsPjsCurbMukkMXeipWhO9thwsPChiqqFkutttg+cfz7wVuzKg792egbQx0VW17zn5wcCGD0qKlD+GtzsgVh1B9UJvdypwmk8kpDrApIOgarSt4p7gaXNwnYzvncwk+ccFLIdFpRbyveVp0nnlIdZSu978IasqJL5N5D+IayefioIg02dVvWQxYBMHWkxoJ2SZ2Ey/Va0dKl53UZPgn2h2hZ0Yv2GAttKYhQ9fGnminKrIPWiza0dTvisBbtwQ5LXsOJdi1qfZKw/sLg077HLx2Uejf
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
