---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgCCdg1205UfaFDjga1PORCax9SKmMDuQJNQKOCwAgfX6xzWAVK7+hRUcY9Wor/9PbIhXnkT81i5GhvUbMdGQPSwbywsqRl9+Z05u7PWuvlAteYqF6n/d7SmpWFtKjgXk6AWe7kGeei+yqUN2ckdYCeRxymAThcTmhmH/s3aMr5bEdaYPWgaIUlPKlug+88BaFWteHQeGPwrz/BYXdjOax2/EjYCTYzYJIR31VrWmcTfv+TnS5qQB5khW49U59FFFQTgmtdcB1QuerSc5tmb2+dgYLil4aeIwTaHso5Ow23iXwvgiSHPUOFhNi/5gxFOEAoVVMh/wmiRlNwPmIcXuR1DrB/QNMinMIZr3SZ5CuhQeyIfQsLihx82UkpO4ComOADBhqJekrpP2kkfLd0kb2zp0e04Su0Ymi3r/GWzZhNNpk72e1t0yyMku+xaRD7Ck2FxUCwZSkWGk+mFZVlPjD2IPWX5mHiirqogeVqSsGUWv+QpWTvbD+ulJMn63tRkmjWJL4u2NYFBTHPCqyO6VbcPX5RNG7xg1lN8nvx3/6O2EnbnqcYQZ6zdAKjyl53JqsZzTrfl0W+gFtEVLrKRk8NH/BxkVH8Aymwo8GU9JLcTGt1vuV2wIF2fc27ZO3ZtpBbd/aFKd55haD4e/7CorX6rYnUb2D77F0ZSjqX64xli5avSbH2SEgFEeXGKxEowBwUd4Q0yt446/zqRG4VHuloajHqYMZzuGEwqE9GdGF69gAlbMOdkKnCflfNxoRt28UYpaopilX5LbvGpxw9DZqjS8YVyLrLnqpZxxvjRe5B1S5LZY/Qiyy+PnHFaJie4QP01mht1HLhoZAkXbEokGau2Tr4P
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
