---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgA8CnXSmAhxR3PX8KsIrxRbnvMNhbG3Lnu2VT0Kk2WsiQ25wmZUG8cTO99SkanCtSownPT9ad6JLIM9lYyllp3f5XKhUEiGa6edWH5j0sg2DJMvm221J/rbaJrnckhX/MOSIvn01tQ6iVwBo+zwzwVxO7Uuzz9TR3iiAZSmkoZ3qQ6g/ETz3XpVLKvNtoPu4r5cm/E+5sH910r763rIxkwICNPyK/7FyMBzfBi+uXXwO3DceA28UJjCgMNmKxCHh1rnGNTWgMk95v8CTwovHdtS2VVWdQzzTbPOab13ZtsnOyNsfBE/rhLHOuxy1aJpspprLsr8LztL07GsA3iAAEYz12iNxndoH0qRPJjfdWzD0zvAb9bLqN1CbPoTfX/wb3CtmoGWaIICZ7zsMtKYUkrdu97Q3OkZTsyXa0Km0yTjVUbfRInuaMPuGH60J9D0gGUs7oNZ+3NQK+UUfqCiQad5IXqGQxTb5GcZ17LL17TwXMO9noq8H/JlM1lZJYrqBoubtpjPjfx0mznLmxDlUHwFIT42T812r2iW04PqsxfYTN8WRZCjrs1Dsu+kCxP6vx7j0+PP2NO5AuT94YUFpg0I3izsEYacw/UXTRZT4h9UDFMClfKVMzuJ3IfzXQ8nmRf3+MWYz5UcS9fv13o14kp3cfyU/CEI73IiSsFO4ncD958U5CgKjSqmqEK305BUp+8SRjnWHAlhHocsSRnwagTVPM7RvUTQQh22WajALatEdlYbcjboHc/vrEGz0o1sznl/2MVfDTT+tCwX1YXLSV39i9XotFI6HSkFyNSu7ohZxZQpGcNAD9gL2rFncSFQSMwHI7Tb2qHG4xc6GIxhkus+XiFQ
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
