---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgB5H0ZqUkGd4ablOuRls5U7XKqOb6fYQvJTexoECoYTYMKWYOV6Cp6Run1a0sUIFLGJJRAhGIdKy1MIDU245joaExSRHUGq/RpMlIEIy3Ovg5Pjt3++9DQnPtl2PWPdvxAaaCB2Vcg/HikW88AlwaFBkaiOzXNw2mWTuANk201j6q2SvGVoF45miL0FjpEZ+bn2DFApT94yv2ZzCbGDPfZphtxiDZCaFAsyf10t4jB+HEztTztKe0uztr/asrgYCCDpop/y5NC/KZ4OXpZ66JNgn58Yw6En0xZrearCO9bVIFgyS3CPteD6oUqvqmOSpXBpbawxzKvp9p5nAmdYCsZYq4xPYIVBP+dZRLBoRSSPtsbzDCCEZpf9oT1U+1PtC2unufRRt5ulXntKbRGXVn2OJYIfmAETr8cAyz4B6F8K2FsjeQtUg9egmVsFmTX1YkRVsQnoo2A+kusDxbi4spKcVOqcHngW5HbaBiFa9JsTPYSpLnO4z9lFEx7lXrA31EejMtl3pmGFG5edVlRjh72VdLyg8sqOiBQnYA6lphOqXKpxPm6/CvYgtN0AuP+4eJibGQTJe6OKBJsX+E6unXJPVBUY1ac4JtcwaBL2E37Lk4wcva+9Tl8PE6/cyWlFrknhU+pAgT3IryWA/6CaW/O5XvKt7DvYP3LC/X1zyiZOKRL3eabnq0exkKi73WIqH+vZiXcGRyMVEsfZoa/C7KhpUIFEp2NtQBBpMlfQlNH4ge8q+Xe9D3X+KgarApy2FSZvYzjGSqa9jvBHj7bIZbQidk7j+GvBNHqxhxPoeXKWqy14CvxNL56AYgXLppr5kMtUJCEsjQKMhlGTqAWmHCPIhFaP
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
