---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgAlYIPjNfHH+fGw+S2sABH0ostXPSZ+sps8cSfPOybagrAGmo+alboJhbQZlFm1Ie8rBHQkK70kaIzCB+2yhF+j5JC91z9bLzbayEsaHkuX1OEd7UQByC8LWN5+Z0qOlrfPbWps5IXGdYW2mI9/rxtlZgvqATIC6zW+yDAYuG6jSrfgLw2QBs/0TRrLlcvZqK9/zvgF3CXf3CJUZConpSI1n7Deq874J88LZqNhy8s+RF7LyqCsI8XnpRcG5OGivnXJXTbEob8Odd7QAnlNne8rCiQvSoUNN7D0rJYwQNt7Mns1CPFpGw5+00MQ4xn+Kfik88fObp/0hXBo8AKnWhl8NZHEdO+UC0BxT1v4RMWooLT0eAtT1jVJAFX1xEGu5aSW8nSYmN/XZ4tDcC5/PzdpVSvEUR1wJcJor1OFPqhuuxyQxxU/CAUP+1WO4KPoj3Tl1YmohJHhoMG65n3pqlfev9cXj7lsDEIwsiIsv/mdPY79gcS0U1bQ+ytn6Zodmx6D50+XYVkqscx7dgYplFpOTyfJ1m+9LT9W3VCRqcGqvFx4QJ9W1acPNAWu1Tn/uMOUlMurGr5oyHKCDfEhNq/cJetou+mlmuKl3dG7CD8xB+TDQ55yEsu0rQNtnhol2UFmIDSacZmYyIN3AE5JIyjq3nEMepXhQ55vZRiysLhZ2Bpf/G6y0LTu8CNScZfZ3FnnmM4hmZG9WW03
    root-user: AgCqqknqmdkZBPOmIgaIBZJPc2onGIocqcah5Bn4BSdDOZEfeR2yMMy+JuBLafN5+q5edkqqmbmgvizgE6n+fgENZ6CIjKRQxxKGIeBLzCW4y15jdK8J+IFSd4Nx95egSK0JSqJqd321jpQRWyUCJIcaTPPHFQqjEdZx53gA1Ka5xCuqrRwF1Px6rViY/VWBkfciB/D2p0KwhjF6jesfNj4NDHmYbpolZvcHxm0hHRs1/2kjvEqxlbv5OoI703W9Nk48k92yWlbUeAmqkOdd6x4Co6SFn0B6BnayRQ4ngn/OrZiZ8l0OQgmH9Jv64YPpE5lTVnBWR/2IT5cinVCS8cKukERR/mLV0GO7SjLrC7/EaE/uAr90ZRulP+ZAAqbdRd6UAAH/plrnK9LsGadIBHya+9pQxZkgPJi5v5jAR15PRthExXikdkDp8jGVXxkIBdcwK/AZEanKYDYzyuny2ZpaEEHM4MQ35qbfQnuMce2fP8Qsa/TLpJ1T7zQospRhC67HJWXdXsNodoUepjLKYfaecaq14yXKnDIggQR7ub9hRQJGz13yyeCPp03gHWX6JUoCLM5t3OycJj1QPwjPiakm/MN4O/u6uY0A4EQSQIXeVDhLx8hOCVAnztUmT7S5pgbuWXTfPMGY801jcwoLXzZZ5/MLgd0+5jlo1Fj2FMhQbgVcsvOf7VLt6FJAMQBu81bz+IC4hQiPIY23
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
