---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgA5y23YGmKFPKDKJUFtqgttNJyPOTKFZNmi84IlI9bq5Jb0HriogxI31m9lOoZ3lBT5GbS9Nz3FYVt97Ous5SYRL9Hh78Ss6ykyMAdSjYsKXBn+F1W1nicLSnm5mTaRtDUdaSoSfK2s2VccwDdawLK3hDEvXT2R0OGwpFM48KqKDlBVWj8tnEAwZ7mYgVfGJcxK36bp2JP9oWfnGm/tqNifvJDFbl1HggzWUhhGzyZeAOKxl+PF2eOdnbW+g2XmZUXdhJPLg6BsnGHlqAGH7ziyueJ4H6WjCV9H08Qck5Hb2KFtgUV0+xzp6IZ9oQVK6ZbMxIfCzOXx58gz1bvYcJ9IOaVDiOnHzgHS+Q0qq1klW1jX1JBxLyCaZonTlVosAzvq8NNJK+Tik71hphTrNt5d4NK0lxMWvQbw3yd/gF0Nhyg8hRJl1pYilEYmZ3jsB+BXwosau1c2WzfqWt50cLeKvZt77B3PL7o0J+CmKcaZEvuKdUyPA7YOONg+QD0kK6lM/W9XECwtb2w8177WFdBiz/deXHFABe39ecy0lOHS6zDh7WqIW7CVkYXUgN6KNDcPxZwokcE1pcsROzHlw3rq9DStmky0+YmRZcGvLkZ0rTQlNDPDHZe2rTKJDTouq2E3JXp8FIlFAWwLsjRYc/Cbbmqrm5veNdzWw2YPRGlf6Pu/9LaR7n9gFu874KzljgypdhS+sQ8R5x4B
    root-user: AgClRTSN/yZIuGqms+NdbHm7jrMBvcYz0nuhaJpuepDj6qJMS018qcIJoqvyjqTgzdo6XOD7Pg+Op3duERdRD2LutC8g15+cOLfXW719/hxiLBoGvcwaq390MxPZQKnN65ZIkBcTjO0WKQFOR33Ux/yftbSaxOTMirs1lZX5TQDGqvdTNIqhunFCxr9gBIJXVUOXo/tuol68lQsdHuJeR7qAznYBo31SxAGAqD/AUe2xY8ekiWR3JhWpJKfhN2MXx1UyAMNjdvk5j+Bxghcwg+98r4+gGG084bV2w9tyR+8aWn0BRFK81HHF47RNDjm1zlNwpcm//wbI+HZMhQXSA8iMZikDfQKtbZ1amnroVw5M4a6z9OuMchtvuddAhpKTTuxxMMW4mFNpxylmUcX3EtJ3yNaV74PkPgPnrRGqFoVS3ABfij6RYya4D9rh+NZMTI31uoSl6982sUeU7uwx2m/nbirhLP4WKg8AwmkRirGqAxfVNmFPVh8h7ADNgbT9hHFUCWxsl1qW0BOpvFqkRkWA8tfUPIJp+9l8Ew7gY1a7VFR3UgfALymMOlJlPe9SkU3futWDlcROAVK3JvYTaDhMCRYq7rKuxQPakLDVfcqdQBmo7iz4fPR6Ukz2sWgEVv3/4x+qXSIwygUJlCncSJhto54WPADhsczCwyvgTp2Z2QuMeP5Eu/wECrxHYSwAlaWxPUCfE/3GO6WV
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
