---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgCscgvBnuL5A8cmT8n2nhTLgjYxhGsoVbd4hsL/C+jk0MtX4qWFD3Z9OZ7aGXCDe9nMKnhGR9q1q/8dhdin1t/BYlyLGsPHz3L5Ail6iEfjkPOIZkur3in6K+HO23TF3z2rJwJrnVTeYyZgu1cPuDhhD1eTdG25oeGf49JU0D/WDV+b90vUZRL2drwrGtMPz8d7LEqxmTqiNlroFkH/5cG5yi8CkrtRgG8eHzr+sBhxRylLDnwtTyBWu3jfG2I8+klGj1RtOOp0R9VvjTquYfPPWUfPx5skLv8DUf91kamWaV8sLS32FrCsZTXlQKnhqbY6pUQxQr5tG5NICWVwJ9apjq02FFmjyPF8oIim9/5Yxudsa0zU67Fj96dCqugD7HD4cuhFwAfWJ1aju/LhWL2hz15ncWEII5YKOAA3Y/gr4Zf0Rgmeu2MeeENkFabvSI2MCHIa3PHPLmUQoDpUAaNAfuPddXKgvL9dYOhd6W+qU0Dh3qTdFd+7qzp7t9Ppme0WxEd9q/KwcYVsF//VL2yEj2T38wPAGKSzqpQ0gwk0RCyIgDYP1/BvwSjmwRARwtYjUD96V1SS3xhkx3cW0CnCfjrBft6BxdogzZqCDCceExxIUgqIQlHPgeeNcYV5ZJyLvGTFrRZATphhPRqSQL5ZrEk3WpTPOhlmNpXoxdNKFgeqye1kOdbJEtVeNkWmbYbEHyqqrsj1DgJ9zq3IsjXbVKG4DU6ucGcjzoyjTSqCnThbtBcVRYnjK2UxG+kCpoVo5dx6OOweCP5xobiFFySj4oSv5yt5vy7esP+j739UZROnIPKvJ3zoi+LConaF1sLeZjvszQDPEMAU8n24zi4ltmjb
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
