---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgASCOLlu///28TNlSFkGf18IOrr5D0u+p4vQlMacW+fb5EhVbGG2KusdxevFYCSIeBhNKAFvGQXABBBFShSwQFGx0vKoPp0u2mGlfsB6MXF2uFMCa3j6DfC1Sz+vBFQyPM8ea3uNUJS/T7a+Po+SaRSWM+gtDzr4hRNjBkUu3JhBlsypSgTou0lq+ZDAH9qCTTC01Eb9ntLxxlE1pb21jZDfEr7yZc4UpOxqgtWkn1+IyxGbxwLF/Z9+5jXAA7C3rf5d2avPIl7P3vmTtoKz1ZZPX4tP/FvHH9siQCdDt0+ornIdP/Egg8YAtbho0qjmrYLEj7cClxdZBMqiy6HsDtywgqG7r9Lv3O/E4O0+negm1EyfOR0wH1Bzr4drGeUr32xB63T7pZw6UBoarUlC00bWTjSQ43R4sqOiUvDtJAs96qgDGh9GZd3qAPNE5eCkikuIEeQ8c8E7xnKmFq+9tBJY+KbIHs2dIFgtj3X0o3IRzzDfAELJ8WK4QGMWLTdHq/kM3l6FRSW5cnqSGDo9xdpP60wZWeb7GdD+3eDNv8gV3OQ+Nq7hhCgEPo2O/f6O+QMDsSinvQ0n7AYF9dBuxrlX0r+LhlrU1A850bvhtu81B+zz9wJFFZfBjpYLxZGUjZKLz23P1dVLm+tR2c2/3kc81D27PnowE43+xLCOYvisWVyUal9jQtNAtKDRpso3s+IsaedGA1SLMWC
    root-user: AgCaVXMQm8lILHU3JR7aFb8NRWFA4sleqf9tUGsc4EvTiaLA4vUj8U7vCkgLuMAWPVrFEtp8tihQDDzjBCyJ8xaLWDtR0iazCUxcznVSnhHveZfAHMY5Mi30DMbq7yIfTm/iESPrwjAnqzn1txlEsI/+NsGpv94oCEojcOzi8LCBGnivJgTPtTpoik/g+yYii59tVE4lphfCTIjThKySLZEIH4SMu/greG2N7erLm/uWBw63z7jdZ7nevplCsbQj2+m6IOfbqW3w9sTFB5TqK8fH8cU7oTYX5NroHby7NhLyX57SjzFpmnl7VtIKOjtjrDqsgnfY4236UiNilP+tOz5d/ij+0JeOxODjZB/hY5hRn7k+g/7p1dlJPJG0TMLgnOFHCt5V9dTbdV+KtSMKlnGX/Lg6L9q52F1IjIPv01+AW5IbnuoPNMpw8OvL1SELI0dQkdXKWAm/UDtZn0aXviUAZr2AxzAlQKaiwoktNB7/f5rqu+FlNpIdCWfyCiHH+eRUweaH2Kkv9lRgD1KXYsMj4IcLhGgTPktw6sIWQX5DbexMl9i8qI1w3xmaU2KVQ9zmMa71J+aW0vvl8x9ypSAkEpkUmmFI1GMRgjYD7fL2JaMFKZgxScoarCcTaZEG/2BbxZuuK5EULPFMV4H+DIv/h71zfriZWTTtFj6kC7eoK/Plb8eKl9f52Bo4PGSWbixQaLucbu+xGgSk
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
