---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgC7rlx9K9p04QSZ2+6cGvpXaU676Cp/KXgYIPVjSlRr6aSR7QjZ559kSOpHLKUbuimiiXFjNZSwqMjaKtblseHFW2pGWAePuRaimJz5YZOTtjGFmKqd8Q8rucQ6L5yIuyU/sstXSwvwzth9/9U8SNNcBjyq/rcWQLCzMY6RJl6w0iVJ5FyZpVt0syi3o/MlQmYR0cSGlTbgcFbZwyCtySGCpihpgmBwO06nwiqNIN5U6olX76NDWEu2iMIJNSKH+/K1yXPJlYMQGT+hW2vFo7+tD1gO/Iy0KpvMdOWw8iCjDo5kNhM8Fec36Z3TVVuhsoQ3PB9p3MhLb6wq757K8Mf781+TJ4YaWgHzdUu4b5srfdZunLGrb0URvkeFauqc+/9Xo758pyzVjfzoyBWVsai+keYoQUvrgdyAEJ5vyH8JSABdN/7xLUbnrvMy4efmYGQIiem4ed3jGrcNucR96CyMu1aaxZmBcz5nnC0BuK52b3G2lN23HXRLFxpScnmh4s4WBpUYid1iqW7KYetb4QC5FX3wX5JUGUfnisBAbVRlwROghW3rALGOOuDWxxtryd8o6SSyhqlMxPfxM1RR2W+94s/ifFSAv2eeZKwdnNfANj2WyCTdcO+RFGpN6uXADd2R05qAHDS6YWIfbnZIwLDuxrg0cKunMpl515iFwyvMfXVGiEG5NB6ltYAYbAMqxYn1od77eSuu8ZMVvBUUWBhhmrPwZsSunG9fiU/vpePUNiTlWgH5KQcE24w0yN9crxUhUXyC/sPNto0JdOZqeUSPUreW5a0R2qW3UnT8if1nr6wau06XCIQq0PQPel3jFXNYrfKgb6JIbmE3eHVFvY6zO/0j
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
