---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgDE9LB3Q8tM2T6XZQbEqhAxkDT+fhPwUtIaU+ti+Pp5OcUk8qlQyQGUug5dTBBNETOiS/QNLk/tAmvJKhJFDHMD0phtcJfWNjvR2IGXDFSirPBGN6PjKMsG0uHJX/cbYDCMzRespoTT9OR+16QKpCxXg45Sv88ZVUmpWgIBjFzKfbnv2Xr8bBD55W07EReKJLd2XJAsFyFKkp7PTRKKipBwgFcLywrgwx20Sxm3j7FO+bLD4XSTrUE1hqnbsKiTvpeXAj1FEV3UcAmhRmirPc0tQ9TmKwTW810G8AzruJjX/bEfO0ItxhbEPcPMo9eu4IWLe3pd0exYCRHUehNa0Z2dyAnBAZMQsf7Yl7YdA3wsYDcUtjgQxhCaUCugIWeG9gnaUUi4Rs+a4kbpSNW5osTs57MTquaVBEkta9PMczZTT78v/DTwKSezKxr3hQbpVDbz70s4Xd74fq/oAwCXmQ3ZhWDdwkiy+Ip0C09PJwUxtrSuP5Pq5ZNpl3Og/YT7LmsyS4GwgEOE88co4sSEapYajtCNh8aKr17j3DjNVYzYXHMT+PSJ8xEVwyVHIeuIZwIPo7+dtes1e/PI0X0BxnS1V39leEVtX84M4QaA2wHnX31SgqI0CNtsjeAoaPLt2Dy4U8jM2OIa5a5d+64rF05IgxVyZA8yxwAoADXHmpE6lbvTO4eNyXXF/enqW8wsCRD+SxLKYAk9+lMxrlZpPOmma2Js2Zm15Yarr1P+XsfWePnIvtglvJLAxxF+Rkdc2efs869W9kuJ4s1B6L7rsdCBfJlU+mYe+KLuLNbLQcikAhgwHyu+/f8AKwds3VDCrDMWKLu8uExpSY2xkbt5RCEInj08
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
