---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: centralized-minio-users
  namespace: minio
spec:
  encryptedData:
    username1: AgCLADBUHl0vo0DmCupg14c3i0EmryUuea3ulGS+Gq6BdBqYmmeyaYdWAx90FLK+IN3Qu2OqoM2IpRCff14EvCKlOWdVCnaETvhUVCECeMmN/TSstz9ikpIJIx7WfuxHWDKkAxToZdfT1slTs68Y7GhNLm+s7PKzaaEoT8uJnRKjYg9gHx/aBzTUfo65aEa5ZosmWlbR78T4FkHhkoonbi3TW5a5NE1YzUJ6b8AlncwIcnDWxdwrVMzjKTmBRkq5XVFpXAhg13/bh1xNYu1okNlAo0CBx7YwnOszvqTheNfQ1ji+Bur66p9XZfSo/b1tF9ACABj7Kmyoc43uW7gCQ3osNXwZ+znoo6qXTkJ9MCriScM4BdxVZFr9VME8x2I+Tz/QzfPlJKveEoH31Y197gqUW4BY7MADW+5a9XEZi1veUota3Wveh6Gs5GQKEAbCD4NA/av/7xMjDRmgDtuweUrxYDVQeGKdHOVnZrOKIUsZx03o6x/nHjVHbxKK0AMvkHw+5BO3OlTY3IQOmUfyXbYl/HNO2b+QwG/LP50WPCRH2Tx3k2/fXQzfXoIPvQfycwjG0JDGoPMPRIlJlw5S6LhCKg8aKvck4LvsSbEy/VeYBd8oYTFa+prFT2Im6MAE7fKdbv06GCBmn2BtJ+3/Uln9C12Mny+jtdBo+4C0XXssaAGN9Dvy4VrDw4WFilFK6Vv26PuBBuyffHzmSLHEoE4fgBr4qZteDPJof/nsGtvFKh26ACTTG/78e1vMVmWxupmxSk75YksZ6RqUTCm8QcPWQnrK6I9uQd/mRLopJsYZQPddWt+XwSa9I+0GPmGcTdvnkCsNUrJ1zM1Fox5nnbYpCxJq
  template:
    metadata:
      creationTimestamp: null
      name: centralized-minio-users
      namespace: minio
