---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    root-password: AgCItrtk4rsqnWd4cuTocn5HnWS4IlizDvQViDedKhMafdWczFNiP6CNDZgIY5A1ryK6TgpgnZhHSt7jXQWubJ+FicBaPdDHEkFhTGTEoE6kEYxj+y+z+XP+Era3S8rrC9RzCg7zn/4jSutDTp6q4fl6IRuRhQEC6eKPF2L/TefTo+yqqR20o5mLq4nbwgjoy8eYZfB0E2x/UXpvW8MJ9qQziwx9n4FDJm1sZWZ6lHLiq+dnpAEAjN7R3OYAsSwgel0utGf2OmxtuQjP5Rfh4rCI4n9n0xfiD1pLrymqSdtqYFbFzqD2FTbT75gdrMH1Z1pSYzO8nntaW0ssQt2DutfofOaGLrxU5TDiOkttuBmMsP6rl2FWcm2zDPLEKKCcKbK+zvJp0aZLgkMpqydbsBIdUiUnwBMsnL0NHZ8mmDD4wd0/Vab9ZSKUegK33r4N3wkWc+8cfVl6Amb5f8Res9TFYfXVczt1CTgX4+TE+LShoJGJuuqdxV3dekfdbYMNpl6/saBkkL+bdJkbpuNS+7UIF4iUrgjsvTlBREelJ2L5tMkWL55WUYbRWoUVWGhrpvpcBalqJ861SC15StGNaTV4eeqQ/8TgurJkRhCcDQwei8VoJLxP0NO6sNwl5WDPw3OtkYEucadVTcMjDv0jt+Y0l6ici05sm0qo0BiGKq4eQaW2RMsfpUzkBOGrCA1qR2BoXGPSFQgmVsgV
    root-user: AgCPTKfbFWert8tz9dYQT+20ThfQ036b0f/z0ZYuwBlwx98vkSbanDYUM48VPG5KX83HjCiKxHLJqJ0u47VTvX5P8Iv79y/26X5lqt+pW/IchA0U98G/nWGkUUDSgB+3AYKG3vTdLrxwpakUaJ5oy6ed6rdK/h7gZDFM1IGtL5Hgh/b4dcw1SSNfUtTlcA+ZZBrrE3vPZLUowyesa4c9WVj0Nt3DHWmHwWP7Q5QQh08rnOmy1HSPd9kEq7PK80Fe/801OR3UOMPcctkjZ2U5QlUAbJc1AH8SIS8EDdVJ2TxSWBRnv0uVLi0mCqUblCphrOAoaxcIZ1qTEmwesNv7Zq9LaCVKNGVFHgKmXfiR542t7Dhf0Fx1Wx9N4UAeaK3oI39x637Qs4SDbpS/VCXZSh/eeBJR6qF7Bz4VcalRZCk6XBcwCbwWNZejd/2koe6JkHXQYDWYbseggFxEk1IdnyzcEXc6d+MRXX7dmd4TCzYId2JEf308ujE+Jfsyv3h9SKGHzHzGhAMekhOmpd6SXDAC/fkWp37YBUrxXcAaCkn2BrraZ5txKkIs4gkkfbqAYl5Napr6aDfs0esKLjj8QT6Vt1ymisHjTHTbyyToTqEeEYtNyogP70I+PYZ0frckQaLAFLzPNyg2HAMH6dhv82lqIN2Kjm1+jlceb6OqSd9hyI2Phx/zx5mA1lSDN6n5CQ0L38WHaqjbPi5k
  template:
    metadata:
      creationTimestamp: null
      name: minio-root
      namespace: minio
