---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: promtail-credentials
  namespace: promtail
spec:
  encryptedData:
    password: AgCpyHLyHXUZ6m5K/+dOGmMS+z8oP3k0frz4VszbxN7vqnuKRZ4Y0CRjDXjXGi9I34fgGGdksF1j/eUe6Qn1Xp/zHRN3RAwAiYvqFc29r7nTfNUaB3rCphgsqPlNe4LDMhg6VorSa9GnOvjFmX5SVmY0G4XTPj+M+SfEyEAVB/c289vnC5zSiu5KYTcVKMK3iBrG0OLXyJvNw2dRPi33g5GvNDNhufaNn9IwO1mHSBQVLRphX8p/xAmCAXTjZZsBk3O9EEP9Pe1oAvsK+qH7hF1V5S0tzpaY5dG8Qapp5huegAtQiLF1WeQ5mIGLp6MWjdIa/fKeIT7MlwismfGxPpPbP8H0dFUX+hVgYkjE5OD2mUZ2vxB/0CE0dGT970HSIz50hlP3ivwRxxSV3xaH1CpMFjZFk6bhUI8E9PhOkIVPVC1L3RaL7XuIlD2dnX4iBLYFKfFdwite/YJSYjJZl5BzcPGr8f8cR7L6jFR7TKj5A3AXfORF1VngOaPFRYFA1Yci3jst7nT+AzrZFg6oh0rwacXF+9oDTY37j26o58wQ0+qoVkG2gQHWdiGakwagic7dYD3EYKGnAMFPg0BODmnkuZKnzIdqvCh0KPOhameuHXDPR2YwxJFps5e9p+e0xhcWartinpuKcwEfSYTcA4jj59Kjs7vfYhbB2Khi77T7LRtgngRGtGdqf6rGDa1YWRmNiyqEVLzliNbwj/M8gqE7I8ZaYKQwvj8=
    username: AgCKHgjQ8lC0Hs3TtOtjzoHIvvpXDi7ySKXUBMVR/S5qQ6YfN7b8NucCbrI4Jq0FxKzpE5OAMlYnbvBOtmiN2+AfMscxdhUCeUaGg/77Vvxq0x3QiprDEP2PhTR5DxaGXjArlN57XunbfT6dQ0bWdWXXb7k5TC3YfHlgLrLX7dqxWX9c/s2B2vnqhi2oNDeZzCxWoexIqbrN/LkrUcOtNcMcJVxIPLF6PZgP5u04Z4aTxmp/sVceaK+YU5cWdbkP0g1w3/Qve3FeaXvoDRGR/kuorxxWDt8xA3X2OLXBLpgqEJzkVKQts82XPNnsDTgVXNzKuUBF34WCzDZGQC5gSCNA0Tg4eXBs8oxvBvtNqsbrhV/H6spio6QemQzhbUj+E7WCVNi9jjJSUmcmyuCL9DtTFnm2KZOrENbKaUSSK7yWk/6H2QaypW+DIX9LOMVbz2ltAJrNNTp4rs479NMfEIGIHPdeN7euh4lrou+bgc8PqZVHxxDQClN3UQeodzPhGVWV1qqq9kMafifvIvMtvcQAEBebgKQmwh7tIl534LlDvOS8QGC3E1siXBycwnJW9pf5bttcTz9Z+z2xuh/Bd/exOLIRDTx0IgK6xM34no/J4HyM+CbAqUkDPryMQjLsbTrIlMrM3gn4RFhlpNC5537oyGPKxxSaJa615j8oC7ZqbDCQqvj/5WQ+zkHtZDrMW68SJ+PRFU4onTmHPpI=
  template:
    metadata:
      creationTimestamp: null
      name: promtail-credentials
      namespace: promtail
