---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: promtail-credentials
  namespace: promtail
spec:
  encryptedData:
    password: AgCR6uRyY66Ya5uKNSiKIQ3H9/TSjTy9h9OtkVdZeBBc7ayn6/8ImMvRFptzkBIMRC9PUrlwJRUPXCQnc1/8aBrtMIa3SuRlzcdc9CX7FCsrU//KaFMVldroYWJYT08kXsFSSxshOfpm2imG1j9ItZ/pPlXpDcosibtWNHINY3WQPVKW45FWicJ4BL9Kt5buyx3J5I+t40JMLA0ftNi0LmAZw9nCaezM6/7Za3O8IkP+M3V/xEbaCi2n/eMXa5G2jHoZlPL5+MOCoQ/KPN3HPr1mtX099dGKm1851j5p3qTq75D6lKa3AKbuAN4EWyIFM8w/iwtSWmXJ6OsDmgMePQCR9eW9wvsCJjmvo2CI6lG8mgJi+7NCW0frrmqr0WolQHW2FuVXQmZ0SCjgPYAxVL3mld6x46NJjnWNKwAIXPBP8Bldv2altR+T4iqIFFwH7ZdX/m830a/ctBVxpauW6ams2rA//85L9TcPhHEknIm1+K+/xpv2MHBRfCMulUQ6gLeh9h4ypiC7MbzLSU3VZcchlL5G3lU7AXwvmzQdFsFEYLR52s8PndZeUErEIsKFVp6LtofrUWnc9oRRXMyBDo1OrYV7wochh7WA/8ymnB6UMQSz9k4qGz/msFId5fmRCtr/JrZaAnLKmfrNkkpKA++9B0/V2GNnR2GfVGkm/dJ3+7FSdVyuqPkjLTfbTe9PFHBI9n0pznn2Q5EK96GyNtcEmPAHXD8V4KQ=
    username: AgA7ae75Fl+4fLgKNj6QojeljRYy0nvxOxaLEx0gyMEqgHk4Q/WE+7y/s3Iv0xI0sW6gR4OkJnssNe59S7uAfBymAYqXI1/ruTZw1xNdnG+GU5GgWWJBPmjwz4zWfNBICpBJIqvbyUPyFkjBWqDZ5xkUKVovJg8Mj0l+qcq+uRoUlDMh8PfVgoIJYsazFKqc4TeEx+rRHOxQAz8IA+y7Vh3q6VlZDacAzLHYMixz+nETAR9PB/k56KhkPBCX2vdSmivN1cSuTn7IebWK+pVAq4tsjWxc98gC8+iH7864gM8ZIFUx+QqnntYrVSd8n2o//IPE6hwqJRpwtqsvOpehVkXthg5xN/Dv9LGuntI8MG1b28o6E0l7esbyE7V4CovyO0bmw/VUIzFCyJfREC7Cm7a1xD9/lfQAwRoqNHFOgI0Hejjypmeo+cJxvrjZ5EB4zzPcF9ZdVWf8XQt/ZpDwCB+udN99BUj8LncLgpUclK4BGwHlf3FXpQStGqWva9iRMslODZet8X+rzsqrOXD7hkf0EzE2TBNavFzj8qOPKW7I5C7cH/SAS/E2iSL20UoGDyHsnRgXCNlXFEO68xuvtV/L3dMHwkArbWm5RnH8pIfHv86nCbjtmdHTK1WiuwRypEZq3LG5LTuaznnnvBow6m8fLeOoXXzd6Pc1myqmcpZsSmw4keOMLJ3QIgItFTF+2zonCGL7c9sCmm50r3k=
  template:
    metadata:
      creationTimestamp: null
      name: promtail-credentials
      namespace: promtail
