nameOverride: "grafana"
fullnameOverride: "grafana"
envFromSecret: grafana-loki-tenants
envFromSecret: grafana-google-oauth
grafana:
  grafana.ini:
    users:
      viewers_can_edit: "False"
    server:
      root_url: https://grafana-dev.devopslaboratory.org
    auth.google:
      enabled: true
      allow_sign_up: true
      auto_login: false
      scopes: openid email profile https://www.googleapis.com/auth/cloud-identity.groups.readonly
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      api_url: https://openidconnect.googleapis.com/v1/userinfo
      allowed_domains: itomm.pl
      hosted_domain: itomm.pl
      use_pkce: false
      role_attribute_path: email=='tomasz.wostal@itomm.pl' && 'Admin' || 'Viewer'
      skip_org_role_sync: false
      allow_assign_grafana_admin: true
    auth:
      oauth_auto_login: true
    auth.basic:
      enabled: false
ingress:
  enabled: true
  ingressClassName: nginx
  annotations: 
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/hostname: grafana-dev.devopslaboratory.org
    external-dns.alpha.kubernetes.io/target: "448c33fd-ba88-462e-a9a4-19891a1a8623.cfargotunnel.com."
  path: /
  hosts:
    - 'grafana-dev.devopslaboratory.org'
