apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-google-oauth-client
  namespace: argocd
spec:
  encryptedData:
    client_id: AgAKQz/K+j9clmiWR2vnZ3ytfIPIKHhC9kNp1UHG3jcjTrtgBFy4EnPQfqLO6HgTGVpIevaCxhyphZhW1ORG+A+9xZH1iVWHifmTOA7jV/970JaIWsvqQsv1D+KQOtpSScjPvmpO+B8y6v7pjJ+Clo4G34jCMwyF6CAor1i6cmc3NViXvY+OM0nfT5EqrpE51LDnJzmdzX2ebd4ZxBFHBG2zaoft43bwuJ/s2z/6fySkeeAcJ4AgW4k2P2tmEBhFprVHrUg2H0ip8sVcHllW0Ixvu3rO73EyknjWwAszEdJXfJWAJPfJE97VqECZ7NmWHp0QnfLBVbY2rCbOgZNJ6Hkea37wYivARuhVXouGq5ROojQ2zmQnS9mpj0RWFjpoq6Fj0T60Sxu5mtkqlIbPlG5y9dh1LVBuITZWUOGrCm1+g/0HdvLb/V4VSWGamb+Puv7rt5myOuE0ucmKQrqf5CRxGnB6m34WPZHOlUG8SnbpgQnL6YjIXs69R+WGtM6i19kyfn6rREXk++gGrkOAh3k9TgQjwSMB50EBNLY4ShgkubKbuu+4O9MLsSaWaKa/mlUBjzSGF0SZBuY6hYKTsduMqdF76CWJPIIpZX6cQ4ib8DvsnT25gstQedftX94doxuMyFN8PY2aUFDkykKrtmF6XyeGpqkKeRZvkmEib/wvlkQp2WVLD4LvHkW3yDDWkc1jxmxTCq96hWfVVcO02XX45atxT/la4JOoil7Cnz07Y+EBclpaGoHGAQsCMHQzmQhjtFAmCmxuBGYcMopU4RLQZBDeQntie+Y=
    client_secret: AgCLo8hX7nkMIPo+Y4xMCT16Bg7NgHCLDStiADxRVAyP3JpNL2qFnKXA+L4ePr94iSFlEJH/vI8tH0+lEqScaCAGaBMk2HHubbJD9WeUSXJVLQNnXFrawStJRjhp4DmyVSd4tSC+vJVrXiqdpM+39aSS3e6xtc4xKuRdS7ocA9PRpbGETMLig6s8e+1QmE+4SzwrI/Axv55axl7L5+eUfSesPqwAYMGlJSYQ9CRqkY7nNCgF9qSHx1AxpHAnhsvm4yQ333ar9k1o6bJLYGS9q/lHWZdxR6hvfdNQRCnrW4T27JnK/jc/YovEimn8t/Yk10TIjwtOnUOTADe0vbL4HKALgDbYRZ8CGjbnkeu7sOTixagrtdUQJFQpKHtxrHxeaGhJJAJ1W1MeruBbQrLg2x7O27LZ0YQR+bX0Mmvkm7jgyqw+e3+8UGXntcPrUCPwdqBqL5mk+NwTs0IXcx6xA4ifw7MTkxAuzIaRHEa9godZhgceLFRalmh6BUVS+f47EmaxlSdccwdoNV6XjmO8Q6fgdmmQELoniPqH/hntKXWwgQC0D9xMzzXT4hOI6SBb26yMPS4oxVzJpYAegxYRLEuKJgBOxQseztIj2fqIj1ElH1CzPoGsc/a26tiJTHDJ8BG+mu5+PHzrdQKUKeXFgK9ban5odW0sOtkEYAJMn30TKS7ouKUPkwO2xYqC1Qc+Z5VNCzLvf0kcsg0ui31dhfqZDC7AP3mFaSatEIFhtW1gHBKe9A==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-google-oauth-client
      namespace: argocd
