---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-loki-tenants
  namespace: grafana
spec:
  encryptedData:
    LOKI_TENANT_1_ID: AgAGQRkjpYCpB2ZXowAxQqZVa6ZhPrNxV1W++nbB3WUryHWszTg6mC4iBiNqlLWwGcr2MnaYgisw+1LJ8ZlyNwC6c8AZZeZJmXD6idrY0pEoVhS6cAf1W2+2Dj6Hi4QGWpwjPiqhMRKBqSdLobVUEuStsy7e5FA0ErYqQ0wbZwwPLmyHKQTXwhCmXq6jlelLPpwaTTfQpWZt5e+bXwsi7eM5hXIvT8Sem2ulo//SJWtMRJgXFiHq9G37ByCzcNkbjaNx8USgBNsk7RB00NT9JqW6tztyxvL4lX+OnIwdF7+fNJAKhjHQe9idoQJArp1OLoHoW2VvPmQJ0deVczrFmyg55hNpbdpf8BK3g/+Ah1LkRyt7BAvaxXEo4g/Tv1rrsQKIF1x27P/D0x3CA5q5IO+c21IFKBiLH4vVGiyhbf84i7zRX5RYk5MzQ+8ump7hOIb0szPgZfcZAlpKtrbKMQw3RUTBHFYm635RxCUxoAkzjqy8VkkRqv9IsT5IcIIfHGZh4NnbYXlO9VlBrTKBifKkjNuv33uECB0Bzqa/INH5SMVjrOCHUW6BNVPfO1uCqKNZdvpFFjeKWP65fmSy4ymkdSL7iGrLr8VfhwMo7INgFLjUNa8Ynh89g+DGGO5t3oCnrzS9H8nEhl/EJWyNFLIP17fStiUiFfxkS1SW+uKh3TiAj9APl4KjpKjnzy/Tcu3pgGg=
    LOKI_TENANT_2_ID: AgDKd5YppdTdY60ILExogn12du2cdRLQjTbYsCfxUShlS9j+QVAYQEk49KfsvI/LKAEAm1tiBhtgM5ONHlT4CttCyJkV5jElY9weFJIG9ue1HfcWd0yjQcxOMF49JXWruZWF3LzvOaUdKWqIzV7+b7WmOLafP8PUSRpipi75t4I11tkhzvP5VRfC6KOHxWH5q9LL9L3Q86FQ6fbDKXj+MvhH6t0vfVAsS5lcu+1Rm14JRt1TQAvs1PhJ4XupJmvdFhOcystiMIx20aq69yBXDzVAOk90ZWCxDw8th7wJORKWnROrCh7huxIG5XxAHGydH/HseOk3qfqbvHAvewNdtnUNR7N148dLsaKjB7OhUb4nHEohbC+Eu90ey/UQ1dkjeY1iD2hNlhMiL5vHhaFWtlJcAp/wKmfIXh1UxX/kvFzC1PxdWiYvU9ozzosfP6eWk4Q/gwPifRdbeonn4X0gJUO1tpS2BpzTviYL0UxA558rQWE8UVr/Uh5DHN4w1Az7PJcY4+o7rOeRKFoAJYLjVOOZfFZeG8H9c/3qDfEl7hSUqx7KbJGZnfmksXpu7rZl3oz7eopUF/Ag7eHJq7hsDQWyoY/ePgGIxPXonvRK9usrtPD7pOl2E2zRd86b3URibwd9bJCzo8OJvoWf3mTasdnP75MlZ7ZXu4YBiSsHAmHwfwjW8bQvL0Y23IlAUJ10NE88sIsg
  template:
    metadata:
      creationTimestamp: null
      name: grafana-loki-tenants
      namespace: grafana
