---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgAvUIqd9IDSi7YZNNjVOSHiY6RvA1N0ig5voN4O+BPdO0H6usRRXEW2jSettKoYhMOQGHBar2WhfvaY0dI1c+LWhPhs5auJ4V9wHKoPsMbbvngbOASut73DWjyesEEg6sSdu6Eg/HKVJWyZ/G41y1bW3X1YfSE6cCymUUc/4gW+oAIf1p+C8Uu6GLBYLKI4yF/l4Nv2AFEBDaUqzfwwwx3UczAiCQQpbedgG3HqDI/4EpjUsEH7ATzQBcAPlVMSA0MidWmULXCEJ0dHgt5DZCDwjvCkSrwxC7PCD8sk0An7dTuELpvIBnR6a4Zrd9z2abDm5SCL6E+VElbZ60j6QBuZMvJ4dqm6mlnyf5t1jijLASGo7W5+wWliPZwfsEzMiCbPvZqfLKG/c+rCyhdae+2H5W/QYRbcN49tV+AX4WVM0Urooy0o1uFTODUIzcIj5RtiB2/EF+3iJIiZBkzrUCMEtA5Cx/H+rggYyYG3MPxVOE2iHCl2I/BXEmahNt4S0gPcygznUXVwhtZCUjanSNTMIV5Vuo0L23hcMK0FNQgIW6Z2PvfM4pmUmEI6cdr2tnEVkEOQ4adHub4Q4YM+c0TiAorr/L8884VzOuG6upszCpJH0nvNbV6/UuovyWyx6SnZ3LgWBS49D80q+0YLMfe1EtSdSHzHGYHsroza791kksfwVakQVWxDmZyrnMzudC4WPi4NOJzl+8w=
    secretkey: AgA6y2UDZ/Nd8Cp2oAKnqOX3go5moCgrgEhQ1rdbVeXCFV4H8jrC6YNS67+rvMG5w8uGiuz51DwiHiw9lV4MXid6CsUsZBuYly1Pm9y/d1invnqL+ruy53z4F78gkfRbQU/rzVVs5wjHu+HBum//ByIdjgDHchEzSJiz6uHFemAS/SH+ulZI6/J8kpKesigDwZmcanLdOk7tX20KgZfJkGP7aMeIbL1A0lTiu3myhf4lgLHq5JHS/n4pOsY3WCzqfhXkRe1P+wFUlPh0FlUvSzoSp7lclWxW+bmAMaWmnIvfmAqF2nSq74z8Qwj9omgE3PmKTH6T+e4CLQdFs2bybaQzcbGJqvqcAn4P6vwUa3LVKz/rnltrt5fzAEzlBWHd5c3nbx13/At3nCcjZ6O+/Tjx1LPOduZM1istuOhtPi6khmE22Zi9IFM2WqXq0WDpRM0SD17l+bBkytE8cYJ+Kcqa8+blOjiQ2d9LTLI2gtzn5RyAk8WT1Xoj22WLTUsK8BdIKE5n+cIGFiWARG2VgU2ngRHObvxEY4Gu5RQ5jD6v0amgjNJzgSqmg+cj5OEEIhoN4S9OQzehZ1TYI3Zgu2xxL2LFVETV0fwrBLsZp4ouC3l2J4uB2B7wSBWFQ0jiOQzAabL1Hd0NXeiKx8MIbE779hZjdwZqqNrB373eCBS56l7kT9Ey1HPXF2+k6aIOqM8kx+d2HqbDTAg=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
