---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgA3K0PZycbbhzHvM41ly76KPqJP5kEiR2Q1gVt9hDm9QBnyNsBzCddUShRKBhEr2UCuS9Hw4Caqy9yv88Qty1yrlZdhhNJrOT+QgfVOSKl0ih1S6KQ/ONTnP4j0OrizPlf6n2bC4m69bFCrDLLNuNTUBuzlX7K1ZMrWJX6qh+1vluc5EQVE4MgMGMI4s0Oo9xzl2RoaD053+/e9FE820tLxvzoDLpeXoQkAge9X3MNTmYkArUrVTMGIe6DnwZOJJrP06T4YwgUAAw6xRhGBWGvUwQcnGIvl8hh6e3z6EfCLAdjDF/uiDqRMgSgDBeuRkcIMhob7adgaaX7V0Xm1k5+r/i+vtN+rOlRK7W6Q+o4biqxasrNw3pawGOHDGimT1fTnx7kac5CROkWP1QBUmAkTPf4VprLzt5/SkXvOZ5tlxihM1mNDlFdRXzG0Z4cdKHjLnAhVVNitCWbAcsbHWm8Dx0ZRxSUCjnA2QnBvhpXtkPi26y7BlG4vMwHT3g5fCW33gzO1++KiwpEeX/797MaLxze9gxW2UO9Sf8lwKz4hrgi5Yme75sZS6CjIqWOe3mU2/U6yY8Fr5iu5XTCeoD+DYPYedW/wvONdXlWBi/26YqwF3NPtSjzfk2SOKQ3medoOgmEmE1wT/2rQ6/FnsW00SxvxpziN1bUaYjqq2TY6va+YD7sB+nVWGjfHg5kHThTc+Lbzv4tVWB0=
    secretkey: AgAmYadq0+gurff2pTO+egclJ1CFOCj2pat4BLsjmljztDiI/7MiTY+V9S2ShltUDtu75pfpnMqvDlTW6ckDld9k7UBzo/aCRveg7Orj+JwuFjU+nS4GOXHHW0kytfDocfSrMjzvjnS0dd6uhvA4DynBraOs6+nL6Gv5upaUe3eKQUaMQyfZvF/Gm+epP8StubLck/oP+1/1/I2XTH5HhjyIMGwUfvaMHG+Zwk2Je3u9QmGMKmfkjH/jNagBwscNMLwXKQY5UDB/XrHSKFukyJJPtqRBN4grZG4ozNkqxdFeUudZjna4MzzcbJoo/Yta7xx40ejXBN/WTGIvkuTetCWtv5PiWJpQlTMV1qlvW32YKPtdck/27gsqXc0sMU/Zhp2k795KDjvKMBaxxNWmQqPK/c+0I0HBrYqKYuIQjQdgg+fv1c607AIvs2WrVrK8FofAO74b+HDdxLxm/wVO6nXw4L+R6MpVR73Kk/DNPowijjUbHeWEgWYie39Mv55vhsVk2Rek7mNMneonbp2qqhS5Cy1WAoHnKbfIWgxOLSQ2mVXLKrTM2wJx1ECf697mABWyKejfqKV3S5RTfu4vAXOSKxKOXIerDvONpO3JjLxnkCjLlfC+0PTbvAadf1w45GMsjmwXCBU9t/gdonuwkL6wd2bN70Kg8pdtTmmjqxU8d5HI8qPqZ8q+C8hgXeHu1FkIrQuF9KO2uQM=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
