---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgBY38kvuKWKu2w/KZJVWGJEY8h0xI0ymDSQO0cQH1OVlXI+mxz3kTcfcZCT7KLS5ocOqstfqBN2Ci0s2skR/7W0MxQrgduYMk78wTYvP4/q0E356VjxPZCdCedIL8WUP/APsHqmAKpVLCuLtw5c3aLe1BgY4m0OAj/v1fEpxVg7tFu7p/7tv/z1XjTO3USN1mpv7kxVNVVfoGaaItrTUmysFF2IoYWrBGVHOuDWsOX2t6m3zJ4lh1aS2Ey1OmI1vGKTexqp5hkFqpd1oBWPZx9E2KS3rpo40cEIA432NhYFGWwd2buLgTAUnXT79Li3JERjrcNiYUkB/uyrPrggRKa3cB5VF2AVks/9WsADU4KecdwkckB12UKYhHTx6WXaIqMSdT9y3kYajxJnD7xVUBFICjZkMQvN29zHZW2X+GYEZRmOT6QEBJ4OWFd6Gnc9WUQ3ObjGn2lwOpi9hUsuAZiP5jRGBTGPX8wkM0bTDx+s0Gd62Zpx3hmEnQDCybO4FTH2PgDcrClL0n/Ny5rSUNkwkLaVHJadMQX4DksG6SxKTef3lTQ2Ao3XcVrCxvswyHTM6BYHOzWyHHLv3faerBC92Th8XLtD8L8LzsSJCBvgT2cyQI0OxPVzWjLbYgOY3fo2S1uOkMU+iTnMACihbXtjn3/gt8UjojTKlx+Bb4Rj+XZhcXW8gBhk8SYvOrbLYW1g72GoE/wgkFo=
    secretkey: AgBAZH1eFKl+YC5o2pETBgN23dHWMgsywd9bDCrCmAJuhhezV/nrgE8CAepwGpzhgY8LuCybX37uzsxEI8WFt9tyxkRyBPudy800OS8hDyMzFSfNg9bhH8DXrqIwa1we5us4r95lQ3WJ1P6R4NqWRB9zku+sv5F4U6tjGGDCFCd7q6TgYoveHwK/su+sXOO2xY00/izENRaQhkpd8rayjohQ0hMnwh2R+5FWqGN6R8/ymjz2mXzIHViIZzEF/1/zG2S581zxukQwW3yBTcCgIENefc8cQp6knNH5+mHPJLOZ6u/zgzyRgvJZmi+n9FHDv2urJqDDP/nnzfec2hEaJiu4ZTCCBA07G3KBZmuFOvav5TC2861DDtwdeem3MgDPTsY9oy7ooGdLCDknUrKNhgwX1/UGNGjXinQy9eOSgvzw8cNGXHycZfshl8sB/LyBxFwd9HdqiipqvDOrgVgBuU0bRuEzZldNpO69faHIl23F5UU7lvX9wSS2crD2PIlc1mGexQr8CWnMzBWNBhyR5mQr1gq8sMt8FS4XfL2d9klOoYmSbKi7uD4kw7QAUWZmweAUhpYiakFjTfYvagxyTgzkiqRhJi+z/Ef7Ok+OR3C++Jf/TTHIcnTZTD8iPAj+Sjyv/1aetJdXVWQO1wPlbbBvWNO3qlCLes9kzkvch+C1vjKhntwMguHykwYbVn3roM2XVmCq2jaDRBM=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
