---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgAKXA9C7KJ1nN3pfLkEQTzzWtYqwS3s7NW4krVWUZGKAqozYDNl0XZ0FJmGh/hDJfRPhhtfWVZ1kDV4rRsXhLLGg2qD/7RDdswuHS+ggU1EkcpzA9LEzGm0iNcOgF/ckSlb5z07wUFBmVWkjoTqKhTqZesC+l5kGMxMm8JXsg+gORZv2KR1SvqYAP6wCSdkfhmC3/Vwu8Cw1uE9f/gTK3AdZepn/X+4AoKjsuxhtjxt5UxNcMxbWD9qwEyYzqxR+clc6jhcxD1DaZivfUjDro9ZqL28RAJs03tmp/nUHwtCC5rk93nlUaok8s0Zce8gLiiKMsD2gk41aSKX29fF4L7390XMV9uTeYmnYVB9wa5lxE/sfXNjGodaFNlakXBwsxYKxQpR7zceR7YeCrbnCchcUHtGLSqHLNXURl4csnyNimkHiZlc2ThfAJ0HsjUnSbjNfK2IjECirjfNwtjpkIi/5hVNsm+tuDy/vv6BXfBJyXns8aFfp79v+m5BNsBNsz0k6AD0HZeCjl+oeI5FcF8jKV5ELeQt6kz2dDz/WkahTeWB4GTQP2K4aKr3nMZFuplfxA/PqqOa2oTSUFapixmCilq6Jq57ZsqkT664C3WJAOJ5yTgzmTraNeQGU+1gZTPvi1qVEPJ5bZdj5J8VwNYkLfFGTVdhWWo7AGw/53OuEkFXJXRWVnkSphdjD6Rxbrt9pZ+4pLsKYSY=
    secretkey: AgA5eY2CPMWfhbeHMOzDmnKA1pTHVjz97DYIusvnDJUpgTXrowPBbHJSioqtm+obSs7I8zcavad0/KsnSbcaLGlvbr8hwNmhGV7ta5WE1grxiUhQ9U+Q0S8culQVKgjFUFo4ipMTaHR1I1NcPe1yUEGhb8ycYxi1zRsXc9Wp3q/aw0+hnlPNLp/4fVIuZw81QnDtRfdSqfwwH5EgHxFvsb1mhS4p0vBaVa0k6+lHdd8u3mvoUOAULFBfGP1wwWATtHKeAcLfJI4zhKLpUcJo4a6cUJADFM42UHNHqyiMViPrp0vkZWKftxaFef21cMiXtLhytWSUcYfsdrpO6/trzhXhnIkL5zrnixxj3Puy43bx1RcolrNPojwlayQgWoghijqqdxDSH8yTcS0yjfhrx/0Ni0nZjx8R6Pxzmi3bfv3ZUSp24mrMTkK3phy9gmNa9nuwSkrDdzIymGN1Fj4fnc5Ii36EaECIDX0yYS4wSaZffBAYbpUNiQGzcfw8LQTIYi0+2fdhsUoZDFg3iQBgYS+O42eP+0bJ/I3lNuL7cyQChftBhNyrxjPnOS0LxqDLfVJRkDde0r9tXzp7hwausDe8U9tn2a4iIarA4ZP8fBqpfG1giUTUaYJS7MjHeCuQMH3/U/n3qx/p18Ym9P6nIyXytmXGBxR6D3kePoB2XutsMmFrTIAJWm18nsobZlO0dcaIWZEayG7hkIk=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
