---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgAI6BRB6ycA9WE0CiZ7cYZdNuDo+mgXlGCpwKVnbRrGFYA+93VndcGFWfFZUahKM37p+51KDy6SZh88IqN4TQlESS3CfvnKFmaUxRvnCHhrNW/uQl05cIyVrriiQ18XDAsaSsZPJkSolM4qIxpPWEniQJT4DZ5E4zdATTnsg/KR2T+YGV97FMynzHpT4GHES4cCU5vh8IJkPtjA5WxIkUvHvJh6m/xIdsJElEUzXJSy12qdvXb+VzGVeUa/gnswgOn3R1qUGFXinL6YAIsRCNWKY9XWMrnu6a1jFiNbq3OUv/ppOIkKvLBbjKsXLLYRfL5NapJ2FcFmZ9GRjyYT+QbLusYL0t+QRkgV5xy0AjeR1j5TSOFu28cfQfqhssfU1fztyj78QQT+ddD4NYd3CY3lYgrAB3AVBS2oi+oY+Kf7D13UJrbhHThwcR1hKdT736b2nzcSCpXpW060SVJ8C1gt9jhPEfyLZHTC+mUfdbhEHd+djbyc1dCWW7N9/poTPtRlRc5xfEKwCrU1ySyDOUubD2kMwyfd6hYkxnhjBunbUNUlPD8THD8yF/5mYPKyikXl47QvsSn0LHzMFqsSjolvT/98hEs0UAjCx1KOcltIalw8R6Edo8p8PocRpOnZ8WSNQgAPJ/BqIBfRnqnR5irXyvuWHePdDQanbyBMVbAbwLgwtxh+6qbewEm+o9y9wzq8r05iTyJgZHQ=
    secretkey: AgBNcqafQ6BIjVIgsre/bfnPljgBIGrc04V7kxA1TV3l6rQCs6prYUxMImnVhSAqVRMPn44r58VbzrLBlz5cVbgcgj0+1kJbEw8RM3ReVMXYlQIeSzHByNNGgXjy/pQjUZ/T5u3H8xjTwhZTk/SzvKKYZdGnXEhhsEJU0AWcAji9DsR2amSORLH2zLwlH7kHOAmVHgwgwxaiqfpcMWpz9F7PMCbWEGlTXSfpT9x24gohRElFSVCZexTutnRF4HG1/ddU4r5brS4rdPVcz9w2O9VwwQIEeSH/vmhPXgNWsPvUtcw/CPaM+UMnMW5Wg8pag1dSZDWacoS/+lBJyc4X7EPOHneQqMl5CC9YaG06sWi++2/lTo9VUEC3ONkLL1KbZi60GAy2kus4/ieUO3V8PqobiTAa9+KSRi/imIIHtVQzUQ4Wg8ueq7kwAogYE1shlywKBdZ/VvkCt4wHvAIq2SQOz0rIpzEZbvsuQanAiR8IKY+9UDvD3IiuqlMwK+cGtQTEiy8mdx3jqYy57ZeG5BgFwTn1SEmWiBFEZ1fc1tulfTVzUSfvD1qVKIjabH5tcCNcY9cEPZqc3s2eakGun7TUOmYPeW1voNeC2YrvHKHg1lKhJ7zyKxRQhGPfei8+pqK+wk2knLAfifYmfBRTc2CpCuaZaCDBk5IEDngl/SFEMI0riu2ISw6xmQ/MZE6NB4OTW2LjB3kJazU=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
