---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgBqaDvOyjtFGMPb+YBY1Ryi0fSWT4WrsgxbB+8mzhyHCCUyFYhCYg3A7DYafeE//EO7yub4oHvBKHvmyJLbJSRh64IdEOHb37dWWOV3BfdJFutPR1qFDnqat4IZRfuo0S7k3J/N0aXGc2B9GblTehyom6BPx29uMs6uBDrzg9TpSe0s0yPABB0mow616N9X7aBFRkK0M/KXZjTKYPYuIBP0dIUZLoM7giRr1Eaf0bSryW4gc21PwXlatXgz9XE9POB4VmLetC5QCCpzjJGLpgceScED7IJphwlcVMqho/4XVHbI1Mpe8RQ0KMHwFmJsXWJjH4NiIJlMmhAquQUMj5YapqISyp4d0II0qLgHMJGu1xzQsnKs8f9mzfnF2r8OAhxrlUmVZtu5lVQP5leFGzqjGv90+CZB9eGxfVIlpyqLp1DQtmvX8x4YcaFxcDWb/efMOYGfeW39ay8/E7qgVExP1V8hwiHMCNA1BhTtb1KsMLB0EByA5VxGXmyvIF6hCc1gt9C0Dh/hlCS9xkleQxjl73EPef7iISJEHwgOdH+kAhIfBkkZmG9lXKXIiUU5uKwsYsg4ZAymzGmndEzyPQkNjcYlzOHVGv6UvR7pJE3Pcilbeezv2MXBZ0DI2mXZDx0WoE4oyAX2jvaGu9IFltglBHSdnUxX3XtZhbIhWlZtQw5FbgBv1yEH55PyAd3NPCdCrB+FVtRJ/vY=
    secretkey: AgAHF7mYhbrgcT6d+97HAWSaTtE6XtDO+UOYibXmS7y0jpeZUm4WgtP7GhPCt8DJfINP5BnPcxZsuoAXQjpqpHMhbLMNTQ4TvTLaUM2XeIhenG/hNco4z5XLvPL4h+zfQyMTXkDwSj9vVS33aMRrtpbJZ0cj8DPu6NMnIo9lmJ13/df3g4HNLsdFA+0hOX1aGoLIPXXpEkcG7RMJiCk5nPJTS9mfO1xziLV6SNpkPyCVC0VIuWlERE2L//OEhrmkU66PJEyR5V5do/HODLZLHVfCD8QAbQ7BjUyXhir4zvSzBMP5X7ftQH2ZHWw3ekdxEbcjxQOQoeY6WP8QRF7WGrJQKDu9v6kbZIZZlIa9G2nAcup3LRHrdOBJI+FWbgDUfOgU4W6biP7c2hIfi+BMbxASCAAgXuWe68an6j474gxxPAgoAXL5Q7LxwSMAPr9YH4QW5YdVD6bNN1jIdxYuCfp2jys4Wzlj7Mw4WvbOov9DJd32WhHrnglqK36Pi5UkeUqfh+34A3x6BKhEdOCE9U0Ows4sCngK1FlWuN3j/6M+Q0yqWBBpJctaTU6bEr8uDqBXbgbo/oSyzxGv3F/3fWlj6QIuZrbvJAf2WoctxTtLBw6/yk5MlMMAC2CqrrYKG80JpAT7kiD2Z0NEMEyh6o7J863l8Rvm65S+SowU4FTL4TM8Jdw4W3HpXQRzh1JHtAuakJwakwglcG0=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
