---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgAty7kEL9LTXKijMkcxwpY2C+OeFk/2bFYeduyV3FIw4JT0/koa9y3Ey6zhyLEvBW6xe41Z/2oVHbta50Lr91FXqfdIm+oiUDz1GqRJ9Q2xbDWYFdcxXyq8z45we6RHb6O+C/Md1J56Zfcn5OxmF6Jj9Zij7GUNxhepUMvshX3/GxM0ml7HTLPqEcZVizdKFKyrSqUaZA8SbCpWtyfOem6Pg9tk14WM2QI43dStlkaIaD9mszr00Yt9RnaV503fxWKqFs/jJYehuCznk2Efjag+1bkZ8E8irZONDg12ZZ4ZUoQvWy3GVGzFq4N//zcXzvn/0Ym4sTnmq/0J+sm5bsp4NozgAIQP2WYGYOcPbKY8fWRBPhBptF07GYSaEu0Sbp74W1JfsyfmE7H1g0ckeo1YTDKpPKPaR48hkZ9CONgG9Y4dg5WBOsUiUQ3egduh7aI9hmxpa/fyyNFZQgqYBNwvTfbmjGWlLwBr2W0JffkMpK9Da90HbvEurSmbLH47oQ9f0xXJe3Z3Vms/rrGaZ+AH+/R6GByXNMmXnc6KR/gVAczzVrcS3o4XIq7WuCHTmHF4c7Bu41zYZFVgEs4e+rwTclbnUgUCV1vvDttMxFobUCYmUwKQtY2h0DImOShT/d2Ke8ipw+bS3yVpNpA/kfOBNmwM59tVh81RhjsTOx5lyRd8FMe/WDYmSHdsCC7bHyTmijYQfBvovJ8=
    secretkey: AgBHGAky0rOG84PNoQ8jziRptTJ94AvBvBn1+eDyVd+YY/drjRgW6Lj8L9sGEYNn4tqj3xCf+Gu3hcR8XtozzhlJrDueX0t1N7Vs9qdX/4TJvD09cAA6Hq3XWjozaOrq66DVE41euysYtcZbDTAY45kVWVlF9z4oYNCkQQxwKDuzaOlazxbz4ywKT67QQn4mFwRGvHSeyjvspepEgtyK4nxfY1F93g6/Z//SoCRY602lnkwpTloYQ2DfZke9z71iBBcFlTmhZ40VpVYJX0qdi/Le1pomPj5yIy4GGe69B0sxqTb3YRA1EoKnQuuvoF7+Bc2pQ/eUwksAwQT9uUhyNUPwyUVWYDhBDwRWxBXUGmIyLeg3pCll9v7yS0JBFBBu6TYS9+KrcyDPTRWdKQdC0Vtg5LjxBNWhKRp4F4cwAHJakvPuDXugwPaKKrb+iOrzMlgOK7yDl4RTp9QFDX3CB0D/KvRJEEMj1djJxJxEMVzKZTYtS3Lre8CRgDCqv6iq4xp8Jy6OD8bYryEG+7FY/nw/kN65qNG4dhHRbmk0DMkMDBntpBYn18nPl8WeXxN41UURcbZ9ZZGUeQRtIKxgzbUYxr/Dk9AcrWcysT8Gb3Ev6yH3X+vHZEGxTvyHf14NYSa/XNmsRLjJMD0/rpfzWxVhCBKz3WyD+apfTo66t85J6Vaw4d4kpIuE7NX0Jfkj32t9KgxAGlnx0tg=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
