---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgAYSUhPOUeZFJUji97oC7RgpFps0zngPwZkELkNY7fxoyOztMGWfGDgqobMnDzvUV1jbRm6GZFxLeXyrOr+ENDySORETptF0fUYT0lPbgTnT3NAfGP511lCsoOgehuH97mPSMf1okVQ6L71PS52m2gsmqmMovLHO+RT2u4d9bfp5/LVCvozHh7rzfOCJQKMv/bgPwwvwSS9Pb7TBFmNK85/FrQefWrOCSczAYJRQnNPfFyTPU4WjdJmJC5kLMvNqSg94z46vRrn0E9V39BCB+S2ygiDcp96+h9wXQCOWXxcq8Uyy+ubqlIGbbSjPFgHZBZO03SMSZjnZw8iFuHe766rPOvhwaNJYbLKTgsRe2mXFzKo+0N8hMelfgqT0JtBdY8zb0U9PGePBZ2SRUUr0QMrZUTyUrFlT/sTeyWYgR8SXz8PmJfrzeXgFHAzvcjFiZfl7cBmQB9Xo39T3YC4kuUBchn6OVyQF+A+Qg0Kl3kD2M5dXNvpUrUAgaE01dJz5NGqgLD9CIAa/6WTW+WEqj4x3LsBkAuX9GdG4MZhq1j84eeufqzUiDYBNzNknlUnedXADWi4i2MqBiThqm6nqQjv6yCueu/21wFcacchbd3/AXFbItABod0ykGuV3HiXCbZVB49iuXpBETeq9MBaZyT0HyiCPqFaSHlVAmhIxKEhKyafx+JFOzwxTrj06KWYVOdhCBJV0Oe0lo4=
    secretkey: AgCB81TGxd1k2wJz1345SF5skdJloQpcU12WdygU9QdphQ4x/F/umlxfEft7KQp0aXictjxYT2OMAJBAR09blEIuGcebrcNqnJ2MPhmo4PG9uZ3SjvhT9cODxKiBEKoDWx/07lFWTiq+1qgmvwsb+X2JlHTckOh+oiJUWNvA9TcXdo83cZNXXnV/yhXK6d7ykQYe/uvJEJeI/Rd6JBKjc24T9ATtHxPKlkqzIXnzlkYpIq6yGTIxGxmfH5Ky/IQ6OkswD+DMTQxKjQj0WCHnhaBBEcdbD9tfdNxyCp7zY2mTPb66efvyHEuyXTNBhojqGB9wRIrqYslMKQkHMDh2KMTEo6FXW5OZvuhgaLlNIwbEiRE3Gwl7zz6o0DbdTJjQkuTlogkJqGKF4uYl3m5jqsyyjdeP3Ipa1rOB8eFbuasaPxuLst2SI1u3H+U/Vw6YBff0TryBt/MsIEMfKFdXFeMIqjQr3FDIlgG4qeFdr6fbi5WVaayOONW6Ag3iwoBhePqIO6X28S+X3LQvpmqlMrkmNMppks0vGY5rRvGTcV0QQDqmOKg8tipgWmmXphG3Isj/NpZV1bro9D+LcaB6HVYz3JSiDC5EdXh5X5N+GZt/45Ka0VTmT/XKgzGbr9Yi7rdgbbfGPSaDlPb62svgmmt9foxb3k84+c7h2BWkd4UPS545DcCndUpbzz1RV2fx6uvSti4fNi1dFrQ=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
