---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgBXpB/C9ZALwIduDHt/sF2Y5EuKyxoP+JKeEOc7490NnLacFx1GtSQzvEQC5oK2OAdD0K8XIJdytUSITVODlolvk7ruDTSwHjTU6KpOOOdotn0qW8KeZAmiB7cvFEwFAv2nwjNBdYoyHQqk3H5k+9y3sHt3jv4YA2Ljm1nuMY8cxlaFFdYf/AVnZdHEs+w0ifCTvZb+nqT9bQFW7OwdOGZuUljHc8dixL42qTTUL7HBA6J+4WlxcFr03d7HsNDsfwffbh15m+5OCtPrOt+lf73xuAYPuT53m0sLvAPtwmkoqivB/Zxp1OYB727NJqQAEGHvWHUWQtO7w81haxxDJ11sJoacRN/mckPxjN2lXwUbUpJGGweahUFGOSblVW3sZq2jJ9zw8f57z0r523LAqgX/Ppq2AKf6/hQGxanXTyUJ+EcQe0FmEX1r/tE1X6dIA6zgQ6cSdLbC3xxaOQrJmVRJxDiUkXnmRci4hFQWcSmB6onIWQjj1yJEt3BcQs88ABiPZFlS1+reFUMaE4c8mecKNW8C8TvVTAdsaQ8cqcbJbMLGqZL4WgaDUmaEavUueMDgr6gWcIpdpdr+c5N8sSZvcR7tY1SEVJ7TQnlPEsQMOkIXRBAFhf7T5uQ211D08ozuEip5thKXWKizpAwAyCQs+yf6uH+3/7wt0aTcYO7JBKBqpaPVDjRBzCbw04fPCiHY+0leXOA7mSM=
    secretkey: AgDMf8bL9MEihJnDicvLQudHetumCDvTaKJnJagSyLIo2Zt8x0RUDmwxbwYIL7FBGuREgHhgw1tNQDeG4WpzY6ht742SlZxsgRNoS1D37+pgPMZ3wXfDpvblSNPk14p1rGj3l40bqCcnlmcIM/Rtvf0ZaBogsldY+c6RtcgVeif8HCQD3S/uCjDQTR+RSho7K13H7eS7xcApwS1eFpalY/Xly7eU4P38OIPKdUBbHampN2XAnKmmA0blzq4n1mVOLryyyao9vXteQB0VV0dGgKgfcLH9xdTlNDSrvEQ8Bi0FIyPEYFJeyOQDXMAoMxKtEM7mAA/u7b2Xg3XKU0llI9lyB27fBm86ZTIB6g7IHzx1vHZOvUVQ0gS1+9tnehUH47YaFi5hnqAH/WMdXDO4ViFUB0D4ZyAXfp/TnebECfvJczgtRMSYEdIDQnR9OSqUZehf8ZYo50zxASFrArjF0I1ZJ3pABAzc2q5EgJMAkT6HBJxNLQq4/Pc5Cy7gL1poOPoY8mmngHnQ0c1/NId7Hm7wYXY0IgPrsMHstHLMYb5fTZ+F33RZDx5Uo3ykTKX+nYgBA3OmC+Aeg7bAJ0xcRhafhfQyys1gFFpQ5jU4V4mizHeoJMS1MwLX92OZuYh5GHWIZmTsG2asRZyrCH/9KwX+L19KCwrozw0PpFFoTTmG+/Uregog2zov8rrFacAFsK4zyL9HirKOjrE=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
