---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: mimir
spec:
  encryptedData:
    accesskey: AgBQyzkm8YYXwu5C+CeOOXLwKyr3XIvy7CfLXQG5csnyT74FtpdumcGqOXQduJlEifyKkyKzvVwu4rF9zVtjFsxMCMOb1cpL2dWNaUEanIziZY3YM1jd07kqJWP6TO2+13USuNEn/rjDf6U55HtF31aXHSqGlcfE1DyKcZxZ8LyOWz8W3ymIdkwCReTdzQgIkDaJecyTYVYOX5r3+tGnQ9EerftmfosfnWvog+wXAHTYzFBIzSpvA2cddD3Huhnl52VYj5WsHAgXV5UaX9aRqhIPtTNzheG+ijijimXk2zWWVArAb0Eow4Th6sS3j+k6emBibt67KB0rujSqIXDumv9gAzJYSIFGeVUA5rDhCg9bN2t9MTgvWO93m0tYElVumP630SvKTg/EFQIV6AkPemD59G6yXISh4TEF+3IIj1rXLJQzcZAyTk7i7IX9m63VxNeeU9t7zQfXX2fetVcZepVgEk04t4YAjT1eWdtwkaCi7jMf4bhx2UP2bHYctGqWEyA0sQarQzGHHAdySeZaVU+zxim3h5eeqVml6Tr2ANnvgY5hnGDDfQIztdNrLF+QsKP5rMzRxY4CIbUAccOcDDU8ClAlHG8KV2Co4lFaGCurSzBnv+inQIet8HuDmxj7zOuM783izxzle/N+Nvt7sj0SXQg08LNRIRBDyYEGYiln9g5syxduiF0kRcSXejyPa7Qn/B8OpqTBHM8=
    secretkey: AgAfnbvPO68MtfADj2IN0kcMl50km43okiurq1KEZ+zPNxWEiiYf+oGMf3eGRJ37C8sk3ZfgTsmE0tPQ9OBmvW4OlNdougL5np+g0c2vrozdT3I/xJBG0nH9m3Tv7k2dzL2zfeJ5v6SSRR+NUYqHuxGwENilyxa1hIUSWpGfMk12QfE/Yk9hcdW6/grR/hsHYPbefpRMdkYrteZetQ/EiNngXF+GJhoE2cwv0ly5DRZyLLP7qGieyc52noUMq/m76So2V5HyRy7wauiCJCQUM2Qa1eLJAE2vKL2sL/KKnh6yV9evscr6j7hbO4sLp+DIu35pN6TGPPdjaClQ2QZqcInO2YoMZDKR2OuLiKbTAWpR8wBfoCP44iykX8YCbnLiNORxxQcEbeSKZjCAnL9z6uh9NBQkejVFEqLwYThWPJGODz7PbsujtQ9EuaU1VUcclPwtKfxV1lePBmEDk6fIV+YsSD272xZ8GwJ7ETyYrZRKxzJV2aBLmQLXp+pbTvjWLA1UAcWqODfb1le3HeH5S1+5lU3B4MLALfxUsEap/qFpzyav7JItYb2grgRLFClLKsy5qB1Eom7Ww1HRmuN7K6Mt43bNOedg6Rn1XMgPXtqxk0RMCiVhEznWZEr0FPJLbGzZNDtawPGn5j4WegQfi7SveF4R8ErZ9zRjQ1cYMQWEIs+WfkAMQsK6FQe24nmyoBNw03O6LNx2KBs=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: mimir
