apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-devops-app
spec:
  serviceAccountName: workflow
  onExit: exit-handler
  podGC:
    strategy: OnWorkflowCompletion
    deleteDelayDuration: 30m
  volumes:
    - name: git-credentials
      secret:
        secretName: git-credentials
  entrypoint: main
  parameters:
    - name: pr_number
      value: '1'
    - name: pr_title
      value: 'title'
    - name: pr_url
      value: 'url'
    - name: pr_user
      value: 'user'
    - name: sha 
      value: 'sha'
    - name: short_sha
      value: 'short_sha'
    - name: branch
      value: 'branch'
    - name: target_branch 
      value: 'target_branch'
    - name: app_repo
      value: 'repo'
    - name: organization
      value: 'organization'
    - name: github_user_email
      value: 'tomasz@wostal.eu'
    - name: github_user_name
      value: 'tomasz@wostal.eu'
  templates:
    - name: main
      dag:
        tasks:
          - name: notify-start
            templateRef:
              name: notify
              template: main
            arguments:
              parameters:
                - name: state
                  value: pending
          - name: git-checkout-pr
            templateRef:
              name: git-checkout-pr
              template: git-checkout-pr

    - name: exit-handler
      steps:
        - - name: notify-success
            templateRef:
              name: notify
              template: main
            arguments:
              parameters:
                - name: state
                  value: success
            when: "{{workflow.status}} == Succeeded"
        - - name: notify-failure
            templateRef:
              name: notify
              template: main
            arguments:
              parameters:
                - name: state
                  value: failure
            when: "{{workflow.status}} == Failed"
        - - name: notify-error
            templateRef:
              name: notify
              template: main
            arguments:
              parameters:
                - name: state
                  value: error
            when: "{{workflow.status}} == Error"
