---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgAdV5rACd56DIj6hRMp2q+FWMA8XbHFVE3YJkRcA0f9yLpfNoi+Pzz2eM1ZzWxbm4YqNjqKw4WvL5in8FZIgfgMGAuw71UPVRhhO0oyo+qWVt6oBVL0xsjfQ86bCtB7ag0dcvoUhn9GQMA3TQl+tLwoyOPvbhx6fKEFkU9jgu6gMXNGurkTwG9biGNf5bKcqkg5HvJj3RWnxedXw83mUgE41hdhSc0duKdg2NsZooeM9TThdYnAFphFvUYm3rVGcEp+wUU28k091haUIPJWvsFbhsN35Aw9LxupYVXeEdpXS+q6Bx7wmIq66s3qWv+Bu7ObvVMFuIN77YtjihfDt6d22Sj5Z3cTSYGwPLHmJn5Dp+sODtNZtI1uffaBT4bJw12VbmSk3Eelcfs5b/jWvCW9R/2Gef/Wv/Hk75Ixuw7JxDGL3oflpDLG+Du2U9qa7zRHM6KF7jjoGOWSxq1bELWV+sebRjSSFdAVLvy3Ixve2LYgPgFVjWRGxd6hV8NO7XKqcufOjhFjKxpUx3yQn+3hAyZFKF79uH8F0k+co3aYLZPdH7/waz1eLxUOTl/ROFxPyKedPKk1IoJtrXJ9tgvO37ekJ4wQH03QEEbtBrUj5n5an29OriaX7zWbYdmvWV0oXfbgMKqGs2Bma/NVYGy2JwBQuLZrK6Eua8nytt2gbLj9E/wVQ5sRYGRprb7mw3uB/4XErwh8LHYVq1REe2sXpcF7RlgVHO/d3apMT7Yce7hL47MXxvBk
    email: AgCWml1b7i/Tp6AJMStM4ixEbuw4p+WbAU0YQXtlBazPnEdCpy6X8dkQ5sW7soOooKl3MbmMyYHli+2FxFH1G2RlNTiIHpUIoJCaHv8S6PMXZYmfB0m1ujbjt+7jy6ll7C9yNLgYzgtihoGZ9N9XJJAG21MzLs32XP3EVBSyi9N50Q9tQPAOOPtQN/NWzD1bKuOGCugaD45QxdsFL+XTCkO16sEQQjN3//XRVC5qYDqrSAWGJHdXu5Il+iNM6JZddwGWrvv3KfvlVp+mFz9igCNos+4+itKpuhbwtr+/nyRMRPXGUmmNrNC3Cx3dkAOmw08wvJkd3rweCdzNN2GVnqeqPvTN11tc0Yxs4yrrYZuE7skrc9Q5SPtRMAf2gancBYPRMJsRducDVuijx7aXio+T4xD8+ur5u90jRlrRa4ClrkodxlzpgX2q5mZONO0Y4TTCskPosovdrlhYU/i97+VeQKhrWDVrjG99tng1L6xKUWCj4BUBDtTkmPJjoWtgX4OJ/yWQ9qJGfSXukLVnDxYqpX9pI4pyYTbotMo9CBy3+IxKDFMsnfiM08vBK4zqfN5rx8vsH4SMO3MJ/53T+Vaoff293/1WUXqwiv7b+W5OyYwhjb+Tbfr7+jZpfqBkbfXiQ5QV619gPBArUVvtmI5cB3KIN7lIUkCj1k19rTJ/TpwwvjufVSAu/JRkv2yxLKd1DjU3IDK+YPNt/s0qIKkJo5/o9/Bp
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
