---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgBHupMoimmHjl8nkW+CKQUIWShZX83YuD5mjnTGpBrIeGVVRSnnuT4zPDdXwixX1etpXAI0uJXr7SR4ezwW3vmEiqSp3g40+iz3ECHXpCEn2QWI+11iVTwghrH06kM1ydOPUZ6yJOOpivJwkfT25nWXds8Mmr+V3KKx3bXJhIcstqzAbP8NlNOENPv49TuKw+BObffyKZBSEq32Ylps4V3tp27lsIjcqNkFalVdZCsWkQ9OHNf94vCcfjgf3y18nM7MqPIlwuBxCeoq0pQilGkJnPW5VtLOsI0bH6CV+ItrOJD3P07OJK/IMwGz1wE1aLJaNBPoqRLE4T5StFV2uRSclQzWjik7u/XkeS8ZEN0Ek77tVk8SC28KdR3xj2SecbzvLQ5b9LDqmYaGzuL98s9T6KZ5IlJd7MZn7iz5R7o/6ifzpJQ3r5+Uk+8LC/tC7P3HK71Ma/kBYfYWqsTLzJXKx8fctAVgWOoGjWMmqE0ITk7kbVzO0PuRjiLG72ukq2ALrHytney1G4fvE+guPnjbpC533URK2Q2fsmqVjF+uaJJNfvCV74JnW59NZsaAyFY23dHTBTyNoKOyM3KCLw80yXG3ykkt4HUVW7f0h+qvD0eqe+DpjGuzx7CAKRXGyRMiH53oK68RWpxanXZpn958aPwl7vglVrCIbgYpKUleWpV8E/LQiwPShhCIMSU3eORrOr4i42bclRwNj6wJJqnSuPFxpctfHH8AoLvFQUFxRLm7wY8jYgHL
    email: AgAOuWln1/n84/sd4C8/yOytdJrAKCmbQRhh+QNHeqywWIBVrp4REe/47Xw30DULqwk4aWZDbWWkQBlxqfEUoujH+i+ipGJpXqVz/erpJkVUo5MweItZKxdBu53PCiP1xa6NP3/qgTfuh4KPgyMlmKBTZI4twa5KZ01CeThhdmUM/UncaNEb6+Upco/8JRvtY4aw8uolF9/VgClZadDsXzUo6vCLjfxpTV+gFH1rrtoO6LupgawaxafGh+akubWKs8C3GNpFp3B3/qF+YjRRIoP0CoZkjaKhqxnKnKJHnUOIXXxzbPuo4yYEJv84AiG0QVSbkgQE+d0LjcJHYeeCjGgMDFx+upfxYYdWxz/Ql1Sj4C1UT7a3kkO1k05eUMawiuDZIkvvLdr+O84V0Z6eSxZSCUdjl2YLDcalQn0n+h+MdBdHN+AY37mWAAn9G0Y7He8QB+J+qwYAedi1mlQgnsVmQOV0zngn8fy66Oc5g4+31kvB47R/iADMvaaR9MzhCjgoyG0oENXi9exg8h3URevduAeAxUEZyNmQz1A5jrBiVPRwo3WHyQZTLGM/hsdW4diDOkWM7pIF7mFh7iqyDXiXNElsnsOUlSGGkiXot06Lxz21Mn52uRu0zXJ6p0nHvNvt3ZvVcNjvv6Lp1adnNM9B9/+4vNqOddhthlXXlA3pVpAKBoVHZ1pxo2sd50527SV+esiOBGaZ0bKft2UEQADGjcDu2132
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
