---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgCcMgud8FjKaBN3GjTn9ihJ2DJxwp+6ACciC8SjYEtoZEwAZc+ZGrlgJNHKCTQKPtvi6NoymjIPWzoRrlkOfl4yayXS34cC/9lRXlqnoR/j79jmV4pM8elFvOFpUGnDk3xDtX/mz4gaV7ft9wsFda2PLfsZT6+7JWEcP4IISRAccYGbouOxSYNpFF/JodkW7VM0vLZ2C/rcx8kNKYZgc+/jauLvtwgZBpW1GKs6y64yXwLLlya/ukRsmkvcFVwEkTSouleJ+boINWGj4Ndfz0/LV29jiCUZdTpqOCS0LGwj4V4nKGuC3/74QtyNXkBJt+qqDwcSL5NdzYuDE4wi7TD+yGPKYGQtFu0OzsQNmiVONCMQLOPCVg8FjKBzfe8vyV+CsIcZnbQ/jkFgrSOMaJxCDd1HDz8Lg8w8dcInzLd04E/3AZgsz7RcZ3sW6VBmP0OvnyrOfpnx1Qcn9utvpFBZX9S9Ttz68/dHfup56qKklYf99qTJnXZshNsb5c0FRPWP7FywkAonYBz+rKT/Zm8DIMGXdw2ustCmqGblQqsF+lopc1pK83zKWl8jdO+3QGrJ4texlcqWUOsfNQJFx2orFNRHDfkbpCf0NrmPgDxhFlHOZpCWlpo5qxnLS0PnE2i0xkWSHaBd+OFyg4RuaiOJkZLOtgAdNQIaCzqeFbwPYXU39C1GzVCfh0pTwF4ZG6Bgk1d0XHM3ItMqj0Xg4P7F6kmznjvFlpiK6VGriKbE1CnNm3s6IvBx
    email: AgBtl61ocx1Z6XFF/xI/ptY+dJ277eJ0xLOpLNPvDyXlSA4D60HAuGgSDJZsV/JESyFM1+dT0Cj4eRk0WcOe9wFJkklemN9R7p5dldabg1YeUL3W/++1TWnkwzIdTawV8qTOIwQc8XwqUBdSj/+gnkCNGuF0q/CWgKUKa7DMbsWUc9MJR5S8KUak8DoUWMtAFLIBjScrqqFs5oLyaDu/7m+TA7DsEzJywxefSskRf1kOakSk8T4cM/f9UXNvapUifR8sggGmhr9VQIEPX7SfQHF1FknEeJ7UHwMx/UNZ4bm7UFaVj0rdLMQn0zPk8VCiu7tcDBukUowZRMNN8unC4iy3cHV4oVj9fSEELb/R0pkngGpJbmsRsElZiBwm4rCxKCX5+pmnw+KrPNjDuI/nXR4mjjvprkrsDf/RH2FTh56PNpeXm/u8Lc88vhjxDcga2tWevmKHwsPl7CYbCCiFhAeCY8i76zFRzP0l516M7Z/vLVJ+Zwce7V3yK+YrdrdRm9dJUaThO/clKvOjsGelBgYQanze5TNa/00NWCpQGC45vPEq2RmiJ8wvfvNVjdlOnCKwKWN8AJF2nhtVZgNNNspuA3XqSxo+NVwQmqz41Cgr8eMmX+JWtBDr+KLgroH5gENgFgns60y00ymLrQz4thKfIoW/IKic/ylBG+jWKlnndcttqmtQJKPzSeE6wrx7HuLDdbTaBUs9fsogUH1BC8zdq3lVFmvI
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
