---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgAGswXHKhoKIr6SSnMdnbU+sigu/925z5y88Ob3pjQuon2U+pK5zjAqZyVMMeEyIqCCApR1FVxJ+9omBXqpjIz+kKV/3KszML2Gs4M6piA+H2BrtLIBr8d46k98mWeYutT/xfrvDKLobI3LvdkvX8CGhQm+uvmEejeJWTWAPFSgZMQ6/dIHBgTmrvePl49wGHnnar8sCv5BJVRXfh6sCwvSlrT1iaWk/Kuos5VgOUmn+zxMe7irAopsiHNqTKY9dKwFRj5H6Fgs2vCo+8vTJqGT8w8YsWjf9vPk6hCIQJ1eDQYRPQ5Wrxa4Fdtn/hYQCybzkI2xJN/acOZWeIvwydLyEMYgw1malxI2sTjD8lKZBNiA7FcUgC8dlCAjnbcqRuueZWCUqVCDyr5DAjbkAon08rT+MrXf4YEhBZF6tMT1mfAlDn4/KPTGd+6tfoMpPm0uGeF0knMTB6GjVLwrgAeDgWZW6W84aaLnqkL2U9fdkzF3uQ1BIpZ6pNRtCOcQEXi2PA09IXlJfBrmFLzG+nPxTsFoFxdTL/XAcJtusNVlOEy0YgbpMzIFl0nPQWiWVre3FWRp4yqE6xWdoEgh5paTwKP0wQHq6POlJS91+ho/x1rrSW9IlN0HFQxM7HT7Iea1zEwLZ9lX5KkBAwO/C/+27xQDrzczvuQX75xKIqTBmtwCgWWOxLgqpFc9WkJZA4J+kHEeDB4GwzBPlmgJoQeZo5+EBuMoG6jqfqxYb+/JLuBrEhN4dZ3d
    email: AgBUYCmXSJs/ZLieMK1C/L+x7Az2JZG7bxZHLu7XlybBu0koOFAkbwK036yEFtqEuA1iCQp/R3Je5+E0NX4CeyRLM2Lq+X6oK42Xy6HKSiujJRaESbDJYsFAIEOqTep/D0B3N7y7tBh/gweM1JAhYV7LsY+8ch9yjukg4x9gSSukvOmhvQCyhezrx+HM6EGqg5x7N8ucIDi/A6D2SI8x4M6FHoraTC2Fi6jLcHcRTe8tRR7wK4X6ZYd/9+UkErOt6kpkYf49B7vwakLl9q229SpcM0QecRfSzpYztCK8C+ptnl1zU7vU8uz07me/+9QZwTFFgf01hG7/5tqHLnZTLMsHyrcX5GbyM9tK6WwibJv28TV9ohWZzYM1E7KqjNOliQAhNqB1MCygsVcVPSinWOQFPPzMgqBx4t+33RD+syk41Iy2M4rU8WkKjGEfOX38ZbJYNlVA46/n9CnsqxOR8GGGM0O1jhDoTWzzM1jMIHyHC4X0isj2nr2lZjF1epDOz/aKVFv1zUdH+OTkgOtQQs5qhFGw/SngFbYiVOQEQc3Ko/Ylz2VLFQuHJbf2rhC9CubrjDMjGfee7t1TaLxSm+0hRjoZJ+VKcltZGHxHXmXg2I+KIOxluV9ZjCz0bzobEE81H2/CphGlrGqM7Ch15VeAzRRrzPFuxcs1UIZVWJ8Ggy1CesD77szJ9EqhiWnbs0qZpcLXdb4GeB/6T7rgzUrqqFnPjgTQ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
