---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgBL5X3e7ZtVgqkMpOJ/um+zczt57J25+lpXNKkxzpEciP04iiy1Ki8Rlzmp21GLQ0vQVwaywsK+k4852f9lclYCZzDYD86CY0AMiPRBnLG7PNaN4J2SnP/+ZPJflg9bDGrEBGdd1qwkXkOMOHqDUwIv7nFWlBQMxH/k+cBhTLvZHTYZOU/uQqum0PEAn6/Vlr1shKAli2bkYbpfBVEzq6sEf9aExc16hkRCB67OWCoAqppnyMH81euYdGaGRvpJxN34guSsghtiTaOQA+Ch0BMf3XBuEETbXDVeuAepIDlGtXk+Iljl4RMf6ppDF+rpRpIpyTn2PuOeoIlJga41d58/1E+ovu0SlO6CLc0DDR9R5Up3cahPpLG1w/l3nLxjEVJ9idBZhkR9Qul+6hsIAsQduMrWL4kzCtN0F7FdTPXgxwpjEFj+3QpIfylsno5/9XuRJNOC1xZuKg4VjPL+2EOYGWjHNX1VR947eqMlPgHiXq7ct3MdsOP+whi4RQkLrP3Lt5dRRvA/sfbT/K4t6N9/g1Agu1MWFsSTYZ2me+thiNaLHnyGzvNhugIMrxxdLIdNGRtU3bG2K0ZW+zVpj0vQPOs0KvcCRueeCdc6OJqRgn6iH1pECFOcQdO9zPUveAbVdgltJcbxxwONXlFZtRQKPIvwrgelvXkmjFo7Igh2aA8HqAXpO3X3APexeUhh+Psh89ZixDwX3RvTLp7WOHNYZvv+QjPVUCUqOd32r2awo+8vYgzv4sBM
    email: AgAssiqEqoA1WgIATaIsdxltBBLc9tmUP4tz2nE5zAyBvrIay3d6C+mdCKGmiuR3PEHVg3aVe+myiBqgElQ9GcILB4HZPog2fxzpOxF71jSrRT4kaHXAslFV9p4ApExxN7QFWnNaffIhT8OBcTOrLHiX1JEp+W2aSCGRex2Q5/qzCNxKigGAOWtGuSgJ6SMoYIkYJ9xNGlcf5nIGrYPwEYBZC/CHSMNd6KBBAhKGlbl3Bb/NOL3abE0BoltFRE5n2JL4VnwejGN/7vNKMeD8wuC0cPmQBF6J/yujJIFhbAENYo8ri+y4rgtM3jT++NRTPeyd5aag7IKgP6dPR/R4Y0iAd15Y86dkyMuysdeL87eYOar+GBD1YDci6z5TWdwUYQ5EqP3FY1gT25pqgLCV81Jcf17bVBRILRbudLCuH8b+JWWlMPjtyedekSXp8EU0KRzR1PtQJiBoR0Wl29AUbve6OsfwnI1JDV/1TqhHLoC3AUro4rui/wC6+IjbdAoysKG/7IZsfCQac0ujkcipV8QShLVOTFMzDOQj+1XQX0Ygq4O8uH1f2sMASU0Eg91Q6S6ojdMNhtaiqoqjw8gMPr3/4p56BYk5yazKx1DWT8I9yLCY+5xXjg36DWRx1lko7bzBfqyJvFOCti74JwlReiblrsq4Ph4wBdwi3EcYmcr2NaZ9UAiseROdZebA/ab45VQSWtyXJpZwgEbLy8g4xqEOs4dXcwOZ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
