---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgAADow/4bStfMYJROu6L36BIZ6f0p2oQwfcrcS4dW9Lvi0eGSa0Erv23zaDu2gF0Ge/ucj2WrXyZAUNNfCapl9knPwlK+/K4eqn4HXjillKr8gzMmsQDh9ju+MrHuZJmiHtYZEd3PUvWA4msiv3lu4C0jjV/1l1Zm3ig/4sX/yPaB6P151aY5ScGWOH4jkYPFoItrVZ7429TBK7P7ZchjwbTJQOqNOPEni+kMXY0PIgzqaIVX1LaeRRoQmDfiUCqz8zm690ZlTL8xpMsR7ygtPi5c/Jfs0kMe+VlPbKYiErQ4/Nx/xG8uaDOY08NIjnsVQCjXV/RPVS8Osue/Gw5JDsHB5cOced5LthpDpzNrVrG6U5Fy446D3rrpXW/i9DcWQUgqXBrEPD1qzcDPiz8HjGf2poXdgtBdAiadM5wd+DFxoKPe+lsJOhSoMh/uHB9lvLFZC+w2SpMvz/YQc7aq9qtcFHeI2+8zb50ddBTc1/OPzV0xzrHY1x2u+/WBQeK37xYCDHn31EBjuSbF/rZnapGSeY4KpibTCR2wKDbfekZZ52e0iJXTuZekYG+kttQmiO5IrLOtBUs3jVMpx10hEyDTv/GLQcESpvVyCOnvBKxkEKQXb7xguj/cgFJjREYY22AbNdO+YxtzafxSeqk9pYagmH3juBItopuEfw9Hlz11nfz8NqTYMBSpErsME676StlFy0X6NpsJk0ztHcfGO+8c1BJJ6VtqbxG5CeIjUrvfT/GC3IrvOV
    email: AgCCpTy+mzizgyIx2sLi3UQ/Ks0IDZbncYVONWCDYuxOAS56VdpJdr2s4+ibkTOoiZ8RBL5cAKUkq9qqSBw8QRdkOrEqNaA8HEoOGbBJid7WU0vKHxJSAMf3z/VoJr88eMWErt1NINQIUQCJn3iKxt90eo1DlJ+84K4nY/139z8+Ah6LbiVmQQITglvPz257r1QhPne4SD4Au+nAzou/sQuTo0t43cltMrdnqA0dxj1BtdxUIf4PuESy5U0jGcuBLMoac2fOJPLPYTgACfL7uwziJdPc39Pko8O9ubaBDnuXWZ8WlXh3AB6vgM0r2mbJCh+Ax1kAn0Z0dugjW7KoM5Q7dbXcXHMPmEZAB2j2suU2zHLlNAnl/hsA3jHT+E57HzOH9sDmyAspp3bY2RE/z//0HBNAoSu4UPSM5gf8mn2HthOpMaAYIY+qVCUqcUtrlf6mA4BwBxjsnoOkefjQX4HSP3aN/E+n28ALtOQVrzqovCxeDR3xz6XjNdtVHHKTV1lg4bjwtenGyu24LyLGywaJH1xTs+GbJE8F0re2aeG3vIaqiAB7SaUAYpKK1fdRtUQn8QmZnQghHVaTia9En1rhmfBey8/GtLP806X2srINvPD/yDTVfEwLg1OOYyiVwhHY47favYGcXZaXX5AdjRCp1g89uxmm98WJ1eCZcEiv8SQR7BqpSs7bhbANklwRmfHnM+Ym9n3kQQB18RRs31n4AhObvHGj
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
