---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgB7OV39p4GPEpo5kkoLSuDyO2S+p5XsRT/45XDKrSoj1BWLgYj8UJ3hSUr4X89fam/JQchXRXJ4Dlznx1jX6Ulfgmnn7JInUKkXdmGQy4Cpyo1ngxO3NXrtjaly6g3oFN6IQRUxFs+Ixspu/phGVALw0p4kOwKp4WiCTTC5DJ5IpV57Zs7joBfxF8b2MP3plZn9OH/9flipgO35mwiyKtKGUCzHeoRlrTNqH98Ht9iRAuyHNsDespHkTi+6cDvxAONJtYlb4oYZ2Pk2rngMO812A/on7UBeaaTyiEQ+zpVyLZBIL+MCDFLuGz9mayo80o98Pm5atH4VVu4EhlNW6hdfAlOaDErQga6WpV2CLXnWk9zW+EWU6D/035xyz10pRYxXG++rnkhSFLtuHMNkArGrIhXWCtBECEoJV9cTr0/gvKRIFDf/BRJ53fl71RERtP0P4zAMQNQEbpBV4jCeY46uWUn1IJiVoTYIugQrHEmjnwsiwB8m9m71XGxGmQUP9lu9ZNCYE0X+8Deg21/l6e0ik91eVoNsZYiihiAb8Wbs6TfB/beLpQTNZgug1cp0z+Gbxpy2PH+9mho0T5N9NQ3BAzY5Wefj5kIRpJm4nK/qY6Dh2wkDrVG0nYzaobWK2atc7K6XMSxj6M385nCBzyu0n3VLEHE94XQLw6Kpg9vxJLKHEpuN/iHiOd9uB22ndkAe1dEhCLq+uDdhBCk/AvZqAe374X3S3BYajHal/kR/kXxRQkgxWwTI
    email: AgAgKEt4vWQ/L6DNs+gJga6bTe/ED6BwsYkvWlBsjA3nfpIgAHdl1ihdemuFXO7fLvk0505LQB+uXUEltLhB+OP334vJ7j7dkSmpZDinc+LlXrMjyHJH/cnXvCcrAWm0W0xGPMAb4JecS+FLBfptm8cP034NQr7QDf7tWVWgUHIfk2PnHqiuTSg/BMVhjPXEsLN3Cl/9bPhvGN5GFyFACwCopiS9+4P/q13GFkiynFs6bcoFQn80UD9bks0vm2lSGUafnuvqVK6yI+rnhoUh1y2TzgsjtVi3EtZ7eX2dMNWEIXQj3NfLZQ85tza1O3fnw4+Zo90Jn1ZRVryBkFItJvbQHxUmtP0WAHENVO76Kyi0IL97MPMV3HychRQuhGbP70su3Q++PnKirRtQVkhQUFop6BkapTtMiLt0tHEPnwmqCXctfeB5J9NRJojMzalOC5lyXQttwqSy66VLe1dFQ7O1RNojyEdmPbuI8OZouNG8T15kyJm62cLBJdeXcD12raXxvnEEtHXr8dVji8VlQg7WZq9sjBUuBROYCq9ReVvwfZM9s9nXX62+31/mvhnfFf3jAPK5xxNljxXVK4OCcz4iDnfKruO6YaKZqk3ln0vjLhEChbTz8yOJgxtETxqXL2yukzOG08uG7uzjsO7wvnYiXxEcR5ZOW/oKZPOJRBv2l9GgL2DDpe8DsBWT5YOQgkZ0vxAx0TqsIosx/jvZNUt2rR4qDzyu
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
