---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgA3BhagCjoyj3dRfNJUofQJiuSpwvUnt1O8PPuriz+rXWzW7uBGf0k6/eEsCx7yb04POK8TRdRUKLWa4y905mjsAPJNR+aB5ATQCc+rWvOnkPimj82eCCXYf53DvCp1H9AgqbrIpdl+FMFCORQN84FvcVphjvF24SnE75B40ksVqgtB0UOIzMIHeyksi2wZveu4kntVu3vDkwJk3v7gD7tA1TKlj1FkXIZeCzGX1LnrWwflzBrW98ugAze1j+6bgeyTJetciduTlqmIyrwTJmyqBcQgqSauHenVobkpfQ8q4U6WuvNP2jhCzd1D9QVF346rKX+ScfarZG7ML6p0LGkMHJbkyWATHkN1AaNDuhDY3LBGIPBdWVWpCdwmze1Ee2O6XNaKochSOB0KkOO9OHk0J8P9RZ8DbiwNbuyZxrzUEIoBcTc2vIulNP+TJs7wVD6g5F1YWXSNTpIvAcF0Ri3+NNC3sJvp4vDByjN5cjdu1Ja/ReWN/+0Z5gDsQFAaRSqZCkyV9IbJKS67h7GddZjkTIT2tfhuIwXFqNVgNLMNP1RbWUTi9xCDnNcGLGrbA+Eg2cDMy9dayvhlaaRQ84/BRwZhtkP4kYoVqgNk5UHCBW4b+n34QQol1nqAhKlLuV8cD00wec3OWQNuIf99UIU4wYsQ2lW/aorzi3AV0Luv7QmpDX9S+EuqboHguBVf9oYEynPteQ6Jw2AxQaZewP5xINrXqv02w669WFShpwoGb4GlyVq4661m
    email: AgCQb1CLxXrdF70cOYzr7Y8mm1Afl1uxB6gvqEw2YgBYGysZffNilXCTNovkB9jqvKhdSaBHk/wi3x47L49t9aplT947nsfem0E2xFiSfPleewihiPUmNPuzyKzw7HzOjVdS427EdPTTJ8JbzOn5hg8PibQpQMvIWMq3hwXvL/QkNeojMyWC8HnlWWc+RLDy7TpC6h1X6/9GboTqOZ/PpggZi3SJLnMNybKyN9dt8hcmFLtkstwSMNeOX7H/zBp/bNzZU2kZF0i3r0bdVX+maV7vjmY9CQLKN5K+4aXot7s53hBpof8LGWSopZWHQ3n9V/WDCsWD/F9UHKTT7tNsxfTGsCEtKaVKeIMIpA5Ju/ksnWb/L1UyCSQzzcLV0bfJk2Py/s6pyfbi2jDRYbl4QO5WzukjJS+g0a62n3Jedn+0EWvcPzeHRAe9gVa+xe1msSGbDiHGhzZvUnOwKe6R5YxL+HBGePKNGlcKP/vaDrpDEMZ9aijUmnXzdX0WJfde9+PDmne/2Lf1QRpFws6jOdJJCuSm5gfjgZeVu2ioZG9axA4DE7ugH9iFLncIKVfm7YkN9ptYjlPOSPPGeFjEqyPaEjMnMIka0PSWCj9vjhX5Z61bEm1qlAcCnJE5He45n9TkKd8SXNwvF/mbhQcq63NlfnCHjeB58PCfrPvTG+ftJP56d5yzIFX8tr78ZPF0s17dRyA4IXj3nNiG4bN846+5g2RScA1y
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
