---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgAPCyJax9ouzLlyHGAGFx/fr422jk3JHzRj/hkmsoB0PR+38d5pUFzV0AOBp2eyvHkGE6c9DVyn5AnT++Yixn7VQwJs1GMvhcGkRLkcp8FJWVmUAT6oRYu9zY3h1xw6Sd/9Do91HAKtcqtbYCQAwlSbpZN0DxtiZ6Sl6Bx38p2jp+2+VfIM3J1Jrw3ywRNQ0FEeiX0UbLeDVbP+W38kzrZeFhQixIs/SPW6bcOY6cJXm+FDNyFKpPiGwltJMk37LC4pNSU7BzT2fuBU7G0w/1flplRfZOfhEGvTCc1slTN9yJ+Q993L+YTo84dJOQByy1iphDdOPgbRCbZLAUy7xrmhJck2Bb5/7qC2GD5bwM+8zxGPy1i/jQIXHoSPCxM0RlRWTtwYDwUuCYg5UhBJfuppcOtjJVPQ2uAOsAMDH8GrslH3VURWkMzYEfl5letOuQnUP08cTi4nlNw6Ken3pFN79hOY2u9mtLxKPsVIP2hsdCGT0Ze+OTU29zJlYbFJN+ZpDYonmZz7bv8RQ3ckX+Ld4x/rY8Ifb3NEQx7Di7KvzMiy/JLVqmce/4fGASI2jbiSaBFnuDERNvclBYtwQ3bOFaUrCP36wbC8dxMDUSl/slFXcl0yiFLNsG6SDGVlAjIfZNDN9yZE91ALkbBPli+of39xm1tPipX6zeq4rQUNTk9Mqzo3nq/RXF6tc5v70OOF6Qh416QsJbvRCq7hAtkQPjuJVbf09sfgqATwd/ZphwP3kF9xcN5c
    email: AgC3zKk+JTclsEAOcsdi6sS3QjWPJ/Rb0kSmBJVmgBAOpdoLhwQYijQRXCyJ6nfUhIeqQtr6XxenJvd++9zzN4wba5lVZJ3q5/pdiKNS3oMO+EMW4YVBWOh7QYOfVq9t98nn0i08ApeGLdIJJRSBnLIn7zou58uNXLR+SMbBcyYM8vt2BLZss+lDuOh/2sheW9pD9iiiKX6ekojhnS/Kcl87eJR9ISWNpM+EoThmM/JeiQrQeh2aM7FB2cztvJpnXGAp8ukJ8TwwWq8PZhEVfy87IDsWKBK+fAAc/D7iiY7vULLJIhm5QLXPUsR9SjmHMguFthFeQPWeKYhzrjeP/V+PVC5PfKDog94BajPek/M5YNYwkC7opz/75GFCSllKGZ3TdhHbFXn2diYev1uDuFuYLguazjVzegzUGVsvcruccWmeyZtN6+ge+MJJfhuDUbyeKHWfTOLBpECDFR5z6f9lHcUfEdanrAjdbLagP6r5/sL/yDBEGamM9XPVzpBt0i5QKesYzCsbqeBJvDVK4159Xj5eHaC4qabjVMn+CZeaoUrV1XrLL/sEBE4ZwdKVVBNHPi3DlpbHQEWHW803qEGzTemxtJQpl+MWZp6UU2C4xgIiWX03PcmpX9jfviXGcCkvu5LIwZAXjvvwmCTteXOuQsQayyAYoMk7Gezt87hVVl3BqupUG7ZvDdWAcOZGa1fLZmlBvR+Wv4BwlDTQ6d5fJ4W8+EAH
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
