---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgCf8g4PG3YWcAbMd2E0RecNBb2V/ZTCkLuXuVr4sQO2iYnXanklj5DgQBB66sdac6ff+QxBm5qBfQoYcYjouM3qGrE5HGrReXL8JoLA60K4BGkthnL7OkBR7+bTfaiHHzWgSUuImqjovfG4XIJ73d4qC7GjZxEdjuQuo3nWnDkjchhKCeT6OUusGg/eYqI0BQUyuiioW8ov2jMLH6gjfVdaDFrxX2bmtqKntocH/yTGu79l1xwnipXCsmX4bz69m85O4SFN4qpL+Hgi09ctRLPs6XlcwR8E2f/GIVNk9evJnnpS71hozH2oP2zVlO5VC1P7/nI7oHg7HyPAoAfs3eQtV8K9k7z7GkYMZIJaTfGsN5x8O5fEiF77D7+Exn8RYIiAoCYESqZsPQL64x4ttxUw6tQHW2L3w5+QDu3NwgSoCjtlddmcCr3txpSLSnbDT4Ew76UvtMCgAc7uc7h0nN/IjZqshzxB9Nv4eDaLujSCm3Gxx1FG5V0cxfC84ad5L9ZzkfB/dCIWBBe70X4lORHny6RmdF8584HmOM86y0Q70Xxij7VowEbXSJ6ymy84fd9XJSv9dknP7dKKMPIYs992McHLpWPlflqcgrg1SYiw8sTdSoi7+dmTYd3vzCoJeXVwsgmZ3tIxS9p5Nqn3iNibY7dlUR+hi5gwZ3ewSArM0nOR/SB1mHwFCfCa7ZhkpcJ8dhVYzMR+66o=
    secretkey: AgBb8PpXlRUzFJJlJYvV6FXtaSk+1eT3KI44W+WA35foEm5PNHwTGM7HyDFSxmlnrdYsbs3DKfxU+LfnxkKp9zpY/PmiFMw0fXMT3VDWPI/qzgGu8NmRpfAqcquSE2xY4C8myNLETbcm+9G9DHzFuA8weO9GtUCDbYOCoXH/kT4VOErM0W88vMyc22en2b/2HN+grm/fUUQaSP42/xHfN+RZQwnTd6rvV0OHQhQbWECaXRw91qw/Z4KzTyA4VkjwO4HCILU92MNS/CmweSaMiJ3yOcWkXinuKAGidNf1VVbx599r3PoQI7ZD6GmajKeCPSwTVrJFOQqb8J/IQF6Q4akiIWvEX+6iGTwi97ytPu7o5RR4XbItZdxOab63f7Xt/6YAXeo6EaF5bVh/9qmNKSq1H1AI2hhjMk5onnSKiItO+iX+gIONe2zDHLzQaBrs4Bt7CMIF9XYZ49eVDbSAL8XPt5pFvfkJdrUlq6YIJ8W/xp7SplK1kP2QBLg3HEtnuA7+NI2odVxh9cgRh12nlPFw8v8v4x+/+gS00PrkwNuytDzklAR/X4XBbVwkMMysiIEFN126XBKtGqNfIaQLnCC18SkaRnke61kTbkhNmnk2/QAmOaNwXyZaAf5SJ5rbpOqjzdxGzfC+DXHOp7zxpbET0nSlIZUUccq0gGsCKNwrTPAyl9GMXyQTJprPq4YjGLHYYa8IBKrv4go=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
