---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgA+gyRBvy8pYraBYzYvO4jwn2UFSbBrNKLZ2vm7h7afmk9FeHhnrjSVwQvfdbfq37fYW23af3ianbB3Ev+P5D057S42M0hXZXXwr3Ew6WwYUK2lyOoqnNu+NISVAKAGSKxomLfjw3veL+ObE6iJhbD9Zp/jop+msGArBX0htH3ECOgtAg/Vte1FrO6L65rUtiVm+4UQLsK5sbLmF8vU6hm8pa9LhE1DiFDQREawmqWQdtUN899jc2SvNoYwDIQJTrMwQasodH2id+WHSxMDpTUT7VS0BnrAgs0swvus+mfAyOA5T7Y3EDslWmc6o4Dt71X05LGNH67moFCDuN6ZKY2aR8UiFlbQbhNLLhyi5nXHAztirYWuCp7z1Vh0eWGBEQ9rR/QjwgxoWSJfgVUEJAha7NKR7dIwSGtUPQb/a2lS45LK4kfhLcwgntdHUzQiguUKwWtTfEqouLdk2sQgtO9X1YdRgP8wmVRtVhk9x7J39tDL9Sw47F/I8GZkpcsDqMwvMvtwpDw/sEBg2YuZRB6Zk43ReP9g4PsNZ3YkOkaptW8/OlNERFW1DafksRXQJMSMaSlx11wnmJHpjcDuFCYUEZbFp8LG4lTKl6YotOnrxbZm0wl6dBF6axedgp19WeoZt1pFSo5YPOM9DfqHQKqnLgfzxWeaF9L8SoYT5YAu5rInxa2wN54mn70iktu0LO20abcBi4dMP5hc93jtrN7bpfc=
    client-secret: AgBxNRig7HDg8aYHeINxDSYSSnXMWWclqyb2agQHV+5QC0WP1zJFJJIsHnpZP8WdMQkWlE2J+tD9QN4UXlxALTrRszmN1seC3Ddxgtm6VSU31NmdRMN72UFLtp5kIZIPjubA3YgFaJl/yHR0DOv9kJEKSR+LnYcKDtb3ZQtgZctyaDFZD2zfNAbZWcr57xgv2ikuZday2BywSt2XWb13bRxTomXmugoEhTtYP/w2bxWS0qmcsY9NmA71OCthYxYOKoamK4Y1YVjZGtBfC20ARhixLHMXz/8bW8SDbeN9l9yIqWNrGY0p09VBsHa7oFYExJKTRwKt9Q/0Ja0Ls9DLK3eBpfEwYZaqePHnim6LX0oSrZcssfosI1xCs2FveWQC7PeW7Nqihq9a1rLCKr9Pa579gNKM+D4ZaOeSxUEJkNW65uvS1NYKvFRK2p75g0ZbrBLmSpklp/7Xr9AdCnUZFq4A02j9yak18ZPRz1Kj7h9bFJ1CXSvEnaOQK+qOi66x3KjDaXae/gUbmOWBnc3DW8qhrRFT8ITzylmxkB0euGtdcP/POic7zfxra9vFoo8Kgc5b4In8XqJyaLAsAc098pGztbN9/F3R4SQWtnC4a9jV58EEd3y/8dxj465Fa4pr8JhIwnkyACF8O7EsktAZIVJj7/hIse9VATgc6lyaLMLyNck0CdWCcNl2wQmGB2Dt0De41GcjWVxUoaw6SNV21AKkKQuCpENAHMw=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
