---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgBTXhe1htdKp5XTqWYavcLVCvdKAYMaoJAQrkrl2Wb7D7cTP5k0tXXT2bNDtvammiGownnYP3ksre+kWkqAyrhsVG9zTAp+oubVajgUUTYmkxUmJz4UA29V6f6pMLcKRTx5+IwcOaCB/chyOjOtp8lylHXeawWe8M4TVLxJe2B6Kpc4zXYF1seYKUJZDi0EAR3GwtnbIRFrhB0R7UcPncAbBTC7NSpD0QxgzF2dZNJxlmaZgPoKpMgRg6v+FpT3Sjf3uSrDrYsX65ajQBkBNTYNci6rteR/OAhJ0tQKqcw60CM25jtzQ258a5JZys0nhB1m3V395+aofgvWxjL6F2LvLo5GFROsHP6mV1onuByHLrd/S6sjZT5KV5IGuk+Va2qOLlVCgc2nydVSjrUNyC0rfXLMXUEMQ5k6nl6nbfDmypj++Fd6V1MxG0MAy+H8yMcl3kpjQ9NYSxvWQ45G6xzcQtmEkQ0uK8Cin6/yiQ2+ftncea/a6dHdvndUjgsunzkwwRaVEF8EwqSWsdMg5MD1flWt8Lnh+/zPlap6zjoY12bBKvmZ9A8N37kI6kNPg20GyXG0TZaRMnNlxo9ZGdI346vt0Jv/WrsFpeK0TfSzvjmYkWtC1k4rkS2G+Dzhq0ZCGPQ8dEutiwmI+9ES2wLhhjzD9YiXtNKBGRYmpZfPjOzlXbLmfOM0WRIJV+iJM175UPua8pk/pi9EBBidNtP4+io=
    client-secret: AgAzzAEzGicH2Iygdot5sYsI0vPoOQTsNL0TAOaRQHbu+U/NH6oSFeCrGWoWJdri8uFU9Ye4vPRLbh7ckxSkNjso+ajjPajwyJsMKEsLkbQGST2VW7Y+CJK674QSzzw6xx9sIYNvGgLN9JQQNnN3eSBJ5ud+vq1fAxe7T/DeRzp/NmB59NQTKKKVqlxogeGZIAkCPu8iB1DmCVOIsGzwF/oOuc546xWH7gXb97V6naS+DqMdE0ASLtR3dZqbVWveJbkR8RDERYq7ALy0dYCKLVVp8dORCpTMmev0asDKfxsHMT3VAhdQppewfFPCJUVf4V+BBKPeFRb++H/Yp+OcP5ALz9TbAtyIp3p86oTPBShPSNf6rcMuLTOMvGO2UnZoocYKKHBK4trQjGCDEGy8TojSYC4orBh+NcwlzYv10gx9dK4bmOsMC9jCTOzoUKzqiEa52leN+2n2/XATGiQD9Ypwkppalv9+x4bA5sYrK1C9sG6/oKi4hLAcW3yGl1MASxkeVqHpKTM1SA6rxFyyAGrMgBmAn8KIchficqbTVpTzcCVS1sMQBg/wuZleYb/HDpj7AF9KIJXe90ZihCnazByRa1i2rujIQOVrnX4FFz4G7NL6IY49kqaeYrbd7dm96iKILHRobX1/YcMuij7pE18rWw3FilWWUx8iVjPKm+2HsfevEikg85/Nvzmdd62j+amxVzfvA2cNUUG0ymosAiEW59TWaHSmBxw=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
