---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgC0h9coBr75j4+DsdUpNpmZAD58dPom30ZottO4EQys4PalJjVyhtFXgo6m9qxAJsOgcMQsHt4RwpJkgH0W6m+jkxd08GZaTm0oQTHFjALDS602O2TffV+biC/YHO9qLEXWI23zSFTdDTFJx6ldv1MYxmeEfIOxHElqhXeB6XOq++tEwUQgKo4gISgFBJtnxlr4HuGlBmf49QtqPqxNeLIIJUX/Xv/9eySXkl52SOgSPdUjGYAz1cQyVx7MH3bjKMZS2f8QuBentj12a0TiKJ6KcVHBsvQR8KKa+VSQU016I+LLtsyp5k3rypcSL0bIRjjw9HvxpeEmt9meHnWwyc8x332PgH2JXU3wL0H/dpZtDK3KXFkgWrxUGjU7ZZj/CX7ErHC6skGShT4DzvI7BPPYPVlXbkGDTByRvfpiv8nQwwqFIQfWjy6U3Tet0SrzUmZlN0bD5po9UcAyuaIdKR9H77Gc3iGCQSoAqYWRaZFeAop1Y3ysAKXznWfwHkBdkw1HMtpkB84FVr4uh+zqr547tKTR85oOoDkBCuD1Q/9CFgHLrRKRalc/40RMSznlx+1mYqVaXNa9UTLR/KMCEIc/eaA0WjkKUW4FkGnwmc4g/z0Xkshs5l5hdJ9Q65nCV8OKYYtEJzOAKECr2ROaiRx3v0f3qzaRjSonK0BvBhfOqRv9iOJFXO7yIOoEZMnvREr9qSZG1qMEwEw=
    secretkey: AgDMqQ2ldxvNiQTkx+sL3KC3wDv2fnKlEDhbNgCbcNen10ziZ+U77Y79ZNpodvygke2TiChS2HxNVGBuWUKueITYOfFEQvddr6o+T3BKDosNE3RLTtEcd0J3pjSfKG2KTqIN5D3cEEgiKPCBFjgd1tlkZSTSfSQF0LBLuR8RTIfR+WOIvQy7jvljKql9GqDXTQAzcF2i8LW7v95Tib14EDOAwTa2S7Llz9Xb/2z5OJ1vEpl24V4bIFkPx4tAq4GxpG1BV1XvDNe5VDDmK6S7Tn5ReqMe7BaPet+bSEsdEIKnM2K7kVG6COS9H52s2MYbZ4fV0Zj9KaRh1CXAVV1jQ/6yA2cZbPn0XBtI93bPIZqmgp08Df/fa2rMQ4MHyrLVK0rcbwEm5sXueABsYMSaALQFyj5jJpcva2KX2R+ux8Ed6icKbxLm4CJzg+WCzDYqGzFDS+jGVK4AKJiN7G+d3/DdcHxNOYziS9mPkoWTIsUlXT5FN4ST2JfHOfVHcrw8Ak2sUtqX+btg1nVV9urj2woY78/kxifF/9ztZnPlSaiPHQ2qoeI8dbg+dNcxwiJkvMWMapJu2MwHtz7Sdc5kTBpErvYZ1rGVeiNY3vTkzrMEDkES5MwYrE/WeYrIrB8ELht+c+paU0zFCQ1rFXG1Z5Fqo3flXg1dmRtaCrxxo9p4p9wY33gsa0AddNkVR/FJrcAgmPyHr0gJJhM=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
