---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgCFZCv1O9CnDZvp2nROP/o9bGeUSO0NBnTUy1Xs9qQRBDCl69p/gf2c3pAnhBh5MJ8a1YTJtbzQRGo0hNy/MYZ6fyJ9KsCHpm6w0/BbJlR+KPtNThZGi8fqEzY2NvoqGa99IKzXZVLDbnomri1i9ApMbNUffpHkcfVCxU+iE/G+O9p3vyqsZDnhrj9ErmyGmymB+92RWMf3eJm/Yv5M0YmFglHToqJbWZ5OrSlNvBOujkPSG/a9iFAvke+f0+KvYSJWT6DUi/WaluHs+5tqhKBc24xlcd4YviSwSCKbwH3M3kovirN89n36OeNE8R0xZei3rW/SrakBkvnWLlkeevw3SsajFrd6FUwlG+XULZ/zYYYXtzhjEIEkWHjXJdA2wQOltTrG/Wa76mP/iSwAnEEr1E+LESb4+ynW73dACMKBIVZ1kNiulVHfo/IEBffAZIlaGAY6z1lgDVWa58/17TH/H/MmJXG2Wr1dgNrByPE30LlFM4V3bQXORkWikTiwVjqqnlqRIT91xoP3uhilJKkNyadlA4EPzPA+SthLiB+EfHCARcjOQtBj6HMmbjFGsDGTuFrUR5RKt6OrfW6PCiU/pFOxVTpJNlq/jBhFT96CQ1o5dfQLBsVpGlXz4VhDtMQwjySj/2GqFKUWGLNfE4X/JfslRzeeTFomP2EbB1p3CKc3dGgmO1MXMHcZSOJOW9pfJjK+VlpuxLua4hkAB8yFsfE=
    client-secret: AgCSPJf0Q8W2DUSfW4AKjInldVqrbUsyoWXoE94EBhCy5G5eUisurSSfQJX+8BxlMQTGVJ2irVhCTGtwTDysLIHYyEU6PRfqO4HhybKhejEgawqgP+X2FIekqc82VJZ4RW33qMhCmrC1dPO3zQ3AMtFu+I3Vp59DInsSot4FvtHW6c7zG8I2DCK57PWrQc/FtkEW27KtI/DblVNrvlVp8LzKtzoguskQFEkv8sz9mHIrVJCrhj8KIEc+xum+nr1lb20dJjqO1+d/xRt4l67c9WIHkWRT3R2DmEjCbN/KqH2QXSFNcZOhejUVtFfGJJleSakpEm7ki1ED+QDaztFjHJIsMp4yBNUevNFQe38n5ZRwIxqDqEfQ5ffeKTPBcwKmDO1vs7/XrHStuQfeJO6RFPpOZ9NjrzYpLIM1Bp2NI1FtSD5UFwDx36PCyuipcG5T1jjFEGRSHcXrpv9bnnzbRMfJIqvFDUWYJ9igNFmAoYky0fn6Q9OgrAei5afmKTayWoVm3AQpz6Ogbo0tXtXM4wOuMina+3p3l6OEqusGu9E1YaUOrsSRm8sgSnmHPSS7/Hi+ncml+p2DznKG519xa4PMgw7HCi+EDlAi5pbxHNmloiT5bfYyU8zxfHL3yt0oa1G3j6PVNlqRHIfh1pezSHahGA8FQS+qK4Zx2Sv8+DvaJNVfKoFLNxXUHAfoeb9zyEgYzxMkcgui3l3gNRbey54/QpQXUI6ZQFg=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
