---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgC2uRyXoIjwy/RXbLnCPBu1zMlW7C+SHYRjo0KaL3P9PAKSjA07F4V489gDLajKNfQYxvGW/z2dyRyAYkTMHQoK++dKIaJXXSB5lfVZrrXsQng/WNDKAk0lMW42V14rTa+pyABsJMgrX9P4Q6Au25N1TWHbcaViAFdZjANRA/e93LDHfLvXjWnNQ8nzlK2ANEqLw1EldhnTHUOciUEHLsAs9JNVrj+48+mQFqdnFcbkAcd1MJwf2/pS46Ks8xVxI8sjPL1EWx0JXEiGtgSJ+vKVVuM5Vm88yfcb2dfjN46jzIiZhafi7iR3l+nCEyd9rawaM7M0qItw9sFNwP2r3B5X3kbOMDptZ/ET3p440iVsURupEAHy1Z5oBrH+3eNCkpANBm6WufmgvovLt85pqiYi/zl+23vPhRF3VHWDEZISD6N2+LsInD00gZTjopNMUhLFtBnVttEYSRHuiSROUnQhvNm07MpyhKH+VTAx2rCi7tj3kmf699mQaHLiPwcZjfEowbJmzqSvcFVFwRaojKvHMowu04ftmqTq01EZNFqU1gtncQsoSnsCgaev2pG9wyRNghTSucbuUXCOVb9uU8Cfx575sG2pngbyTQRYr6KePWemBD/gF00vcxI82BRwx9WI48+TE6XAsTOei3b9rPAy1Its+2JATXV2fm4I6l8fkqoCWXdeV3z/dHVZJxUJajWwH+mhGLz0DJE=
    secretkey: AgCumZ2t4bscCuz0YLOW7z1LF+noFV6NAv09kTxqXH62U8h5v5y+8p+wNsFZP7v+I2GRStvOsSouUBtolZK7MYGbJipu6gD3fR1+9pUmX3TXIZTGopQMfjBRnOIhaGWtw/aX5WAqX2ej3HrWOpRQb0v3ceFA1bPafHElvS7iflZL/QdCoDxqovYuDThuJne5PE0MMZyT+Blff5pWHOXiYn974+kEQZB+P3oyq3x2leYUIJNcrvlKZOZrMKtdwAanvF7l2VZYJnIC8k8ve0FUT50REXTZmNBXvgLW7Q3mSE3ES7KBUDvkjEf5YCk/F3a/i9Ii/9B1N3slKNIiJlER0J5rDWZ51s+B9Ayceafl0Y/QLFd6uFBSL2wQ+w4fJo5vdabEdWMljxueXVk4P5V+INHMvGOmTgYhPZZhumZC0dgMFbln2gddFW+3oB222yuQBFC90QeVyVgMgXXbtfFYnEzx5WtJSBvhJ6Ci4V0O1XunwOy7fzSwg7z4zQR0t2UFW9aPx9NnbxVjDx9lM1zdkaQLU9p6n8O2qzvKPalUEmTqi2dpN4SWPNGmvz31iE9WZW+bxz+vYhYYEIfgcrZHRJC9smYK3RP0NtSeyIULidKB03EnYNpm1qyrQ+HFzjPw6FMc7ZCuW+66xy8LH5iFEA2GgK2pYrZXmbdqiENfk5s+lPvx6eT+cCsVX9+YZ49CEbWulfQp82rzfO4=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
