---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgBqBXG9qyMoz71bFzdWWRU5xBw74L/FDt9q4TN9L2C5wMrwJAsX9UvM4SfnzQ8YpBYshmcxdOKM/CrcGO+48pM4imM6GBxCf7TVwWeO5bzg9eLOCodJqDLset3ktIoKjBbyby64ibr57ySGYd3A0Z2kAA3ODM4owFvAVE6Rnf9qrzzctDfFGQBd8AtgAX2mAEKJmvtox+jOq0a8MegtCVEa95gXmn93cDagC9/Cwgym3QvrWJ6Y9xZkJaQ8BtRI4oSLp/FEEKeCSlPFTgOlAKdI7tvotJSJmoItUMRUrH6a1DcvG9POhH5mccu/bKRLsoOgQtBf+BzmDOG0dLsBPWjRjfF0i/DyKcSF79pTMf13hC4Q31mjeZUgOGv/R+nJGK6IRaEj8z9a06Cm5GxEZtr9NcZxwrqzghZbbbPyCJdCXaoZia8QCIPN+DnK+skGkL9DvLJxiFmVtWhF6qw5+0nLK4k7au+tMgfPzc7O5NJYIDcIz6sJV7VH05KrgW6VuZNNRsWwfCODRsiRvB/v8AyqJ/IZAPSuGQO//DbcHc5Gna7j8lz87i0w2TT8XD21IQXiL7gDUYudzMBGXsO1syNQL834WF9qbQdr51gBz/pOAiWjCCkz1mWFZMWCPX+BG7H/fKMn2emnPsjqy/ddQTFTJCAmXbvmA3xWFWrq1GwETVhKJif5Pxb+bBHUV194ouCpfqaU0SsFe1Y=
    secretkey: AgBaT3MldCgzjpPulcgTsIDXvEGNoxzFcHkouZ0GZQTNkolgh/1fdsZmWMIpUtgWm8WI0XFuWp4/lFVzXBs0PklQgkFh3/a1Q/cXPqrilt208vuZnhVwxm4tM9wrWFN/CufMgsdshobZa0cJfECsU3X2BCduhCaCI/67R8egVSqf1OnNlKubH5pTq5T6Ur/+F8Z+FM989i+cSu4rJlczGaKZYXll8njzpf8jNzsNDJkQXug0566U0UFDIOerMQNhTNK+GEwFdxV3LU0xQdWHttHyjhhY1NhYE5+ndySVOkVeGjvQ0UbKmhoQsLnWqkJ9W26zbm7sxceje1FBsRJwfP1Pno9n5imdGfEPP5VVLjhYkbQrasfFStQL8tpxRl0HeZ0pqsjhdGMCeiHw4AD3Hs9R3pFmWjPBO+28RmhxW7lf+oSHUewzuRPwOH8r5hgRBE6oBHAXgex/1IQqEan5Sgl3U1VpTIET1Nc6IZM20zCieEH4ar3v+Yquibmvupkbzeg2AjR+9DmIBFRjziTmnaviBgme9/NgWMnOnDAuH79iYsJjNGe/jKp1Y1AbiFanhOodO2Bqi4Q+ut7/fhzmafLaK/1532XKy7rwpLLtXdMMt5HG9/FY7x8iqY/E/4vawNQqGTOJMeGDpymVWLbhd+9CmLQMu8CImqakSn1fLglmPdxYxq17Ld1SpiI71/DiIff3djm/tWaDUAY=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
