---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgCAVNnY3johvkeCLBi8pMSaFJLPib/sHo4M+YOGINJ9dxk77Ak+LcwqaBEbmAGX0Gp6guczx6vHcWwPvmTBBKA4UXcwuV1P03LJhYxamYx6X92HHhk2JXyPYYWO0ApIa1wIf8x89o/BiaatItmzAN4vGNRH0xH7iRigLB4uS2C0NBENLV3eqSWUcjvb9s48Z0ZOUbW6FsUFqNT2YgTto92IdFLRV72W3mNVWkn+to+pqiz5nBAMGcNKZ/+5zIs8jt2ZYupBdig63HRTVsrpI6/xUUsIcRQs7VeiGS1Mq/H4xWs1V6qEx2fdlzMZ5+5CY/wqgSXfOo41slekCwlPPQN7X65vcZchfgRw+T+2L05Bn4vDqh5wpnt2MWrwTCyHlkP1lxED1fJf3xHrQU2v12GzVAx5zA2mk4I+8LuG/8yFbeYtqjiTz8WWbEmITQtN+Pnhr+S/GuD1Gny50NCDV4VstLQ4mNnfUClSqRieRYECF3OmB+obGn66VtJVE85YLqZ0Faai8V4qdWJk85pTLsugcKaVXaRQNOZI3nTHMowX1upV2MYmDBC7mQG/YFmHc3ED1gdTyo9iOR0+UEeqGgYp0cx6Gtsc4cGn6Zf99wHF/8oWHvcLJIf5eI1l0XKP89r5MZsuXjcTxNPFq0CNxN1+xsMwmqjXaZ7xfe15XHbKEA56fxN/z6hklLIFGlSA93+wS11riLlwBHM=
    secretkey: AgCFcJwyMacD5m9LVzI3IjDLp/LUpkJ1g+aoTSmeVWFfC/QVY3BaAAvOKTkTn/eSp7EscICPcEbI1jNm1V/bmtGgHL2U2ANOXPt6uDwIELAtq/7LAezrnvDlKj0na3Y6hefsGFA5hwgQi+5qxbeLPkg1NyKx3XNzSxIeuB0ftv4lF3C1F6mYetSnWWAQIRIl+LO4F+u3u7+RNpf8/PRv2WovB89meODBzIF0cp6CDgvKEriQF4NQ+tk22VVlDWH/m3em2SDPUA5nm4i8yhsdvYhpW7oVyxyMOuMEPnY6HZ9IGIorj5RW0s2UzCupW0+faBX5XQ3Xxggk2+VOAxR03G0Xgu5KItMRoct9IqT7sIfTIgsthCIIMbgeelmJXhyWOjYF3tAyKDVU+z6ZunZop1SyKIhjd3qQxeGoy2aQ7YTxL3VTOgDUvw3hrh18F5gchXwmRjrkq18T8j7OcQXD6IRfUN76awUsKRL/xWnt7oziInsB1mbGwVCsmJx35szPZgDWWXO0K8O4YvnrdzzR5rpu6BM3785/rogkktjEc7omc6TvITJjVkMMR74BqSwADYxKMjS5IMimD55l2eDmsP/OqluBjj2H9IRHW3JYDu/YmmiRG7m7I3ZAUDsGoT5WRSb0VKYnIqwCkm3uyKdlr/toyM0HqmnAHWWdO0zvntATHHopjMApie0eRAGNGXyw5s3yCDVFM91HOlU=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
