---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgBinx/iKzw6VcLc01gDv4zVJoNieGv8FrMM1nuc8WOmqF+RUnntJu1yBOG4PkJzAz2GLpwWwL6/x1qqdumYXnY6Jbopomr6BABhykLC1wIQPxYKaexY0ZTffx8EnCQDSkMts4WvCpvxrfgtbRdi+YHf2lmbMZNDfEVi2zHWxaHfE+TmzHObGFqX7iZKH6bThHDln0ib9hCGnCtpgxYFsTonpzC4zQhK07F3Gv3gq5+O++AyQQFGFdvPkTZ5lCEPr3x+y71drRbTJhtcq94tVUP5VSJk1J2kh8J8lYq48m0yx0UWF03U2S+Tl3e8jz9SuShE0qt2n15gSmsM2KC/BJTa9smNIijoOhZ4TUG35F0brOzsvgE81/z7Sq5+ji/OME8MpxE2WD7tl2wwLh639SILRmwSnp0iAdlL7MEksnE3yx+80pnguAl1eNr6D+kyPD4lXVFjqxw+AY+xRigeUoWmiUyYMuqS/PdaqJGCz+/6FQwrsw20xRINvkWCsKBlX+z4jciqNFOeN1XPZ99HanrREoxK13ErX0dJHsQq7FQQCx+hGYgUZyN7KmS4b15jltEbIQw7RmAMOcgb8aOBPvlsnotP9DkUWJJd2tTogusywbMgRr1zEDMQAVPm/ERylWi3zlqsrGaToL5Ge/eBgygzlw2IZ1bIkpmhzq8r0zM3JUPIKREXkvNVyVk/YWq3c8TNk7onCxC+Ej4=
    secretkey: AgCzVTib4747pVwgsvfkQHgRTBUT53vvZ/xKaPVOWSNeExfEvIVDCrUsxuw8GEH7cxbYzuQR+b0NOLyDKHQZSsFn4jkqTb/p9WK2B5Bz0x/GPzluvQPA2btKVQ8svYIdViU1IzgV8pugaGl5pxRizE5itWICpEUHHFV6Dmgtdr5JAdU3T1yB86tevx1A99dO8onWgv7aePS7p1dI34VAuFriv4w8+zZCcAr5oKYoecDZ0cKT6T4adpmARrUJAXwa0onMRVFpHgj3e7HOJjQBUtA0UKu1vpac+WoVjb6VEMh9I0pjYsSDi4m5dRCywwX9zE/cxY3AXSC+VTm6Zj9Pi5ggk0ZDtB32bpLdTExW1VpNLUwFstfEjFKbLiKvhjZIhJE47oxN+2ETZ1vABCspOWBtH3VIyLbXi7HxkB92fS9T427m4nnjn7j/Y37kGfjUDNSPQf/UfH+TwJecPFgdB7qNxUJwl4dha3c5qSgjGuWpl/HSbhC27689Jn8EhqTt+9vQMTdditmNidQw8tajDa/0XG5gdIPyaGsTUzGPLlClxT0R8Dgbv8hPe8XP6h+9hFWtshyGopAeifc82uuvwSBpEcJNH/2t4LA2WWKxjN5tffMG9TeefzO1hvNJzHOS3YipviJWCDvjBCifvGmyRBwnsEfvzxLPzlNvTnNZAWziXcKGy1uyvO6V0AFpgtDJX2gKhAGr5jUmhJo=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
