---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgAys6XC0A4fjAGIO5CDpkttaJ2TexaTKVnPWHrWaN5OowRM/9yCxboDvHW2bX3BxeXry1m+vWqxGcdVrIzaSgJlEssrhaVDwECQiesy4AtkMwtoFWtKQPeXDEh17X5n3mnmv8zOUdiZQSDcBVSX2ZjvB7PWjXcR3qoIvI0d5T98QEkSfuy/vgRM2PB8ObLjfS10SZunvgMN9H17vWSQamxW9JAFyYxJLbKOksvNfYKYPA88nUWS3jq4XIyneBUTHo9CtpT/OmP91z4CcAuIMe3dr6YeW+wuiVXOCYJWhPS4cS7E1bSdsFR+EYfXdsl/qe0gODVSVtPtBEQTtsy73QZ1UhTwj9b6TO4EWpajrdOXZDy1NQJyKZaw+yK9tRcLot2K9Lsgjo5dBtZnqSzkR5bJW1ey03EcftECVDQ3gia9amXlpoy7dH94dNcSsyICVEo8C9rmsYlhaqueFydSrbiq/V8NwYxxqTjNGH6xE61GxOXcA6Yn+mwj0jCm5BrShd+ebza6tqzmr3+NM+PUlC8Ci/PyKSALvEMd2YueokcYMGIN62CxMDU/64rII+Xmj1sm3WIY4NA35s9eU6FgUdy4ttfdTw+ZhtXouchiDDclD/k+PMlzltdoUt/4yCGlt1JVWqcRvflYGRDM1OLa0CJDkE9HxIWOHTZoZbc8+Z+9JShw12nSced3khWpHCoudmQYHdhnQ1YzDAc=
    secretkey: AgDJ1+s5qekSMuzEHa/4OnMraf+OVQUdmqUTzLdlekx7emHHHpSEH+gxAXQBaLoel7S8Y0kAauQWG3RZYCKcrKCGSzCj4T91+GuBqOecZ8YcRh2ME4wf5j5pDKXkUpXeYLbTicwatsu/gauO60F9LaGEp/5wOuyUeIVUO12S5ABEHL6HOrEhsU+GjuoAWyTBl4xjG126Ve3We3cSiqbGOSuI1hlCtxarpt8wuxv8ZN4ANkTGzL2kgMGUzUdSw1I9pZ0TlwPYvVNTY4JC3DDzyvfl5/5xU2Y6bYA1yNzydr7+1YdsYiBFS/wr77SEA0PTucUwSfTtA+pqBGEVvbZxIq0CYyVgoh1dzthe4M3STmC7VMkuN+cG6FHxPeabpJVOzzIhUReCDcyaywyFwSY3IJLmUO/oinVdmzsqpoaVqWZFSjxW4GhQ/CAX8EgHG8D7mcAk09+W1jXFm1ZsCwO2LcScTKa1NJJsa+ZMNAp0r1AKOhBQs9tH3/obHQI/97SkBuBHQxYR0FPzKC/3X0AEOvPTzdhvvFxOE1B6vbSR2xyy1PqpdYZ7IKRQv43JJqKhXpKPBmx2SBiJAkrWKZ6+XWT0+AaArQtriaYu8HEQKPEBJXzcX/Lf/lBswUwFUKaTdihR2d2Cbxh4kp7aEKdIkTgOyREGCD1jmbn0Zl7XrNoNqiAMGguEk3Vke/bKmiruhP44LOg12fdBaMw=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
