---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgCepEtc0IV9lmfVTKAE32BHSEUB7DMWdeQEoLbuUWVctcT0S6Lp0tGYBCYASNco1KPHB0ZwFwZK3OTE4B3+jPXA+gf5w/KXLO7SJ4kBRYFVMnlkF2yBNod8Bf5LmcxkVLDlhdsCEx+qsFpIbK8MEn4ZYleJqJwFzKSP5ETQwtYg8J9gXtPJxc+bRW/lv7KT60IUFOwlHcWdBzwV4whZkiPnJQPXlaFwXi3ylEfJERiu6b7mskfz9iJBqYZdUx8487qyPPlzHIyzn0oD2jaITQZZYY6J6g3SptgoQl4bqkbTVJGrA6d3740AM4+GDmBuvHNIUR6cBvepLx+3LsNvVzqIdrvq4z/s9a9WvwRMnSXGCo4w2+dtyFKz6LSBKF4EGojWijd2wZ3Q6rxW4LqdkKVTEXp1kMSJkWronD9aOZUZvEzLpqu8ZxJ4Kzrcaic4dpZnlcsKhcDA0jYzSdHztIFudSEmyk1Idi9VXdj9+3l7NXMuCbE8d5monA59vTtMApeZlV4JTOm2SOQnespCdKQtCSy0nAOJPgB4klTzbo1oq4DXg4GUqoYJ8bFJii56SiZ2O69vG0a84779COWLhkiwVqNmPR4pnY51vgJJpkXeF4sCCgNrYl8IdJ5OBrIrAgPRWyR5qNJlAo2t2HTVkGkq4X9ncn41QtUZGXWWv1iWtDa9wT3aO9q7DUykJv1osBgX1dhFlpOHLaA=
    secretkey: AgBv73tFVFK2ewK0pfU2ud9bniuctZOD7SdA4Yg/4+vaWPpMt9lfpxQOKO16Lg6iDlJ8VYE9Y6W76SUpv3lxg3zTDS35Vs1CItapOTWg6uarCo//un3bTqvcZGEXpWKy+Xmq+JKVb6HLOClPp3T0S2AMyJi3MWlBxX0lP+BoM/5QiTjIpgdkpg7yzQSfZr6RfYXpQQ6dZ1jHGcbCf/O6jB5ltlmQ8bWsvD3PPMse7lHb3aLMWphdmxChS0e9AelX9y0d7Rx+nKf17+XeXwFMvwGrlf/IR8FCWlSYzOTwfUFawqKv0aqfqKS07TeyyIzIspKCGmpSGHi0MJ2tW4h4D5i7CXmxUjFBpKihplxr915ruG+T2RJWoKmqu7IetguHRluc+2E8epSlTK8egXwiWc/k+qeTggZccN0ptsDasolx5N3fp4l54Qnc0NdLxfHER2hMwrkpcokyUXklAfFrVhxlGJvMY4Jzx2RksX6hIiem1+X/qpC38UnnKcq5YlHdgY+EJYivAD9iXA92O8bUbmNNxmLRnit+AKdWT4V7ZwzjCYg2qKSlkW8tY9ebfs5I4iV+Z1EhpWfop8alfol+hiHBqh60soA8yGr1OKAEy9VirXR7Dyo3w5qB4HHDJTanTmz2AwsOUD0vYgp5l+pLq3m2kGYtMyAz72IDUHKbxfwqwH6aYVEAdEA1Q0ASgYxlQ8PgIPYRlwzR7e8=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
