---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgAkx5NUHCekt2sqGAQiLVDCHhsd0bvbOzyDESHH5XVb0a9nd453dLpP+g7N33VnVfO+Xs0s5M9/jc96e16mImiqNZZuRLPxn5DT8ICxfNxebxk57uFFyhMt2Mi1yRgJI3J/M3Av4w/rRqDBCE2pyI0T+NlJ/vtABSdsK46A02Av7FgzkrO+BSgWNa7xdWP5AS+ia3NhBGgO8h1PMngybHuYyTqbfnqngn/pxAeLmrxivdV20mBl3b6//x5lV7QWor4k9cHStLzYz7qqJ6odNJkk+9sD4/heg3Sbqp+oHz4A25DwmAFOK9FrUxfqRkJU7cJsYg6tQAlsy8IN5Suwpu/kg9ifR0qeFpTIhUM2EAs4qarZYBqhRvpuf4vozLRliKUCA5CaesfdgB00XipoOvP6cOL+p0WqBFqjvyzcHk3zPtqo3wQIOoiARiCr7bZDE0Grsd1pAYs1NuSoDJmD/SSUJ8zR8gxBCljvsAXOnbij0BgfZ3W1WSU6yS4pq+vJHKbfVIE9/ScEJzJfryeYfqG1V9ghdMiOHAY33YblyD7WQbTO7szffb7kxh6rVAtPqOs6WhWgWzbMKBiO+klZTT1qqSor6dWtjno7e/dyNPTGi7aJTFdAgcSHphuEsJ5zWNFrwJQyMOEU2N1akJ0Mkuz+dAGNBQAzW7lwcDcnnhagk7+6xxX02D8Ag5NMvgtIDTeEZ/cgGQLgzW0=
    secretkey: AgC935IGtaLmJAXeseGXI87xNbgU2pnybT038F1bCSOmlGaZ7xHR0mLuoWVpjKGQSHYZn+E5ACd0KmzzTiLmTMQFSTcIqE78x/YmYlzBkBUTYDaYtFWdZQ55g3QaX8bDXxxO764hg/y2JaNrKFf4bH9yVAD0Vg2szCRLbMZ8CX1MHfv1bm+JbVJwZL0g9HRYaDyn8YJR5vmaQk/8/UzB3WdAgcki46juI2xf8gudanvUrp34K91/6LHPBLc1yx0F4oY1SIDTn3sOX/QB8oaGsyvxdAlX3J4C/+yJymHnioZGMg2M8nArq613FQXXbv2IUllgt3a5lA4u2u0a7zPw1U5P7J/cEvHkGXa/UX7TYcNADAp5/NKExYlYJY2M41/4OZOnTq2N2rIIyK8o9pUNqcGSxHmXDs39733pJR0ceWFDxq+di2QuC3xOMFEyLdZ7mf3W0wrfYogs60xhLmFQkuZfF6TN+H7KJDVEwxOBwBouRBgk1UooCApv8beeBKoinfrYzuw9LqCEtW836lX0xKG5J4h9i2vaptxDh5ktz/0lE4hsQuKFtQcPsLasGlP6lK5Qgvuv9x8ORK3RlgCZfK83WOWXylfduR1Wc8E9Sprv/PcuyxLa8qf9eCjGlcDZSkaWS5YDGJ0oj88ZnoT8v18+9rHsqtEIEM4h9WR8cWB0wcIMY7koesbA/stgimzKolmfwluPmsHrzco=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
