---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgBCPr2y0JfPssfICqA4tPsCojLD1KNhTBo6w3twTmCPvB9YXGrHibfvzbw0D5MianFiwQWl5ZwQQ6Qm/9VscTXfLhybQIpICvTrJ97lSe/ng3RDgUTinxCJI9GZguLGWRx7JnqvhnL3TqRj2dqjUCDoFEQaNy5tXNauEKHaqLhgPs2PcZ8lct76UHM6nm4aSM20k8m8Y7/iYG/Awv12H0ZMyF9aHdhzFtz6JzAxg4MhYUDeldjhW6jSEv4Kq5NXYUf7DuNdwH0M5uf5UDfTRWk3lcjZmCU5ecSP+h+x6E6eJZwJlsgCz2Ux7UHiYs7I0rLVRFzjXr6kB990Vsz9AfqMynm0To8lNNbget+++zUZ7abe3bpVxwg8VhX+Pqbh32YQXlsXabA2+c2q/w+d4+ozlulzvUpWEEmNJYs/CLGsRO4eU7iUJ+7M84Scbvf+jLjyoXY7KBJIX11zVZD31GTjgFNv5fxNssKXP3UJ2Dzk+Ju5C0E4WC4Br+qv3gkF5qNTMDKcQmt29/ICf5nVO+oo8/LoWdsnJOT1XZrwBo7EylSN4TCHDNZ2wjzaK1V33sKzvA7QD9jNjoDTTsCx9Oy7qIF1q56kVU8XnMh1INFvzGWakawYLWnzoDeON4b1AsZ4V3F+iWkqiNI68QoKP2F3qPmBMJjb/1NkgKU94nSeRMqYlvPNHNJSit5ERJ08jIO4N851nwMlWNb6gGj79VXkDrM=
    client-secret: AgCB7rv3rFuCT/aU8kp545/lqaykC39xy4Dvfj4pcoPf2dbcf9KvuO5QO104+7GI8P8A6S15VpwN2LPdFSPrMX9WJnCIkFG+NLaOwCy99TheGezsEy7UNyooPMZHWdHU/+3CAy7JuLAcTmaiGbAua0PioJ/FQsVUgIJz9V3omEiqU2j18WFy4cXmrkHA4qdrrXUNJpeOLv4sp1y6rMn54J+eGbiPHylSqgW+9bBVSvqCZEPanZ6557cyTAJfa/SyaOFc+C9HcN+uwdgDubBhs+8ndE50V5jfOLw+ZcW91uO7Eb4XGZcVO6wcbJjmHWdABLn8dHD+YBJIpZoUahHcLSirQMKgmtECtVJvgvmZyKNeQxnPn3eGGCbP13dQBLefViYRvDXeteTEFzBdCZ2sTcJ0Bj1vwxnMszQpCYcZDSHxz3tGyNQe+sVip0IbDgDl1KjbpLAaVXWgfeR3kvn4xE/MUreED8tvW6CLuiC4DL3jj4xCmwZvzKmFZxnSLeB27/ytZ5uS5UxymmuIqJT6lZmKUztsL9eSmLi7hgszzauyidTbnYnLbPC3VKgxjYCetaSqMSoqRRhfeWx4igivbRITYc65LObkCjl0w1O3u8i3AdJtT8YDhbzq4pj5mXaSdee3x2YsW4HgFqGc/9kNVhgOYojedM/wxmTooTFL1ffZ4x14mi+gE0RNqrmXEpVk1dUlt248idxwMZEKk69KiEk3uZa7d6VOdAc=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
