---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgBmLs4qYd1R6Wx1xCVY1gmYtsQwWtOPGZZCkahBIUHGLM1nc6PaB1+mqbMtv35PaFifXVnFpS/qmBkiZLrQKYeB7g1sg2IQaap7MZ0uNi7jZU04dm5v6oAyf2TZ22enW6K/PjN9KdAnfgmhoKhscMwdP9TesC2oHvWmvpuO+1QBVd7QkrzAOJDfT0iudGaPDJLLpMcVth4thTSQ0n0apuqukaiUEhIX7SAO8R/9wWtkrZLQIgTiAImu5JjIgAvMTkK6W5vZhaWFkZmjHH5kkiaOcq5+Wq1b4A4hgqupFUwTmxY/I5buvGqG9zWje/Gqas7GpgLopeNeL1V5Yhy0b7UAN3cvM5YPqnBEC8jUzZ9tADv8Qu+goqO6RiYhLeEmVQagX/uduE3opxysofBel2MS2+jqIG+vbPeCNWhS9HpnSlU/RhthNeDMymaEhpV0Fsz2cRxCxTSkXWsFB3VxM92RCilH1eZ+ZNgG3xMGInDGD7s+5tapSgfoffmnyUBB14GEk96t0y52ZdbSnL/wb/25JFdahRHcO//9yq1H0tr+QRbpHEGrNN5HPeW9SqLRyKpF05AG0eIUoeafN4BvbxLEg7TEfZb09+nfguSV8Pv3LFpc2N1XoYy0Bnc8E7YdzLYl4jJ0esgTszUjiFWYarQTnpGYfJkqhyOXIGHePffxIrjkMEYqiPCBg7mC6Aq/UcZAfnUfQw91pbs=
    secretkey: AgBSDRLiGF8LdM51Unf08Hx+lxusLHxHMYhx6pwOJXzhDjc+9GkjU7nkwCF7FqCq4ES+oGAvS2SCPtnp3z6OHhU6KtJMZkX9pTzpnxU+V7hp7M802NG/VUsJWkc9vly/c8PWIBp9M929WLiyBOiAyME3CvPokbSg5fs3tBq7e6BT8EWGAp842puckqGMsuY3m1hD3FuzZ4yLHAEDaWrTIJP4DYZyrD1y6NsBDU+wxdrOhTkrElzWz5007R8YM2Unk8rls6DROGuYL/BcI4DoecdNe1p8Wz/YlrEael++CCkPlZit4B4JRuJASUUBBCnY0glR87T3ERilwO5mPh13GxbWl0z4CiZc7GrHCJAgRd/HK5QW2niI1Rjx+62iRs4H2EvbX7fes4ejzyK36rvOonQURaG9fu8xZctX5cqqN39xn5c8BCVDydlCfuAthZUE0uoSrvyJ3tOuB/mTpDtN0MhW7mBnMKEkIBOPS7v4+K1Oha2p5jI8YeEb9YEd0QLuvLTE587KE2n0Jmg5gCByVsWZaT5HXOG6+PCAGEb/McLsO2aGtU66T7VNjOtIEK8Q88We/h5coaPJ/b2h84Ihv9ZcI1MjLwJTMIAT49ku3KagPZ1LiAJ5NqxxVXdaR7pnA0YiLGRkgwfGE8sPWc3GtdLVmbcxQufQ5CuClhZ83xNuHIQUVR2iC6kfuLDQfBvE1HqUD72BV+gV/eI=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
