---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgBswqvYn6g85gonzbLjU9ibg3EWHvjpJKgDpjuhu6FxtKsp87Yua8eAKD+Pxv+/ZPF4CWgK/7IYRGdRZmealZ/83VMlS8n4DBMcemKO9fFIpwdb56c/ShGvbEPN9oE7aVPcu4+TQ2w38cQcsCnO2pH9r7f59LYxot8ntNjdjZmEugQySxMmJpVaWzUZ5mkJi8Yq+vVKNsCp0Z9ziRTVuj+bke0b0C8twVdAxz3e5UsBFpKNtYyoq9BDNZN2s+3bdw+wZ6gQSe2Varql0u2P9CYYu9rZHi0kad7xobTpO1IjDna0gQ5yJiznl4neOAe36Hx4jWzJk/HbXDAilSnq9CTkvT3y6Nu60mgj9qTVMsHCmmRzAED192Z6csrb/6OWZ+Y0tcO6ukRNpC1SexAO+j8pVM5kNVFxBPHOGvx8OSke87pFmKXHQcxxGT7o0HJWx2INN8XKZaRnVdqN6YpOjYeMIAb0cJy3foHTTe6wHHIn9I0weUjUC+7zlxEkZAGVLJxJazMoMAEcRbwRXB5d2hIuU8KFpEQywQvRrf3utXvODwcpGp37NPalpqUyqgisX2b+NpFfIjE8gjVR9LjuxmZ7j4OR0CwmlPSU+3yLbLS90I38aeqWJjiZ0hVM7SxTVL8mWhtvV+SojwcvwW7MC1gGwr22jPl6PWlgqqjKPUp+1GW+2QiNpzL51aQ6h3ZW6lGRW+skok3rRodtehXu+QRr3AA=
    client-secret: AgCvE0qsamcIWv7k1TTyo1pERa2aZI/eePnoyR09hIETUxBrpoK3eqQD4VYh8YDWxiGlOgVDa6ZJ7yM38z8Ed8JkVpAs7xAwJm0KhdTvRRR2yEmWg/PhDt/u49dDPoUwHLLJv7C5jzlf2b6xBpYVsbaN+kHz9qseAcz85oDl4ODoTTlzLUH8BYZIpewMxE219kUISOVOC2FrjEa8NXC7jUOtKfXxh+1GYHVJIFD/ozA7sR0ypOa+bG0VsDbtJMp6n5Ml/MhO25HgaT7u6qoH9VuiVpZXM3p0K41gavzf2+CljxbVGVTo+/g/tkfH/kOj5N6D7ED4WmZGtvhzQ1pOzUNf6fzkZGLdeXz+r+ECQ6SX8j7OxRJrFoajACpV0tVCtwEr+XqzQvZkbFRTllJoCOFr2S95LVdS0y4kCwvAseAFvhxwOJryHpIOgRBIiKb8kIjn1Jq8r3v8esINsgoBpnkW7ikqFIHmb/Tp1Fel03huG/lQupITAAB0MR+F85GiWrwqi0tcsFTccH2wB/81Zcs7F9eopiFwYfoGCUvxw7W3xgBDqkTPoNN7agXl4pnpjxhPgRbW2437HTNn0kj9G8VJZLPffCxpg1+p9UbWa9i8wMQHsFgttK7JlBxRMQRywScLPY/JdOA+zYiHNwiLjb1fUT0Ot9M16avJROl+NuTa4VW+STvSDW9j/4IoMnHNSoV5YR6BX89A+m4VfwJ6HIbXgNzwr054bDE=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
