---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgAZ7flfnfY8YOyaYgcLFYhDbByqOrpawEgkUv8tz71sgD2XbJgOy8NbW6+y8ksrxqheNCIs7DwaGybu2WD8bT59XHI12Ma8a/p4tNu6xF0NPWJwG77QP/xSuUx0DmEGW1y55LFyZSxHqglzruKjrL6oEW6441yXHli+j8qwlYa51t05R4AG4djG8B/3RhkeUY//U9PD9MnaU+I5mjPH5w8cE6HOAVG2jblHpAsL/GVqGBmfvCzZs28eCGB5Dt8R4XJdmp1PHxJo6XkEgnFk+y8FO/AdIq2Oiy6ULTerv6k029Hj3iqV6tQznt564i3eyi5QxUmi1UB8k8gw5zMGEY35107ZEkywlfebl5RzVScdJDV8QLcVsk0wo1YBfyCWTzknrccIL8KiWJQ2hVjnzhkfJYOFTqFLlAYZHXa/t7aRZ5hfnLitbvDj1OIUCTerPUqX/gPh2GmQTmM+gvIwXb+kAXvZpGUx24Qxcg9s2FQbeAFZvG3//rQ2vcYjvnzhS5S/mMOVlMS2AZ9J1bfCJ4xT9Jjheumec3OAXpZIfe0xvNnKqAaJTPGhqXoWMXH6/djAKHpp/WutVxw1BOE1+YYBcOsdfBavb8wQ4jqil65jRhfd1v/4ESsGJzpN5RFeCfDBs3IamUsP851MdkOFWma5psaCR5rFlqeEcY9hiOr4RDQf17/EJSrtO7H9gYhpnOgu/sVXT9eojeU=
    secretkey: AgBunSJfhjGXOmd+mZMjDrRws6YQQeGTK5tdtDfhEC+ILHsGyutxCawppV1iVTq0ya+ZEFdEM3LggBmaJC4hARJBsyk9IXoIkp87SQcKfUp31EW/DK9HnSdSZ7fbd0xDv0N6+eHj6ggQnyYdo+POD2WAfj4D8V+CWtAmWVVpDwOgZOYFYNjihCBKQscmRf4rM0K75g/23pUq12nDc4oJQWEF6PyUT+C5Gqip9yZH4oZUrSqofjGNFcr3AZEmUvyNFLTsCComeUL8OdmpS41LeBp1vseBFZFgVGsJLPIQE8+WEJ0tvs7L11Qubf+3V7CjBjhl0AD9QAFGjYqm3HHl+I1A3BFvHsYUlWAfMtL5iUqdc6hHfMuXgg7daA+tarCL0ktC/ZwUUni4qwYNBlZM1+IWxG7hG4AH4IpQucHO1riQ702/lPKKtCp9w2ynYxon2pT1oSF8ur7+flFXm+Mh0uEVfJCWTYufkB5kVt8aHnqJ+Ivemh59bsamtPu/0fzn5v4RFKM/cPaLPii105LgtWOzgtce6jbHJcEEMh0xjpYCGrGn6LjTJb6cP0iTv2Ky58LkVF3sUnq7RLQ93ivoXafRpgsYlYdu19lscGmatCv7Mh0mF6YAI/1VYTaROk6y0o26bWcgHePFGa0x0vxpI8+OaSFdzT/LO17gMDbSEGu/YWhiCuhBXfcc+pZfjdddAko9CKR5foQiTzc=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
