---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgCPbFE4RoqByKR6ithIShZR1uHtn30EwOWOfFw9d3RZgL+kQYqp1lHkQEN+ien1mYkEP5d+pHHXnvAG1YUUHwnSnAMSxfZ+rWaKzrzWhm78TLIdiaKD1HIZfxQrgMy7x01j26GsqqDBHALlZc9D/x/sa/g1npnIACfmQAksxw52HaqVUpU/1PgraYE8CHr46uVAImXNWBMDbL4Zu+v+9f7pA9p8vtph6isChU/nQmfHbG5u0pwmetcjo1efNbSSZmprF9cpTo1hkkG11F4+OcDoEeXrrcTN2T6K/xinsNAztMNi0Kzrlba6bjnU2W7sh75GpIiVWRI2uOiIqNaUGEX+V/x+DBgEspmrLUQYEuH7fa2Gi+vsWTrA6p+XYqPLp5Z4Yol7DvCkzX/n2YSDwQAkmkrU/XdxnulHVkKTw8mRoCY8xQyi+Z1ihwjQJOtXLizDYCqZ5OXoVfe/qlyRnv77UeNqW2kubJ7xivV28z17ndzTWWhGf/oWkROWJImuD/YEXRuNgU8dxf+acRXTdhl75o2x709MsgrFUEpxfGioXu/oWn7RyAhRGuHZFBdDJcWF98U8ws9FapbUjHhjbdlJ4NCEyWyp5lcIPyKImwhucAQkj8BaCozqknPQ7o5Evd6vuy73g3anzrTriR6yUvGCNyvJrjhHHSzJrENuVejkI9v5kMdTeyH2O0rD8VKV7ltbU/sd+ugNKLkP6BPc3SGHwoQ=
    client-secret: AgAr0OaEWsHMCZiGNIKAgCAO56qa4gP2aszQp8vHug237ax5W1qms8mRng15XmSUM1wgpTY00h9vanRZUGR38GqbI5Skq3WzI6qhOpxtolSTXp6Tr0+3gsFZNrX8nxBmMcoc6R4+tD5nq8YT/zZtbnFX8O/1kud1r6BFmFaQFRAYhHsGqvic0RTjOJbWz0by85iuiu3u0DeRwXH8A9JYiajjkUfUwXOkA/YPXX+XBkUsaQyAUv3QeJUkp7nr+4ra5CyXCDndd519Jg4fH6md/EPiu2FyYbxj8lpTpwNd56Os2mhvAo1LAhcvl/GlPegFdGNgCwj92yzt5rdwq07yupwMtPjWhhbH6OS8QssjwR/d75LwXBFZzzNJTEyKdt0NBrik5T6xQUgB1BC7LXRka7rCZkicvtEr3+crDWWMtuQuW+XY6edZWg2bCOeQW7S6Yxr/d5kkQv0YwKAh8+yD2SjuIE1JyaOzq5nYW/6rE+B2Burj+eDzQA2TBQK5Ae5j47vXcrTmubCcrGIsW0UbZW5lLn2BzgGQtBZiXRqJCr05GyU9vj6nT7vGaOMQwhXFdqNIFt6jmYD2O79Yzaorxr/7t1W0SfDrzjrPOxd5Nu8oc8GX7D1EN5uqh4kMolaPtrdE2lXZjgCVH/hY4QOyXmSlntFPWEroVy1U8emZJLeHYKGjT2ku27XEPdWG93S3C6slJNXkhva7NZx7VVF/aFPL6JEgy77klf8=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
