---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgBFSWrcYc9H1x+2uKLgh3o8TqqwbM31yNYo5xpfQRjjvoUK590wP3L8S1xo5IzmY9E5NcuyqnNE9TRw4ELUXwfmELkDH1uMZzjnHyP5L/2m4fmgrnonk5re6EPzviOa6zB1PJ0xoBrX7K5e5fUeb0dVTNLKHxkyE2+r6tC0eAua59Hck0KhAbrPHGAYuXxdmQtkALOo58oxIKemrPZHtEnXii9nevVaRpHruPqyJD3OtkSnIqGNfAABhKgisG7wq+lO9osNEr3FDLFfJB8lY1Ch6/44Vm4PfHv4QRIolZEQpjWSmgck7FXQ+yZOJs3aNxtFwbOvPgd4IJ06PTkU30zbLZwwiUkNYN98Fnv03b7TROeIg4r+YDIXIwCu2W4ZttgauVd3H3rqtIGxPNAwuAlBZxZUq9G/6nmz0/GmURGRbUK/+xyE91fjghkVe0arJBWkmqsGWG0SBIwc01LU5DBT91bnddARpH0wyLVaX6Hd6Y97lEnwdgRPoqU/cssGY15lexANCIUp9hHMw9wjgaddVi5xufetw9GvqJ9cE3sHcr6vLyihLOvz3iXD7qt2hjwzXraO76LHmnEKLuX4S5gunzwY6IPHbr2TTfGH8w1ZC328Ncu5++VjyODOBvJzdtR6HHHwg7KOFxHKLe5yckOBvf5jq4PKRN2YI8VWzX22v0MdA+cVCHtmkuf8KpDtuFS4VMaChJK8wcE=
    secretkey: AgCVmDiI6Ui8M5ZMtMP5zoPJfVLqObCx4xMLYrbp6LUj8VO0DfDoj2GabYnrY5yLzJ63HdNrDryITohYrLixuYVhx5NBxrfJnzYitIc73pGn1Z9ML6kiZgtwb6Qg70QnLYzRUhmU9/Y8ps3FKg8CgV7QW64aZxg1KrWJwyYUXcf1NQ3fViFMJqmOC2jQhm+lDO0O0uIR1BZ5gqgOiQSg3zRlZ7aRtgKwOTwoY3yPuNWZPnjJj2HBqiJf+PoQUyl3255qyji05giuuK4uxIvYtnF5Enng206k4s/ADEfBsXkGQCTR5KDIuBXIQPqRbfI/RUvVaon5+2lCqI//HOJAQ5ZWuuh+HcIU/mfDWyJaYEXpSH3i2Iey3TFhj6Mr5cF8koKY+Eqt0k+CV/mEALrZsAa0Udn5Lk0342tQIwhoDNpeVmTyLI58cF6QIypjknIF98e0WS1p0LQpeP0cR25k1njzJTSGPAXflXbyI9XlMniB48AEMJRNF3nYPugZJZJfIrdjQoS9zh2yLV6TdI9LLDCUKdeuM0rzDKhWQb3LDX/Z84QvE5/rPrfmvgbsa0K3BhzbRYb0NkPb0sZYEevJJGAV3Iavf9Rn/7BDvPyJePuyaRsTFMDyfJD68ed4c8YllbBfFODFypywAxq2UZf1WJ1O3JmogxcwPECmGg49X08IB4Lrg0LYsgkHUklSXCGF3eegP8692QoGVhw=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
