---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgB7st0qTDpwMudYbtAgt3PCKbZhsPrQleZZ+VTH+YkeThSljnzO4k0xb3FDNXkUNEVqcVFVmBaJRajbRpb+QMO2A23gRj2WyCvXqiV94vphZD0cKUi6bIC7gkCwPNeYS/x2SlkSdugIjfp+2nq9pL5w+hid6r9EJ6VavW84T01pi96RFz/5MAG8MNyh9x8QFf4PI+SJvTSDzK+shPiUcFbJxTHJoaEx3JVtx6kGHZcHuZ/r1+kATXgklEV3FJWgnYZQ8OSK6o9PM1EIxD2Dh38fjGb4mlb40TOE+IXgXt6DYc7wrVDDHp3Dwfkqil5Gi+1W4ErwJ3PbwWZTUUbj3nNcO1XiwTig37yfqk29RPzzSeJmH3qGwCejt4WhqRoWjdFwn9sSVnm4QQvdZT8ntg03w9Cmlg30AQoKz5b0/x3uCFVxosUHu4r2ISztWnC2W2lbF8sSz6UEEVeIWoF+XiRtHoa9MgC/406JSr0L4F+EMKbJaEcoOdQKCjv2gNXrdPq4H4TdtiylcTmgcQlSJMGerUFAgf8VPcZU/brV3l8SGUYnYSpZiXLmasFbui6VZDp4pFYMyaagDCgJedspC2sdPRJNJcl/8vVTZf2lwv2m46YajaxOQCE4rTVLpVNA2HMaMXSiVVgNK/Lth/2JMYwVTL95UhJfyUzt+kcwTNsyEOYo3QaRgTVO/vdk2OLg55vAXMzerD2WRC0=
    secretkey: AgAEUMz5MDmlPX1La1A7HlOU3LRz7+GuMdJas4Jbt3OqmPBMK5+RvksmHWwvzjLyI2JCov9iS/smEhTGK8IjWqHW+Z5Kvy/gukvh9nH/l9hihxcMBT5a2vg//BIhTAchHj3u2FhcZMHDXpHlGC+n92/y+Ts7NlqB2WiyGBQ2AR5Ya0qvXhA126x8H7K1lp2NRJiVoWnmwu3P8DJwAdUkuafpad/VO66MRbgCJlcoi5yKgiSRr/oRfT2JUQhY5cbeG84IxixO5pnzyaEfuArwWbbUGkgFsOqc/qYrqFKpNs4BAqNJ0dkFgh9v2SpMqWhADU+G4J4AOFHtKULyFEagm/AGZDhkLs0O5vZGfwRxZFqig+Ljv+pJDI5xFQ5cAXW7PYURLm+8djnGQUuJZGiRG+x/y4YcTYWh1+47RLtQivKYPSHz9dwOUvObJj/qZ7fHOnIKJwHRLfhdYaJz3YPzBi9l4C5Z8kU9mF6XZCVPXd3V8JCuHLYKiGU7QmP+u2iN9Tc+RuIVPBqU1f1xMbPtf2Yq9NapFM7ZOdpJndujRIOvoJRGvh4C3BG23BTo/x7rUG3vHpYsnpwLn/7gDrrbHuXcy/+lriClAmrELWvSN/ZlaiZx09AvY1j2mPdmX/vPQt8bS8qOppjluQ2CpyPULtZ7lON1VQnupIIAv5t8SzVNdP7+DCRpbPZcIF6eIZND3MMB2Xl/cQJqFb4=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
