---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgB14Rkkdy+zjTuc9s6V44llpU/tL3NgucXbn9AsAhuZHGLUo800YC/tgODbux7lMRmPeb51lGVKaokwNeapinjbWCf2PmYxIbb0wWs1omEiir0Zdfm7VO0E+i6NjnDu54VpFz62y5hkriy4NTRbu7glNYqbZH8c+YhQ9Oll7BiRSZBxmy0zVBqZd1VHKF55Gx2Nc9sckCf9WbmHDjrMb51awZcnEeYD0K27bynpTQ660J6pGsM+rjwaXe7WqQIdml+3GLpS5JPbHGP0uMWVCfyVnkAbEjxDHFwXwfMb/1j3zdvF87lm99sfPx06MgAqV1KynzkDao4rx4sVOMlyeKz0rA1K9FKkOVJ87NhGGgq/XB1vrBkzhuVXwwErJHDi7kDJphqCVrEqOLv3KZ6MdQnIH59RKFJ9YLonfR92QJhZasiskhIIf4KzZiKR02rQ251yuOiBCPM7jSOw3zCFx2LbujiE1GijWH/2DQCwd4rbduuyar/Oejmyw7g64J9uRff7XN27N7glfz57CG6kJ1FIto5Lagy+jIoFwa07VKBLb2gLXhMrVi9uII0BwDc/Jn+rCM6ce61I8EW1PpX4osWSD8qAlzo66ad4Q1+o6rv4DJp1bATsZhY0ioAw/kF2RwVw4xVCCBUCVHyfA/SbRRZNcLyXPcXR1wejhymitSyVrMBm+VNwR04GFkHlD8kb1NiZXAj3dHPohaM=
    secretkey: AgAROBHWc+4Tz3Pvnr1HIlkjowd+aGfvHD3vgbj4ofAIENS8n4SSfP8sXrFtZnR0Z5QVdy+VAlHl5TQcdsJbt/BCmdL/cCBhFDMs/AtuuaHna3jXtnqo1qaKOJPhWJLGGoR3nVTd9W1XMhpmgkxbnY2tBg8XitOT4ChPE8YEQMcNutCXLKq2kdfm1CeHE0XcXLn3p1OXCKtxSrEvy1pQkxua2IIrfJBi87MWaqjfUzhQgyR2TtX0IUiZ4MTF3ybcWVSyrq1FCm+2DXTAVKsHL8N7kNVbl5ze9m32lVXHEiwULIdLPgBb/JB3DNIIurmqVNOjXAAt4D5KhWRMElYG2uDS2ETPfCGuPCgE2+29o2e8A8c7Eeox/liKuPzc4Gj1pGmOTUYLitso4Fgb2JlBtYeDk7QTi5rKFYOgviLGuo2kdZu0+sR8Dr38rh+yQeX23OGNRv62t3qxMmnSx8D7SWfZeTYtPbOgqGTKDvzWq4HUHMAoGscm5haHgVTXwaeDqJUvV2Jd3mUPXsXw3ObQrz1fXKcIK1Bsc8pJoUe1hVM4ZL7TunvcqpWONw05H+ds8N64rjFc7kuNlhBboNftRFpwIrv0w1XTVmERy8gPNXTHKP71kubZ8D8ucmLJQ5AZWrszheJ1eyUaWk7Qc8c27MARKYFmUN61jmy5nLshd077iwtq51y23to77fWRQVMOCL7A+ILRujq2v6A=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
