---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgAWihrjG48IhlkhgYdbWw2qimfG4sJ4WzRAeDv+cCdZYYzAjIR8QExwvATlcv1Q4AxJ/hamC2SRRu1+fDtGGHs/xmR1q515bLT7cDnY4trHFO/J0Ee7PMNxeql7zoZhnfnRZnKXOuL4fLgF25Jf4xPP24G3TZdyWWGLQQE71+llCQCOJ2FBCvM7+R1prWAQvjLQSy49e3DERspsOAQO5fsgomUCeS8XOm0KoV9tjGY61Yo8GRE5FNWC4rw//ZSU7HjZdV98VZXynhW4QeJNUZ1k7kBtUexCWOacawhoMhrj804j7a16x3F2t6NFI2Jq0qFLtPOLp+JYZdynGRSur+49R4Rzn7CgXvcpjhrm6nid9bfMSxw/7jRNzPCDoZkUAkml9fMoqOWGVLZO+3qardI3NHP4bM9jjxVvSmjUkqxwYUfkjl5iHMhVnKDDZAdOVS2FEOWsqp9i4rPHdo4YmXVfTzDNfkSfpxOeIY2PPFqJUa/DxjpCM78JmjgLe0BsfaNWqrCSnYLdgxefsqxlHyQsfggq65h48+gyjq3T2mfyhi3vV9hOzBAB7Dltj7LLgkULlft1pUOD+x693yU4rA4A+LP/Jcerr9zYiYtVHyElr2fWpSp9sCA5sv0z+Lxq2RLqUenBJmATC4u3cppDaD0LBieEHlahNYdxQ8SE0W5DskPNvclPO88AmIvjTNy6yeqxECjCsHk2U2912zPcqM9Mx0U=
    client-secret: AgB57GH+JNps5QuH0omhxAfTgP9yQtfhDk4BxI+Lhc7y6qdFOMGiVx+T90ScQP/i+tV9I1SXPfJ1quF2svGWBg17ya64HYavNr4Onc19YuHQafHggw+EnjevgEI2waGpncThPUBx5kdN+oLY0/+AvKB0w6QH3OySClYf8K+FJ0DL/zKZNgefvrGYuEhRwcLAFiIBnXpNgvt1YJ1MDvlqn9ZkLg+dNAtCRrifBRqTjILzIasGGtDU4PJk8RQPz2mawfXPTocRSSXj1Q470mrkCsmM7xJl6+YS0ouAImRGO+LlKtFtXM1WWr0JIU3RDlC1TAbihVlX+tnQI2DGUCzTN+MbK0RztM09/fL8+xZRSGfvaEB7G4ldVWIUuxT8/QsHljQSlFyf97bk9+xSHXdEOCUrPARBU0EMj86CkPSgBJIWFvRTvc5p7qX+R+DdSAuax0l1jG85UwslmbK31o4+38Xko5sOp/7E5FffMOnXEN/08DzNkCtUsGKGu16b543io1v4CBHRc0IFM4pbScZzJwrTwFnsnYjI7WlUjHA/zg05MfRscLMrEd1lCR0FcObPr8RVtP51an0PAppp8VP1y/OtY4htTRXzf0myAZan5zw4vfTtojlSzgB574WgoGv+YCZX/w45jayyoN1jwPtwZNapcbNiOYEIbKi+lLPAR5+Y17T3GUiBKyFPrWqswNB8idkS2XX/YRi7SZQeX/B15x5S5XF1jEvI8q8=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
