---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgCmMMrRuKmtPu8G9ptsICLYUbAFH46ironrgVjVEUSXQZRxyPnWrQiR1HQBboyOS8J7JyQ8MPYd/SRXbqwb2KieSzQQFEMuH0LEQbkgGatF/Go0seYXnGIdmzRHT5ihG5y3G19zVaB0sY/6ercDBS3GLKZceTHHGX7n0hszIK2HDJnueqhSFNEYtJ4iGx6MsSd8EOIzIsCPz/ROAz75RAlSFfHr2bDP+l1CXaqynTxpl08Cpfw2FpnSsVMUcmtGgrZzvsE8JhpflCRuVdsjAQEgUN733yEFjcEwwtdi7kiPEFrJ2X3pOBW5Hp6VJ1QzqsZ93Q0da+E0x0MH8y5hDwWXbyrFz+sQKY/Y/Kj+A1Oe01VJL9/hImvUzeOHC9ju7Blhv+cn+GlVeyGHejb6XWbUbrOkZE8m7PKvdJ5lfOWO8LFkKoBk4iajypAe5s8ZqzO7mKw8bIpxiGb82kMpe1XKwBefkOwLXag3eIU251A3sT5TI6Y/ebGykeRZOV7x34/SBmyAEWNCcZs8fqA8PS95yVeOB0trkQv+ZMRynVF+5psZutgIfBBHGwajhk1nnUrPzI3xkJCt59n7+8ZQek6uSB6bv6LqsWtZWhCWxellNl0Fo5MB/twYbWGD+cGotVGBu2TaIKhBaUwj5O+50cPP/hiH91lG8hZbSAJ8qJ3EEf8oTDd0oOpfgFfpJ2FX6QnJqUFS8AXBU4Lr+pn4ZhxMzwY=
    client-secret: AgBigNpDa1C99DhjubpAQP0WGKqdlFdduLbdyAZOgsdGoMT5ZKQdNa7VMIBBSTfHpCBoLRwZexjb+62lBEyeG5lBMH92Pi7m/nAkrFKFm+K/m9eyUPgcd02SPSc1WnxuV9udD5h5cj4AavpAtkaaEDn4YUTYPXemLHZv5x79p1eCoxeakpTdAVHgq+An1pPkjq6rThg8x2UVyjdaUHOA9bon84cPxa5Q9ooN5BD9U+hw46wY3NsrbqOqyD0WKD1h7HltqUnl6xbXJ1CGzq6j5awFmCVEDRLG2n3WWaIlZZo8rrctmsW4mxdB+SNOiFveoN9v0w3rxB2NzkRZjl7w2oBLvn8ZWbKnSEwD6gVoTS1rT+/bXik+rIOXzS1k0D5RdaKPIIEyIlBTMfJSZ492YLgLuaUsgL2kfvI/tLiHepScqJmdJnA6pO5Qf5fDcIikRZ+0s8ZQzYYLQE0NPeuCOsJ0EhRVlVJq1t+iLXrHvlP9XKFnWeNTMkw2CNiUGa9j+Isg8a9HJqxtI3t2angIIX+HIz0XZLuwsCrpHxZteCu+TlYrLAGwr5hbbF/UdXz6MdRlGU8nmhErcF5qMlOK2Xj2LEdo1/rafsW6yE3vAe+4fAGUb2DKLKV8nyPScxBT8+x6XTVgzGUz97Gy+YlciiDx2Mlnep+FFdU/0pgqPNTCrTp76KcefmVZYyf4nxF43jAhkRdmAPEdLccQmJPgoSPvHT3Ron0xnGI=
  template:
    metadata:
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argo
