---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: argo
spec:
  encryptedData:
    accesskey: AgBFOrr+0hMzD0HEjXBCTEqAU7QAoANESrT97K8t1wZH6sCCvMVE1D4w2HNtSrmqWptVAsqoVDH19MJpKPpHypKADMHVX2ZQBMzkbhyezC2iuOhQdhgzKGMlcF015nwWDPlAeiOqljd3ckL2ZkjtRq1XCdznQz+T37DpYSi0hiUE1+j+9mHjgjFAcLsJg5Uo35VEEogrX9nOHZrRlFx98DzaadiO9H9tr1FPV1eRsuGRhu2wbpRl1LSw+lpZIcFOvsiNdzIn4oUHhIRhfRPsvbBOLjVhUv2BXJN6wdGLrUmvwio+1gH/HbfI+2r49wMnvENBQXEU4ND7juBuR44Shv6jYuNXSnRPECHwNv9rEhKpfwfZiszW8iZ9fJ/BFXQCnAviYPPuVcP6BUYjsMcmUYDZ1zVX84zeJ7j68kc0Lj1YJCZbKO1p4wU3HTgefjdhniMmviedhjp2lfWsISuYlrmCR4G5xPLraP2W0N7NCfTQtNUHGnqU8RGPI9DZqXUSOOvObvy0XmwQrq4cx+s129kuzXZ+qTqXIIrJxGHZTY/gX0tpwqhJHr/wfld/NmNzFudITpSV/DVsC7KmdxWwnxkX+I2glonN4Oq+uR56PyWQOv+erRia825ZbJQ593BP8bSprb91P3NpyPSPQDmNegxT2P/80KVxeEyhd+f/2XGiJX8M+R34X6BRq9D/xwJlpDQyGfUJqT84pXE=
    secretkey: AgA/F9Pl30lqdQAPyVDFrB04cc1ySnFgZUmn4YZ64XP2oL3fj1RH6LOyiJMJY8lWvE+i6I5E6uZyepTb5iNTM5z/CL8ZzQLHbHVrvnC08m9g9hvsb9mIDHqcMKJJSQh1i4hnvCMvQ8nQ7fugvEzNyVhujuish5L62LCFHawu8ck/Fki0HbuU3LVxiXm7WTbkFbAPHBbFg+XXzZ69WosSNON9iMaG5wH8Snrl+JXCR7MO1r3tfIb5LkxlwCjcaFrD/3J99pTlFlHcU9RypQdPgvfNzINmf2nSa0Jp6rkHB9jcDmsaUiRp1DQ5/8JB8KSJB5dHBCj0NNQEHBhtpLZD6EiV6PQjtAgJKN4aqiXLNDCKbjGfi5X1mMrUmy/ehDEW/d/ZZti5Q74VMb31dCCqa5YS4zKwBsuftDlL9X3mKZcNVgRzA8URwt4onOn/T2Ri7f8kGycRRHfYlOVl0KnfB2x06djHgHrAgokrd/wOYqMWjzP56qsoRQU/DO+78NERQsCggCAwd1sfpH1+IBt/Tw6cscmmmcNR1bL/Gsy2m64EwSIXNuvU2wamZGtprOj/H0EnuBE7H/TObcTqEzvyrqaj71qKGFkGXvXJv6XiPanw+Owd9XxWVUihC3o0FhN4/qZFCwNfHC313Y7ypmDGnFQpaQUbFeljWd3KmKlMpoJR8fQsG0B7sgPRf6tgnZa+Es0pxvGbByfWxEI=
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: argo
