---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCDuF16hgIFVw0UeU6MtIO4XXb2wouOT4DAwG8ctmdGWr9T3PhCVAvVT504QarLHb1d9etJlLdyTeAl77zx3vXgF5w60hKkO8WLGmPDNONruf17mXyiL2OIBuS9Wpy6hKCP8ZeWYMaop2wSgD9NdbqpoqIUcY2Ele54vc/QURcwm9RA+qIa7TQPho4IoEk3rvJh/rzf+vftHK6s70LU5RMOvOWD4C2iwlPdG3lCC+93DOG+lkH6UkDHn3aLzrA2pkTso3acgvB8UOyLtl5aeeTUrLp0ZTRIhQC5h7ZPBl3R/AEMhSSlvUBSzt6l9WZAtlJ9I1ze79TKyzbqz+8ISIqxjPfnZoUaPdgcOeDUhy9ap6eQXdcoFPBwNgsH3zumo8OqoUn2GJpPzz+Fu2YsBo7AxqR+DHifRzvxjJiujpqvNYqiet5k9Ln5/cRe8S3cQecQCWga8kHQkkyslP78U+1d2VpwTU1MuN7g2rWhk90q76SX6r/XI1ZpfQJ3wk1SaD2mYqm8FTwlCco0CeJrfKKBLoMOFV0YTbJcJShwMkb9HOnkL/K6/bL8UTmaOxfZppTp1C+P6I/RMqftH5GaV2tkDceJ+c7HMkZK/0Z2xpIyzHO6Zlp1nN+AFeKSJvlWk+BXhG0HLxs2fxj9ofnWybdl5bWbWumDg9rAbAJ8DH97PEWREiE5Zt2ipN2V4tL0JdwuzkLjah0LEGnoz+5yt5GolPhV/PE38P2ktjDRcmn/0RISnktEhwULQEhydrkOt2ThLqK+GIlD0OINSCdfEnALPkAmm/M4ER35THDVxkfGSHu5KS1UHyk6V00k7FdPyBP4PBNCYjXzqPNPdIot51ICJbXj/IPnHT2/1Y4j5ApCuLSURvii0Ra4XqwzJ9HZXBXSFjDp90nag4EParI6yBPsLw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
