---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBKeIvkIT2WKwCPLNIA1oGV6Y3gTv4PskQR5BY4v2+iIY8e83d7SaRwqL88kB6iAJ5i2O1XwuUItK+/2Q4Pi4S4a+r1i+KFiB7ieS9v/h4PjkQqLjN6Xylg/sPvD2mlnKV9nVYndqTCYl5uidjDjASrEdaecBFVKjsU+1T2yzKVBJwpzR9NzwX+3WUZv7eoTS9W3peaC3CexhFJjccrXxllQfT15L1NuCzgfv50r+34V60sYXzVeuPvAjVxpLsVZBdoZehD8W0D6tIY+t3SsBY8sETkrqvESgZKrsEK+3Q5jBIKdCM9cjxiQqd8PahxTXkKMlYRnRiq0Zf3yXA3wptWm6Io/vd52a9cSPDzfNPQo80Le9fHj1NKnaItSP8rMLPy+seV7en0W7d2Ke5zfFDEin45ADXif8DhMzdmKKRbHMB/TUY9y9GQP+zAINW3xSYGjsIphOiAtNu5NKiYx6QzT/0A9G8QUjYTmTEYsQqsEkSV/wW87epYT1gSYYvqXWXX5ELlXDlsxI9kMU6pZj3I9SXJ2fW3f22JPGr97Vy37U2Gwj8HqDnBSSr+PQSEO3mgWl7FyXOZnCohuTMmjVYoZKlsYAd2o+0X9u3VKO3r4zX5eE3ny5/V7YT/DONFf0GXGJn8j3TAS1EhwKj7f7Kuncozp8R3K10Mg+JP9EFc/fBklzCb+j4TqdJ2V344wDtLMEEEMXz++agtQSYeBBAkGzmNNnFDA/CppExIqqb4SuWCyP3qbqMuQ2cgdQaDNQC41N7zFkmXs/0HzRzBW7kGzVMV7DUvAmPAxxr4zp/AO+6QqbyGEc11wrhFi3bUk+28RXNsLsa8sDV8qsyGV66PxEpyH8H4BH7Q0g28lB1psWF/yakFFbpz5Enah7VX/Re45zeudUhARvRzqnOy0XOVkw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
