---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAFtdKaV6jdMGs64KRL2FZw5MQBgIp98FFvQ5s1Rlom/0lfQrUmVIfZsnKxa1oxP7gqXO2L/oZi0IQzS3LP1WlhaNQ8H1lKkfNA1WEB1nVlXFQP+Eoj1138j6wCmnE2EJGdZG0KtGCcMmmhG6aaaxveWy86fXpkNvEcY5noegriAe+Xkk5cunsUpgtg4erKyIQ8Idhw8DBvC2RYuZEkp/GmVO/e5vDiIUeAwoAHLtPA6j0QNnLCY8iIFGS/TvYEGrZFJnJbuR8uH19lOaomZyJop9RA21M2Ms/jyTgdWQtV2/kwgvnaBtMJMo2lpNxkbwNb+GwmcRszgLkTqK8vHbp/i/Om+hGlFUZo2/QkzEN2x9ElMUu5PVbwec/Y0z3nfzRxUzdxIkM3yDh+3kdUTqNRPYIthSmQtryFC++nF8OTl0DFiCs8nKn3G6tRGvou2AHF+CwOnTh86HMXs4ODJ8kAuwXx7coB77FKObrVgb9mrU1DuwUgYy1zxum58Q0URudjBrK4X7qnIIZGjwow2CS3eIwQetJ4p4S8G56CdNs1q4GxSHWbtboQWIkTMVsnVYtSnWyAD3iGhP1ZWlvVI/z5jaUBpVVS3JZXcKblam+5VC2QbMc2NTjSFbg2KyxIRHPpl5dlmdDWtL0O8PYbUudQU1aWZcyu+XEWwQDRSSBO1uFcW5OLL4SqdluAVhzm3ZduAwW4TKVDK4TLytc8N4ztbxo1GxqKtzk2tDgf3fIYVtYnHrfeOKD2skB9WVJ3Ldq1BCx/PcbIGLGO6KWsYGGYF2eGKjHDF2PfKbV+nMWy4+uvK19EyhGjY1SbecunrVHBWEFfe0t++FSKW/wQuEtOcSfxGNuhOWaqPy8n1jydk5eVgeC46EIyfG1QJ8+YGyiWJbHN80mIPPgpMqd4AJWWUg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
