---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAEm2I7EQdlujwNIwmlCXqZwUsy+6BkJFZMFb13DK8i2FB4znMv7DVPrBiN0cG93pmd8aw6L1rONm3eydkjJ8ADQFnn4/utlb3Q6TRUug0vJ1PL7dXcaMHzDc54ClzvByXkf0Q0qCKQKL9OwZMjgjLbT3oV9hf6isO2fW+v3Ou6+n/3PHUaS1hGykMxJ+84nh3CqGXrAiVpYln9f6mfwK1/Slu2XRUgahCAECdA6dk5v0bs7xjCgctc94FXrP1+vX13Weyo/JHOycAkfHlW+GavJcQTAJMwa/hfUprlASBk1JsWzBotBb+xrgSa+7OpBio1wFLaGoMg6Qw7uv+J0niBVZ9z5Xq3DfBkwq/UFIYL6sCCZsCjGZXa5vxMx1d7CEQVBxt92Ce8QgTDI8V/nxxZCPa9MR/FxsoY8AQRCs/tfOIOU1Hr9V1JC43olfpRdSIEsKBEnpHj1xJzCo9xdRUBKinYrxSTvFsTocgyKzxntPxEQg4YShN64YTwT9qu8KxoBKyTgwOsPPB9diRc07IhTyfpyy5WQUgIRdqQUik5PHMycrTbqP3DVvrSqQ4AcSdE6PT7/TyN3aJFpAtKhPkGTBdkVllwHjNQLqMSD/uUoLe/bLZTOFLuTJ+QU8x1v3VzKyatnEhv/pfUa8d5CzicdrbigPCLmT4eraxFULcNB/VVTxpQVEyzNGpI9BsQG3Z1lO21P7yblzuTg+mLKofbSl0lIWmB6RQXfPusP4iBMUsMSBk23HHY5oBGIpBE1eeyBu5zmPga0455z/k/3ySAnRBMTmuIPY4ErTNHqr4IsmNFloMqRNwBdCgu0xRDU75yR/hCMdLL4i67wF/f3ctNy6Zw7GBAhRaBtdEKF01uKWUUNqd9TrtJpBrzpk0c8mT7hUvNGYR8/kANs6oWkC7pZw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
