---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBhlf4hr0U+plzjmwTJSy616SYP3Adv6TDGj2nNvXHNndL9KxIqLl3q+NlF8USdqzcbQMWRWtMdO/VAMASPvRdpsDHJ61bQhwaQcJIwfGqcxZUVVQSpEwHDIWX1e03cNX8D0pFhtQ04JmSkWI2RN2T3Ws2lKfB9X/GoVuhDiTNYlqraT6fSnEHSDLhUQYeJ5DQHkcn+z+Cjrm6dwSQqTpK685IY5sLXxU6Km0I1vTjzc9e+gGW9KDN6PVKY1Zcye4TZLqxFjqvjJxVHrgaaP9QG+urtnulMQPaEP62kNSQ2ZrFGVynhRGnt152PRopzHCGnKQWyAFaW+03XJupnhgD0rbPTFvXu+ktGy6SY9A+XF7mgc6z1lCEGbmnBYUpCzsTrHKmuGYgmR9k1XaTVDlfP0SRYgU1sTpgl6J+zb3SYgia0Xtls/9aoAub1dS5Um24J9hMyj0W7QgLf+2JcNp+yG0ZB52G8zSkHcL1SBS0m2RQcPhw0IqBd2N/el5gb3MSeef/Fw5lfdh3Bz8y+0DX6uQ9tf42Xfc1DsQXJ66qP3Rb3sIKzWykQ6yaIHOpBUrFBFRCjz34Xxg2cul7NRLMgq43sQehd4G+AfEKW9PL3tF4057Wq1TydAjlvgfcrMC8CtAMO8WV/vJe6CEunPnBhbRW252FEuOXLkE6VUhBQkhpwx6ziFAx5bvLtjvqQwMh+86sMSs8yKxTp7WdaPbXMs9Y49EZ8DbKKz22TlsiKfapmC8f2i0ygFgqJB8dlxJL00A4ffnInOIr/9808hyFKyskqy9tXKGZHRyEayDgovmZtxXIDjXwQ9ijVlqWbomW3tpSZi2Ww4cCF66Tk/QBi9KLw4DirUnC2Ojx2sksgAyBFlqmICe6fOud8Mj9vg82MHYMocEU/nVRum5jVUeYPCg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
