---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgCZ/29CmtBxZxPGks2n+0RmJTm5PL5DKL6WD9BphgQcxXDvnfuwZv44kUYtHYqaWNE27yRLbcu50O/MIWBwSVOA41iQ72i/rjiXr2vNvRvcXawbXHObeFT8XNAeFm3pMd6BxeicufAQxa2xK7Uk/SI/nVVmBXisoAQhwEWa976nqLcizhKgsqXoZ96CJn9Qa93vsOrIE0zOLJ3nXh2pLk9FjeREgETBerB4mICwhrzkFH/Bx45kRcEp3uj1B/BbEfIRxdVjraBmbItmyp5gynBhcGQwF1ZwpD4MD0bk+01/SPgklIqr4aKSbmTH9fpWFsBWrJizMkalgGTBVkY+/QNbLu/eFdle9eeifkCoLKo4xKWDs+jwD5YYsRtObdmxsOfcyu4Yp/lDxGYDm31s3WPE2YE7yUPlv+Al9R+x5SOorvToGDxpG+ceaehiJIeG6h3EfJ0yqAYYm5ljZ7Pt9EwFyQeUmNKGDnZHEvZAu10X2/T6WiitCfCyxWKk2xuARNm9uqEaT5RGC8tFGuW+u2w/ca+gnXQTf+WeBdkSaqBaofmnlMMOXGFyEkL8SLLCVyQje951VAbr9zd98xTSazVpx7Pnkuy9/hMLKdTF2mMR/xI6PNXu7kgw1nOd6MyHqLWtn8kNeW9eSRKfc798G22CXebZ04KaSFJNZLsjy/MGNEAVf3py4z617GRzHoBgojsBP7q2ytG5Jy4z2MsqI2LQcDQjjdMxUtwlSqvsOS4o1+ttYnIxaVVH
    email: AgAZjkfJo01MMYz3PkQdFwl08KJJAuQbrLMI/UYYJJR0lKpx9zBUdwzIpNrr55RZFLkcg6+iAP4R3rjnXqGISp3WAJauZYUhlxGqBpn2xcF5gmDhZVM6HYCfR1O5cKFI+xFla0obbAasUcaqYcet2/jPbEKv4P68YW2WGASK6ZKdMlivjMLwAh/SU9U7654gHUhj6XdPkdfH20LYMWayGxAC2iRhhxi1yCuDLA8+Vca1ys0hv11KJH5j8Dr+PW9Af2yDsrHsO7BqcLpwiW+xLhtO+HeFGtWnw3uOjP5g36KJ8obi1M1HNveI/pBccNY2Sdluu21IPKActaI8VUfsXVJmbFZ5K9M8WlHhq7zk4IApXOnuAfbTMsPNs3RdOoPQsiTAJrKc8lKTvoy6srMbHY1OpeXZZhw0yaMZbCsB6AHqQRH028H/IM37fqQaGcLAioF8MpVLnsWZLRIi174RYVO7oA/8E17jPDOviCUjcsQn+CNEpWt26Pn5DsFjLd9KgZG3AQzymwsuvYSiYOzQFZQhXjP2I8uIKR/Z9fkXBWTwN/nu21A1d5gLPROi2NMs5rqdQ/lkAY1Hl91/PpfW2sAgFWsgAeHTOBuaZFAc19OgNdFeaE6E64vvneSbZNaVt/S0c2ak9QHnl2PNDNDBrrgsmuGgNbd0/gUfhYcReyYwT6mh5bSUDX1km+acxEstxdUa04fqWZ7yyi5A0EjVwmW1CLPbRr5P
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
