---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCVtsFUv3pHt7pi7tQq02hvtdsFU7f4KW6WrV2LlIaR4+Ddt1iKPDhTk4SlwC+voG3ouFWP+jwWi0rEN3Yfopn8O/kV2tq++NhUp16/QqUOuaer/lNCfuE5FnC4t74nu/GTXXWxfqmZIZrLSSZQfikvBKGqAhCPcEb1aWi4bHvKIytw+153UOXQXXb84m1sbZjPFsHsgLDqlME6b9JPC7q/oDjPC35Y7UWhweRsdpgQNxil07sIrbUWR2gwiS0dr65LuFeLeciaP2+vqzCgdB0qphCItkkqdG35ZDo4raPkA/gz9L9UaqLxq7gAFHtbZLxFSzkA5/qokZUB/awVFCQpJZ12CcVmRglEt6+CC8sufpNLu1R6po9AiNNkDmupskDYsC9nc46Y0YR4QxXVERmTYDUPZ41Lh0jwqZapCtYy7kfhihyTgkkbFZDBhV7+AdhKu/7YjFmwMpKhQwfkUuyC/ROvCWG8gec4uRHCSamcEPTtONn5YSPxWqeKzU9/9NzMo1oXW6FGfxX05UsPCjrjQZLzlYmmZfE1JrwKoryD72Kk3O1AX0lX4s8fNPSNGocnqMNtyGhz1bDt1Dv2dPs86Fx0FpzyiYXIMCfWyOoQZye3pW6WUW8g5+FesNPmBVNz4oOoaSJEuz95FIXK+SITxDWVvc0HxLuPcnWndBlXN/123h7rnk0bX/zOSRXW2mt854UJhesRF7ZxWabFYXsupbzFLAfD0sRQ7bkKeDXnDhvYcgE0Htlh49P79aIaQHifCLjftEu0Z0K140KUFNwBG3tOJfMbpaY0NZ//NGY+BWZSeuTnBPA9UvHx18mCzjxyUeYZ2VsO49EIeusGxv2CjrV5sKHxV2D7Zg8B5ZLZjHyuOdFqiKvxLx6+l0B0D+lhFxk3RqrReVoLw3SK/Ya6bw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
