---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgDRENQHaZipwKFEXv8qELnArjqvcxu7r/e5XVe+jJS1Ve278qcut5pAcfV85qJBnu5AHWJVZplw2iuDC2D4Knjb4zDw6lFxd5fb54cDsQAwo+PD4rNtTxpmU9PJzD3Xl2WcivXl4wXSyvsW9u1vDv+WQF0R+iDUfvCX82C4TxQIEDZ5UtqPemjo0a4NYizu9IIPXdOEQMpaaFLY6yLH9UMwst9ql1tcGx9pbqjiOF3oQgKZM/n0KdhlMzvHvE+mjfK8ptqVzcDE2Fb3V1u5Vufetd+3wPbjJE5eGhlF6TlRLLC3QL3AKW5FWqjM8e1rlL5ah5BP30Y4KPxKpCSn9x0vCzTmoFJvbzkK71m6KKbAh9uuk2dfQzG03CgZYYbhykFqDfg2ck88hLeNURulUf2ti5tHy23ApHFDztc9lrqZy43fywld7qGNUfyYcc8jEQ2+6xvCh3qFnjENdi6x+IlZzMCrtjG4HtWtMnodK5syeZMIsSTznM4VowkmvbqueXfPHnn9fUbJSn1hkpcbXanH1v8czvyc2/ZtYGT26m2zT638PrMs+YrhiDnXG6F8g2imhxkcK3ii8Fa3U8qpYsclfsMJx6xv6qQJI9bWhGBMBjqYysQ8b/GV2Bhg8L7e69WC0GyaB0eK0XmBLWna5AjEAOVpMuE6ZWNg5pVRbAm8OvLaA8vrRv6Mvcb/isTGEJkF5iGTsbZZrGYVYFxZxFvXoh/gvy2ySTd5sB+bzfuBVlKKf8bZ90TP
    email: AgB+tw7XKwvKONDa87iTdV0NDHgg9jGIvQRHTKJlQcmKnhUgauxrh+IoC+xnFlJUazMJzE18xb5MvN9qdSRn/FYq8867Mm7Zxb12p4z27mHFEnsP1ViWDR0pYcNyU7KY7eY2+hblIK9XKccpqHYN5WCPaoONBWC/aOzUCZrLaDQYK7YIPh+iLYSEIMqEmJJSuB09WFdUfsBe43X/zagXdtCZ13yfP63VqlaZ/ndWaoNK2velREotxtL5/BNFkmLxibkzqf9b0aNbsjLIwuBsoCeUkuOI9sG9PAB+S6VIvHEfOPGLoffpx4+8eGBFg3+v/t4W2G7HpFjthKPqWjFJI0yPPTMjtWMbagTE4wjQOUbu1DKpRHvWGaQkhSHeTXV+xhn0bt9oKgOpvdTu4fNtldDOt0taUPfT9oZWlMCoe31ANfABG7TJaB6FleSsGV/ePvoTU6qh00EbLimvmrHN6qrRcps+qvZHPVhtbGn34nIBOdnr+q9jFkGIDog8Jz7vVHZq3hFNBqBFeJNrMjnCQRddRquPoBwi1oSNRZbUO7DyKWoFb19/x9y60SGkiMblY/24wE+D9SF+7BdVjkV5h5kNNf9EbLk//fAQceI+COshxP0dzkWfFCF+vb8QVyllz5HM3iiKVaNOsasjh8/Wtlz6D6AQpW+oAiESGFfW5nTdR16FjfCAZQ+umhABXdGSmc1XjLCcv0mfqU5witHRw/A73eQtPQ1I
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: cloudflare
