---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgDQuz3sBxU/VZO2rzztTJqhOt/+IG3lsGK1psZ6UmJ97rOb87Q5W1MI4+C0dfy8qte7iZfmRXTpg20yakWBo0w8Jj3hRtjNzMOin6DpAJou48G9JCbGRQFcok9qu8kJXORLXBmNeB+xoUumklksf5z5J0InR2sEAsT50Fcg6GtawVblCG2zMh8MP/go9ApIHiBcK84DLh7/opZKzOey8pAdVdMAMmIDlmeHUnjeSw/jOi8kVq1VlWGzfMxJko6qMp01PCDna+TC5COSQj+DP63St5t0XT2LQT8XjOY+YzQtWpqSwk+0YvdQro5k6E6FDqeooo5R2r3kZy/9pFKoXPGGocTVmclH5orFSfSvpkkiq5dve0Dq3LXJhkPX7yKWZ1zJrG1Nh7hDemQxHW82PaoBtVXuasjfcTDNE5/Ck4TfUG7rMgo+fH0hU48WJ8u67h6WBXy4Ymgv9DnAyfJv6bwGLEUFGBKIriAZw0/gAiHCzKCGmuzSWF84PS1Jb2GSSqbuKF8hU+AzbUMHj+w5NUFjZ2+1pJz9KD6mOzUULQSaWwzm8iBSvQEwsU0lD0n32EOv5lGDIkv7ncTplozMPgSNvW2FSS3PPmRHDpC2nP9zdmFsWro/6jWFpn9CBGBar1HdTIDDmfvH7OzXiNcdo7doGLiJ343SZ/3/VNrw8ggSaOYi1TlMRNhKgN25E6fP6rqJfOwMDQkPQIr3p1c6zRcGzRm5WqRSlXw9N5mt+F88oNwnO0ZRIE/mhiavUFxVf9oVV0w8XGMGbJdYuymMxYyotPevXd09/7oVz8DWV9tFpuamJ1g0j0TQxh40Ob/7YWWNpVeLBuxN7i9h0jlvyzPsMlE/TcL9GuOqf4YcBLgYlKDkbox9mSy+Xe3YBQhSGqFas71idh5NHqH8tfOMeMdgeA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
