---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgADafs0m4DbYxZD7JDwNWxvxdLI1tVUFdEZK0v19UwttKmD0Q/P4ChTBKbIWBUj+cCr716pY1CkqJHx3CmnCOMPO12bf+Q3zYH8qqBSnXLzCQKD6Tmp07rL+zS02IVsMEW8fC6hxyqKD7zAweGOk6HCXtgPdmkX4gS0DKeDltvKHb1a1r2qIrBDBzNZ4EeLxDA9Xn4MLqEiMKh7+jN0ZN5aZfLsylcC56E/K1LfOSXV0wfijnl+4yxRranhTLzmz4IXpwIh55D/AUk4vAZrsKmiykWUoKKNk89XEINbcCByiTlNxpoJBAHy8Z6t6Juji5NZztI32o7sZ4Aaikv7vNTl9pqi7Dy1w8dXHlhv7XEh6btbzz/p5o/10Zl/RWRVaOW84JUNBi23FznXxzRjV3s2w0ztg29O6IeEYiiAroExmZxxCvtg35Q15rCVKmmHw8J2H6d95egVnIAKUsURVJc3UxtCT312OEgYoHNzgRrppfPnSFpJKWbDTt7kIQhcrJlvm9bERHVWN/68wGbCz29wzOJHuoJxplq/KzjY7PxupzF1sov1NdOy9HcDIlxiR0LyR7jo+KwXe33W8WDiQVMxEICu7aLJlqLhrLER6somIVaUsHkF6FYFRCr/Lv/DoVDYl8Hz3xuyBlrwnzP3iFG/BDFXXqZsZJWN5+492g/FkeP/TPtMm9AqGhNnPDigmM0IsnK84Rhkmfhngz3eWRR05SH5Ahq5QrDOgX9AmlKssbp8Pbwt9YniZjQ7mueLLEDgQgSC5aAC49I5oCtqIpLL/ly6EHVMhk9xrRssa8PJpUActmKTetYraTV1j8Xc3gSBc+zQU1Fw6RzL6B5FvO//1xc/YANFZF5eqiTNqPRmykpxWRlP+Ms8rSVrxKGWBx18L5tjWDdEX0IKD4Zek5zUcw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
