---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAuv1mhiuIQDhQ7W5J9MqOSVxJ/75E80ng+fYnIy/fBG1LrFpjTwuOEVa0D7/v55DUcZllYlLCvdPilK1gfnwXl1YzYR24u5UD26IqXKeZ6v9A/sIZILVgtb0dXZWnxrYZZaz15MdqcPIhPM/shqkVszmjEiEAVXqC3s3xXmxgV5TJxCTPa7gUVY50JAS8t0uR2oYvUvOXbK6oEzBIoCyE/U8xHpcM1FUDqJgMObROkMK0+quOAK68DEFUDj+zOzkNd3uknhvtbwCzgOWBwbJNmS1UCGL2Hp79XLtgR2t9ddRYNcSpgO2bt9Jrh7NkvtJSq/0QR34Cp54hJWUZ4zYqw4hIy3jfmmqf/2LMCSCzW8tsT8/XUbpiTKV0aBZjtbfecjlh5zA5PEkL1uwTFFVD1L9VYCMqNo+OUpO9iT7H4sWDBUQCLnmgmcNw2siiZZNJPbigQTeqpJrkjgt671ByFBGXWw4L3Sx0X46Fx5yMjXiQYCsKImDwcTMiIRtPjqi41lcqZQLSHpuAaJxPGZl2LA1/bWROwmcD5cj2o9zuP498pNyFHgzy3oXaxdAbKo1PzmIcQ0fgws3b7jLt7YtYSZ887i1N6FOgxIRXEVALQcHn7fPsa/ysE97eBBaixZvA0ie6gD3lxikQPuJ4OCzC0wjNu65FM6Eh5A2K8hqCPV92VVeGSlpwsHarE3GKlMVFc68v7Or3bwanZYQCrdgiyRZHenyutgZaMDd3YvsjHmtadHMdR3IKNJ9UHjnC6Uw/3HWiTySbx0ODn7UWHJnM7+/W1AoYgyFtJwqlEG2vq7nuSzKa5lmw0syyoYet3aAzl3TagWuiJdM+MTItdyNCJyMYQKauXYFMLQRGC2v1O35MS1mZh/x4784XCqiNU+kYDPAzHfixUDbj2JoatvYMrIA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
