---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgA1YCjCOMq4S8jZOZT5n+QkEvwO10Lbjl8buFZ7Uc/VRgEg74IjrhbWvfOXYJxdvRAm/r+jBRuw46T0LHkiSPj5Cjg9XT1lnqjY+ma2kR55HV1bJ8p2I+E79WhGkxB5Q/+HeDDVF4giM7ensEd4/Xob0Z0ZERCtP+j/a+C5a5CAtJBWK1ICUwmy63vN+PQIT3qUHOVY+Rbrx9RdOxRnVakNgD7eBnGslgfq8ZHDgakzVBLwFS7uU6H61wyGS+8l6WPkbF/uSKP5Q7llY/L2/tigAZ8S9yAA1a1Nzkp3OIYIAnTIvGY/oAPW8mXjxV1ylQ4xvlcZkAglJ0p3G8WSIqdf5nBEMNbvFl51RQY4r3ToP6B5jIZHiYCjRH0p/6/rU13sdCAEMNQWh7CNBhVcS6ndVqqJUHyroRlz4Fk+pKVa6UcSjLnsl30JyoY3rjUina+RtBR4qxDmcPp4IkOT3qiuraf2um7IXe9icuummhFfG6xQCq1js8Zbo03x8BwKdEqrazBCaoo6SZsEiywES8Mk2jySl1LA2/g3oPa7GbphguMAh4zhuA2RnfR2EdxiGFtZAr7Fw8FnihbE45oHU2R1mg807d1uRisXFcWv6y8ctDpRxdb6CaDm3j2CbyGfsfkl4aqVvW8QXJ/yYZL7JddgSanaY1xAd/iKLH0TWsUFZodXyFNFvtaCq8JNSuhNUD0bFwNBfpKWOSaaTwTqEA92x/Bd9enxU1d8Pz+NOivKm5qgG19QW8Hg6fj7psyaLE07WqCw4RnItpdz2iHTc/9VDtjkMlN2ATBm40EmH5IvYjdgwnnf3jFFggodZF4T3hAP1hN1eZl4d/BcAZ6oS0aB6CdY6T5gLmegr8mXAfbdSG8IHILBG9T/x2wSAREWZWOWggp1ZnXJ1SvlFTaR5eKsjA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
