---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgB42VNlM/n0X5Qa189btfEHv+5jt2SrFr21QtwEk/4lngnMjgNcsdwejr07kp905s1ItWhEGh1VtwGk0EcsgURtPyFQRfvrXO0jOEAxxH2Id09vbMibvx8yzfPSbljhl+JKsYSKrkT3pGE8n4nz0Yx4+/kPkYzSgnRTYHruiFxYSYrKDFca7EidIes+LNjwYYAjanPDIDdurXavUHlHgnnR8Qla+L+HiQrFwPtnt1OFAMt0SHK15iqG8YmOh4Tcd4EcRiSgZC09zRsD3aTEjUIA3y73QMkjJrIvH0b2/6B2H3lSBaS1mrYfE3fqGc8PCgRhwrv4Zwg2NjL5YXmh8z7fjopFGcVKfARagRoI+Tk3ZdaWPJ4l5JbSO1kMJn0jhvfkssDUSmzLdy+9lmWysxvpAjrGWmiolHoS5iFo2Mxb+ulRk5pc8k29abOCJ/HbIZsUA5K6Ddl+0Vz0RF7A9lbxJZruMQgLE4tW0qSb7Ld0G85nLh8c0EDZ/7axCa/AvS0tMrNc6zYVJLm2Z8XZwvSJz+YSaJYr6B1Z/KDjJWQDV5/gmBX6i7kuBmMkJradjlK1Sschz0E8a+4Buihnrem8P8voK4WPVqVvo51QXM3E3lgzbyxUfxPbboJERsG3c+scrPr6rLNDaLgFLvMbPYJBDiY/eri7Gkj83tLIVVT04U3ueqfW73azz2XNX36gRlxvTfuE86b24MSapy47rK6RYo5fMD47vIbl83iH+uMo4hyOaIid0nz6BPfod8xnqdU847M+Z+lJrKSwghf6n/t5QXo+3R6q3trPuBJ+B7hfZIevjnNGxGhtsbLL9oqMMxDJKudESjYBt6s7+EvvjggDNd7gCDB5IAwirPER/UWECQP8bpVUZioD4FfXwxyBE8zqj0XR3JdMN12ZZXwo33djeg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
