---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAw7wauiZD+gogxM3ek+kkB55TMxN/ZZoit/jxFY14jpmGYAD357tcTNhMGXemduNhxwnrrqmlJCC7fiCa63etcIGRocoQL3jyUuCwCHe0a8YnhQK14qfnv4qlEmt1Cz+Qtb8H5MzrA70RA7BNkbwQu9CVlq3ALqXp/npnPzPyuHkiY0qS0DaQj0G8vfQuEJw3W5QV7NTtZjsVM4aMxyVSfhLhGvm1rTLnzr784pdgKKLR81+mFRklEbTRGqKYgdQCphX+DxUy4wpG/abANzkLoZunLYMYzNtC2+gAt8I/kbCO1iHPNkdub0hRq7V+g6ujCKMyRq4QX74P+indxxLzsZ3wfLJDEz4x9dt9zeltQ0KiVZgBKk/y7MyL/m1T0Cy24RCtxcVFRSDu4meeZESCrHl+jD0G/btYuVuwfZ6bjP/ajAQQ4EMU8n9SfovL3al9ai8l0GAOFr4VH+L2RjkpBpXah4Kix0lEYISgxl6oERCbEyIpgf5lHsE5TPigXi0dd4X9qWmkza0tL3Sz/Syq/tLcAvGdV3VdcBiH0p79w+oGfkNcwdCtCwQ5dOA0C7raZN1ShBW6emr8aEwkG31l7XKSvjkgdKkvqmHa1FqBPVaiQzljNg0JKpkRWuQ+Nx+8pnp8IA64wxLDLfr9Ym0qZTCKEXZiNuf3AeZlV6HrkyttWw1x0ZWlcv15UUe/qRAOUXV1olZCKoBqfusC3TTDVTmh+WiH8TYSFL4LAxZKXRr3Don0m1Or6vPu0/aODUoCpTxrXIv4Z/GnJxPU822blJxvk0HsReHZTiMapHdS2OjlOewREA2/YBlhFEC6LM3DR0YdIwahVhT50e9a6sY8t1vOD+cXY9omPO5cZ80BgTCg8dPAcytX62/WuukPIjGFJ7wUYno0ttCocBGshVS4K8w==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
