---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAJOK78Vs6tT7vuhFfC9trUI5w4ttZe3lfLIZXieBfiH6OYZlB3aLUSOPNzrA5++HwYVFAfmy1YgIX4zUF9CMQcePObSoNDCHIpZnbyWOTQ5lMvscGYgdz9NTvwASx4N/CuWUfJQ4bS2N9xeKBbyY5S0XFZj1/6ce10GrL5+bJhowUUZBwcAkTHnARrwDVseKKQd0GAo2bsDFi4jdmjqyj108Z7g8C5/2me9T8l0MHDqx/RsrYGelUr+f6cmTRBAJN6aubs2f4dEdSn1HVHUER4eimGuM2+U8M0/6hQcnUSkGU/a6uUrZ0hnpkCi1LbGnRs10MS7hDRoI9CnUnPS4umIUSEcff7gJ0UVPcwiHz6BTx+OrMbQYMYveT++mfC01BhNS4cmEehwSoYiuflTt+ZZE9l9HZ84o2/jnXzNtYdbh97lvXmsNgSMtczr/I8w+ZJQAwTM4CD1NKNAomBONrns8MbarHQg8TnubjRgF65Rk9ZcKmzD8e4hGR85PghPYYLpFi1EsUraDqgvMrnwYY3uPv8xV1nWBy5kSV0Mt+vWYLG849lcmXRfuJUK1LF/lzqAd3YAEv+Md7TutrrsXBEtOjaJpvwdEb3nXjH3cPMccOTRu6znSvUrrzee9sEFFf2PezD1hpJ+T/RMIHlBzuG8ScxcbD1gge9rgX7RKjHZa/iI/LijNNg+nvOzhR2MeiXV7PoDDbQw/hJYTyFoEPkry2IUJO0cCVW6mN3Uk6mQpDCa/AMnC2Q+ZEIiH/rslWdwmFBJOqCtHkhbA7jUdttA5pK89ET/63LoQSqkaCHz7GFfhZHKiTyiA3w8cP/vOaC8FNd2U9kT9yvy3V2cUxnLzA5lagdT0gNuX3mHR8VSTCsu3N4QuNIZ0yKsyayjrLTGR6jwPpOWRGXZ1MYLRH7kA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
