---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCUD7BVIvxDpJrPwxR6/kccoAe2CSoBab5v9HLf7zbhejULIy4/gUC+5tPI7oviVvPqIS7A+Pv+8cBQlpyxN7K2d9gzBFu3K9jN6IIK3AMTrvvcIMZFtkE/Pqjsc0f77jy6n2ezEnQmWCCbuwZpPMh/7FIr/DPzQMQLGmFjrJ386TjyJlHdlNQP6trl/8QtGgbhTpgmX1vkNIgmq19usp24vjqjyKbgPioQFYr5diJqHB6RnTDrQd6Snrb+b4BVLjzMeSXuXXhHiPC7VGOIEICM2SMdiTXbWz1ScYTNXwY8JEwRMqqQ2GRUJ5Py+hlen+a0amUjgQqw3viUsXahx1PiwFnQSYnoXTG3ltGcCm5PRanUBqovjY8KGqfXJv0ZGjcrlFpqAFqbOJpgx5o/ExYQlxpiL51e/9ng90/DmbzL8hLoNpFHmyCuDqiKGCpDI1xxUMmlzd5bv2oaLKdWPeM7QChSUdnJvoJ6IN459qo5fVHZwaQA0IEO8RndxeMMFpRxOv/YNQz9p2O08uCjiGQCRkENJuao/myCD3qv6BfdbZM3Jovu/naJfc2xompKg7iO5EZd0ZbZSKPPTcRBdakX8b+vsJbZNNE9ZsTnVG4ztghIfJP3a0hHFxqaIO0Mh5QDAjMuTLDfSnlO+cF5ZaubL2XNCHw3IFRrKutbaw06Ixds6GULzcte73yds/Ef4qGxE7om9e2pR2nyCb3q1ATOhQmcHir6aGnNTMElYEHa4MuJTvVkkVRuA7F/Vl9Z2BfMmfGHtzSEICb48OjbKiURJ4JWoR4HtoAqVzizmE8pNoLV/pyseIn2xbRucYVPF4RyopZ+7ipTRPm4WbLPeqN5J+BXcYaHwHLI8T45bqukIqyD7phTo6lYfyhvc6KcUGMZw0r2MOlZ9JU7aScbBlS3PQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
