---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBXjlfFLcuYRhqiJnH5ZBPQru0DeNQwqCZWbSwv/99nI0KT6A7ytdVAmj0R/AuAOrCDdat0fhf4pqLaaBtlZbRJb0Q0Ids6+e5XIdbIt429Xwq0+DAU4qAbiTUKhIQ7cSd2UeNnuzCetopK6y475g3GaqVrJGcXt7oyEwPsHcrCReYe4TE4ua9HLXrjGkbIe6SnoD6GS4AbjfAeWbdP3SONXyfLU5euZFiGBXdaqHgVCwCqLexuipt7MBEabJABlquKwqgfgHQyQrYQ2pvBtDjy/gNGbL3ahFgEk/l9EwyDeH0wG3rYuMDANZoIxoJJlF0FOopx7VQVoibCn/PvxnNLUyolPJfCxNKHOU+u5fGR6UJuX/rWRS3Am9em4nYvjLpmNZ4Hmdneb79n6Ft01RIhdMyexI9T0GzK0Sw8OeU09aB1q7w6DmXOBJu4s3J4y3qP3ouCqH53LnjwBDA1TwquS07e7gItPd69pb0GO0rpObqpOi+uRSeczffasNlVvhhGBP1qqpxRZxTSU1TOw3w3tpKI/8+q46FclfdThbr30ymyehyTvoOYeaSZdYxJXM8W3RhgiwSPTq1PmMWft/kkTBnc3ZZmnNrpC+D18QRtcdtRRuIOAfmh+Uz/FG+uECeQ5mR1zw1asawrGiv3CwYJxEom5e/1SCx2r2xfX9LPaHMBKHuBO3goIjqmA/NxWuO0UEWKKtwe8QFicmUp9WMxtGq+V+pf2mK3Zskvj4vxGDepgC39/jieaY2XC4JyIy2nfOQ63JAPiH9bjntLyKOvCSW9Xbj+Y3BGV9s94WSN8zXXDca7FN5wjyce8toSgEmuWonAjUZtflXql19iDHkk06XtFEcCon1qsOFi0DKs0OLiIa9VooqCHTY1/8VejorpNGhziHxG7Z5haqoqkIeMyQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
