---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgC6PAVmD+WS4oAuyRLulqxrQ36DaT+6OEevvxNWk0q6eoDs8rxR3E9doAXn4/PJ6vKUt5dodJhYkpHGteqDGm/zayz0+DVnKJSUCHgvi2pR0xeyb2eQo4jx6W8Y7dI7yMRantn+iZOjukHKxG44fGyyUkNrBRikn+w25Wp625xT1gqkmyKKxqn6D1WFlCFQvLMpcllIzKElNXyjI5LRX57TrGDZzkBzT708iqRhm/ROzEtxXrfkfqRWKLLyTOFTAn1/0cPqPF0d9n4A6vR/uiV1ugORzB3+Iq2SRR98PzHuNct93sCoCKp8tafAkZPlOor6vvru1itx2jhPSjr9yvjLeojSauTU9GQgAflJ5Pe4ZHjmXhZO9ZV70j07DeH88IQ1hR8+ziBvBDbSU0sEbAnK7sUpvo/VSl9G3MxeeTdEnzH2jCeZdaMwB7iBxugPLBLgjLzLiOczvLfhEpH3vW1W3NzLU7471HY/0WawUa7xxAkD+LEnP/FdvrUuWpXHjV6egNMosRpxjMnRhl7Ub47MS5v2QCd536mvgrTwwXqEVS4Qs9nFA0RMM4ZtTHoda/OdGR14otQfRpObCNtOGhptbZxVQFhiIMpwbKmKfHhM8Y9dNsaNnSkG+Pe+aZvJMtHYFFuJWU117jES0mCOFrRXZX6SWXfdoDzffQD1A/+vI8OmLuWg4U2kufgFF9nF3TeENxZdG5NKwW9bE+PfbvKgFINfSqEOd3iL92QwnfMuMt4A48VXD+NWIb/CMNz6FzEV+kQq2f7a17otjAeOSVUr6Xz/wvvvo8cHGPwxBjN5Ny0sJhidj6nflCtvSTCM80rLC+FDPo6UhCtYex+Tmp0EU/b9kvZalcoxgJ+gxFrdP9npka8znb7iNXqHuh49vGOXAHe2cn5umsud7pbTGCh8yQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
