---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCeNWZKpQuBM1EGsNgRkPzo7NXb3x9b/WCyQY6ZQon2BxNQONCHdQiFboT2meRKR50/nM5Y7QmOra2vxdrjqXX21CkQQK9YHoXwBD+O6OC8SEdB9yn6EWz7CWcXB6lE89Eye+Hdf8gvz602mgft2htY3ZfWJJQ1vJIn0qREB4JhQ3OLZGOF4q1UCdkOu1/3dPrAeg9MKNKvJ6nVXfaZ33WsGxd1GWCpYe8uPWOhZQI/VwE/UlrEN8YW6Hv9eeQO+lcf4UVVfuLqqH/q8NqkGp3EyEilTPNYLF/5GsXoR5kyRGnM0psw8g1utS34Vnebd+N/R3HgtMxiqry6Rlj8yRNwePtrRxhX0Kuv/1w7Ea57sIkyVWVhkccy5UG5qP5HB6SzrZjFUQEkZF61h+3RwqQIpBneHipDBJ6S6Spl4hsqY3b5qGsapCuYvxIl/2un0q363M+dd+ooj3HBNZyCiO3+sV0iGQag5Xh+HHoxLBmf1TYDid7ICOH0OYAVbO2F+aPFstdmlFJJhrbmqhaeh83NYGBTQdoQ1gq3592AH+UgZu9lddbprx66Yb4PgI55eeLJBhJkMYJsETHbUZ8+PhlU8NgRMfnmFyQbdEnSVK7VRXxHAGE4TMqYXvYmjktfwL7n6Q0NjL+vXv+jN5SUqEvFmQ0qL4opdtY6pFzdreDkPua03Cxg6hzBJnOPw4qUCxM5aYB0DxXCHgRm8ECENKkK83dvwGvPoRdYE13wpdlyHQSggLXUs/+wA4V2byiuirWZ27oP70E3F8ljEXQkYNCBoPGJulUhKfvRj/rkpxwauYPLJNe/f3pqVOhuBgonsbzlHN9nOBjiFaRWGiESH1ua5oW6Ml8WD0bkQXBorMW8LoDmUVhNIL/0xWJyzSGB3kb+ePs+pJwBijbY/AgUjjRtwA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
