---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAMYX55LXrGoU80rvWoBRmgcdD88DlEe5NYIxiRRtwUl/V1n+iygpLeyxCHogo0TH9u7DnffZqgk/pKfUaBG4oB4x+AoVOIRi3INOgzdpmhvqSwhdcc9n8lZdilvToVJXIgjC9y1M3JRBaQPsDr2Ef6nYfvUoOADLGpkDjnQ4x/eY4Fai0nvASrpfAoNaP7qoaianRa73ROLwz2WnLJNyD4WaCtQEDPh48qMvR98t/k+cqbbYbI7vwO8nuKOgfdMqhHybCOBWLt+OrMYAlzlHkZYCzF6giWizf1+dSf9loU+lGgG0cVvNvPxORG/PkJgyHd5iVYHnkBtkhsrmC7iaUOj1/RxGvk50+cIWHbd4lmecb+4MXsiQTyMbegiO6bCWh1mbLzMxY8XAP9IcHLPBC0SOiU17+klv3xi2ypPncx/NRILaItYoO1v49JPrXg43iPEZ8V5F/RbGa1xwdOVLTOVXzyeoIvK9VrFGBiztfRfMfMmZFkwNL/3XyemNc5jTcMtcWiHzG8FY4d/n05scNnFAu3OO6+HP9i9E2E6tHsLtmyJEp5G3HupgGuDwk0zmqz5VVhChDR+1RGtnuDLkJ8RacLl2HbWJMyLx/0UDJ1MoCuRo/qE7nKs52lqMn8RFlLdQPA+3FlWjSGAmtXI/ubtPa96aUJaz7wNxxKMkvC3iXXhsD+MJXA+z9BuS9rdmOx29qHMfww5WCQo1FoO2lwP/kZyfBSFEKaiWNs8ap1Os9rs52EqxuL/Ou2Ig5Nwow1b3FWXtQWHPpvADjugO1SHCADqq1i/4NTGH8craxw+rBhwcZ94L9PIJwp9T+TnGWzosAhUvb6erLrBB1W82pLi+RPtzgH9r8KHHB5xbMld/GjqRSegT6E/n/WwrUAX8OBmZZFc95FEifaBBt3ghtKlw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
