---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBgHbZdRb3adcT2cmRkXSbK4VIQUInWpag+kayyiO5hMe3bBonsiEk+Nk18Ezm5EejCorkwgGun1Nx5r8XbG+/Z1JA0hb9u2ujvJfIeJVbLtX3igZWkw85+YbJ7jaZbLT7gc4h+DfTCJ+reErKRZnl0qsfdzoJ+faXiTQR7Pl/u/g3uy9JSW2v2S3/lHx4ei1PqaCuh5/EN5ui+YIJaNpbaZQ1CK8cIj/IywqEslzcgPUFVCyY5MdQB6Jrri3C5TGkf8IJfX2o2KP7pq6liceMDMEZq05o3O/KpfUWO8znn/rsOZh34GDDIfkZobBkMCTQ1C+/YyTnVvVHKz9bO21plkJCRiTNjibkYnw+N6oFUct3A8T8jgmc+BOA36U7smp7qQ4LXOPEDJKte3TjrjJ5yr08bP2vq8s9Ys5hn5wn+0TaNTUFFCl2tH5UP25pzlppr7wDXvIBGwA9tNgMAaVCEOhAChEo5zLyLJsjIgX0FyqOHB0EwS/m67aalKreaFXFpURBW09S+N6HSGh40goDZnZu1YIlOh/Tnjsm1LcNumJXiH41HT6YCQDczTd9khd+a9s12VG0CjdOT1VDvA/Xu8rqucBEEusIeEnm29aeTSDZJpsNs3j/NxIUNaLlde3QOcYlue6kbyIldYnx3fE2AczZ24SFo8Dl9PgXj5UqTjQDZlEdg/cN68iI5KBuBnai0T7Z9cEccAeE6oLNc8zOSsn4wmVQkVDazbMuH+gx2HhlrFAb/rDEAMGlWGuF/tPf248Z5LL+mVWMPowtAWrz0drp+iTPiPlfmDf1LGS5s24XWaFLjf6zODhCij3eQbzNURgjOpX3qz5ttz7nuNFh/Lt1z3Kf/C/e0svPx+qqShP7yzI59pQ9chilImEaiwJiaHFON+GFdtVHo687UxkCQGA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
