---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgDlMvwGMjer2IBT8mgM2K20mvH1BMokZwB87PI4kX8edFdmQ0QoGLy5GjvgpcnvJqjPM3n934uuuA1VAy0br3dBHMlwjIjBjhYv4gR2QEZ1L8RTeKG9ptVz2o7kkXigYM+I43vILvPaayL5YJAqlSquDMgC68bFvjO+uwxsqZ7tpGuVv7+7Hu8NmEfMwT3EosEbYxhxUABvalMAJouOTIv1PvF8BHweNROfm3FF1pksTvlYBlNg42nhs0JxP52BI2Ys8v1WJyDyaplhrrTaSPLZCoxg1VF+5+DHfBmqXdSk+wMw3WM69/H2tof438JBSKC9Uybw3ka+2v0q76qqUxXiw9Ea1bJ1DRgZOzk/WEkJk/OPNFACOidEWHCDfVHp72ayFem7pbz7UHCAk/sx2MCRthC9Ju+6dX68/vxL1AgXdJ/R/8N9X5BZ4s8sWmDjyoQHc3RRwzYIH+Vt1LnSLOWdDjrbAE5ZGEHoeAJ3SuruW9Ekinp0nWRzHLlLbSsFvhRPBm3yCfFrOKujBBPfSyhTn8QjXC2XEpHfkUksSzchdzLMuNtdEKEgZlklEYOr+3S7aqanBHko3/YZ7JQnNbfCFhEsNkNqYhiTE/pkPel9RgRMX62NIb6zIEnEliddG60Ax8I3QF1560BTNAH1QjBRg9qRKHeEOTxBjmfLTUnAVcj9Bfw7QikAW27G9cf5b+63Q7r0u7d5H9oROd2Lubl2EspOMeEAcwfnyx+2tSDmW8YlqaFve0TuRxkAPUuhomv3NG6XwHT73/pZbYGERD8JJ0uw3wkFxZRx9WSIIM56mWljXeotGDxiNJSyLyiLBUjIyRtRe0DH+BtUf6VgI2p75+6d89XOZxblhAOQVprVC5VDeJesWwUdQ/KEH8p90c8yfJh5fKIo7tBVonf4pn5sKw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
