---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAv0b3qqK/vdeEAaLnecMKeWZ2a4o4YnZW0LN5UAjO6oiUjpTK4Lz1uTa62cxQ6WbhE5xTLlrbUvyJNrLeXpY74H52Z/w450FVDYNPx3lK9rKsFB0aHMvgEAsy+CtgofG60DGCZCpMR+mQsG0dTPre/rrKMW+5u7EMy9xnL6tJv8/qAUBxilyD7Tc1+/2Vu5MKRlGhjM8wKdCPaHBaUGHStFs5jB/uDLynec0+rrNrt0hVQzF3wISi5ayurUd8gfffFbM1IpLp4lYnZWFheopQ4+SVM3xpkxHl6gGB7SlRBFru3Kkuv4IiMpdlDV8XBmkznOBWGb/4EAxcKzdx2vL6Ake0PMKb0oOqS6zZgw0zMsQj4JRl504Qz5yDyHcbNSKEi1dqJSmMmkYfKA+E7C5hVHFICp3oS2l8jVRzcEgV1VyJoXeAJj9zVcwrkxHhyKfHFvvajvtEMPdVWpCWeRQlW0W1L9l+VZGtZkE4Acswivk0gbQTHaZ66PD8VxGHw2urn5wZ4L9/KQbQZLuBiy09kKtekM8jdTCCRT+F/yX2zephrrl/0p7VIirv+7GrJXNqtLGwzOsUnFYZ1n4VV6AdyHOvmvu97Pogu8Zdc2tw+nIYXm9eXYC8uCyYDdyVxCSlpMNCkeDk5yIx0QUMBJzvB6vuHmmEkrh+v9JmS8UHdYUfVyyWdaa1flMqXLSSHP3TC6DWu8OoDHVZLHS1+rvIkWOoEzwtG+5eha0JiQjW6nNUDCH4Sn85a41CdnHqa3IBV9YsMfBQP6/+JPhKmDTQhpsPTfDuwVnE5slGEQ1k0Wf5/uIKsdM5tLnQXgzv/NrrcJdNuuXPVhnqNTUk9sNK6IDXXbIDPVm0AupQG5jyFIJ8KEzru2btRCPf2c4DTkf9RN8ukfnXAAPlU0SYpBC/Wtw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
