---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAOEex+U4znp7Eb0DaHZ0bi6o84MjfO5ZsjRvj3k85RLb+BKzD507UTpKHvmKv1aHGYfaPxU9bxFX+cUHRAzFD078nhuhyeGzgLTuPekhR5c4OpIyZBQFeKW4M4Ii7nui6bqPNa4xCIeLNRkLKE4vBic8f+9cfs/vzeg+6SpEA7lnZQ8HFaSZiVQmu1wAPEFSblJHGWkRTMlyNyFuv/nRAJx5U1oHdzpmCi37L1ymXA/WfHNEtlbfMxVfHQXE00aFq2h+BqzrlH5kyl0Q/QAiIN0z1HlQS5YREBvcDIFSJQhm4fa1yGAMbxUAPc8gdKbQiCX1/zHds/8BJR7ygP2xRJxotMEkZLMSq3i+a4n37skjc7YBM6QdFKPDH7Xrf/4PSkI3a4zrvQYenbGEe5BCi0hQdhH8+v/0nMxaFbIgGyxyNzfrquMzkAdIq4EOmIhdkgKUPOvej7RtDJyMrtgfggHs+p8k7F+2fQZqBrNMEeaD2uB4xhZS/KD5Fjfkixeb4GZn9WOMMPsmJgXN3C4YeWTq1XNvtnUHhz28xreCi2icPJ6/3yOIVtp63D/Gmu8zvDRVD0SJ0mR0id92SYraqEi2lB6TcFFYphvuxBpAgFRx3Z4cPH3rdNlAJSrsB4eMnnGcpP75Yx+HLIePPYw2vBqbnhZXlc+KWTQ9EYi2YFLHkTs2GkgUPwP03djC68mb6/tGjV9XzGBNdm/o0EmkAhLIfalPgTpStf3msvHPXBVRCih080vJnxAYLJkqBWInZQaBAha5d75S9/sqwPeOoRq/xkx1TanwEh42mCP7yoJ85vD2CYOvxMqmpOS689V4mRL/MsuT56OMBBu3Pjsbzf9+8439Fl6pKX++UV/jbeXGnTkWE2srbGCWsl+k30pIcaLNQ0+LSbRd11pJA0Qmw5GA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
